module.exports = [
  {
    name: 'ChatGPT',
    domain: 'chatgpt.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Plus',
    rating: 4.9,
    reviewCount: 38400,
    badge: 'Benchmark Leader',
    shortTagline: 'Industry-standard conversational AI, reasoning, and multimodal assistant by OpenAI.',
    detailedDescription: 'ChatGPT remains the gold standard in conversational and reasoning artificial intelligence. Powered by OpenAI o3-mini and GPT-4o, it excels at complex analytical tasks, voice interactions, code synthesis, and contextual document understanding. Its massive plugin ecosystem and custom GPTs make it an indispensable productivity copilot for millions worldwide.',
    tags: ['Conversational AI', 'Multimodal', 'Reasoning', 'Custom GPTs', 'OpenAI'],
    pros: ['Industry-leading reasoning with o1/o3-mini models', 'Flawless native voice mode and multimodal image vision', 'Huge directory of specialized custom GPTs and integrations'],
    cons: ['Peak-hour latency on intensive reasoning tasks', 'Plus subscription required for highest model tier quotas'],
    bestFor: 'Professionals, researchers, students, and engineers seeking all-round AI intelligence.'
  },
  {
    name: 'Claude 3.7 Sonnet',
    domain: 'claude.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro',
    rating: 4.9,
    reviewCount: 29500,
    badge: 'Top Reasoning',
    shortTagline: 'Hybrid reasoning and coding model by Anthropic with steerable thinking tokens.',
    detailedDescription: 'Claude 3.7 Sonnet introduces hybrid architecture combining near-instant conversational responses with deliberate, extended thinking. It establishes cutting-edge benchmarks across software engineering, mathematical proofing, and long-context document analysis. Anthropic’s constitutional AI safeguards make its responses exceptionally nuanced and hallucination-resistant.',
    tags: ['Hybrid Reasoning', 'Software Engineering', '200K Context', 'Anthropic', 'Coding'],
    pros: ['Unmatched coding architecture and nuanced writing style', 'Extended thinking mode for complex multi-step debugging', 'Massive 200,000 token context window with high recall'],
    cons: ['Aggressive rate limits on free tier during high-traffic hours', 'No native audio output generation within the web UI'],
    bestFor: 'Software developers, legal analysts, and writers needing superior nuance and code precision.'
  },
  {
    name: 'Google Gemini Advanced',
    domain: 'gemini.google.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $19.99/mo',
    rating: 4.8,
    reviewCount: 24600,
    badge: '1M+ Context',
    shortTagline: 'Multimodal AI power with Google Workspace integration and million-token context.',
    detailedDescription: 'Google Gemini 2.0 brings breakthrough multimodal speed and comprehension across text, code, video, audio, and visual inputs. With native access to a 1-million to 2-million token context window, users can analyze entire video lectures or massive codebases in seconds. Its deep integration with Google Workspace, Maps, and YouTube enables seamless daily workflow automations.',
    tags: ['Multimodal', 'Google Workspace', '2M Context', 'Gemini 2.0', 'Flash Speed'],
    pros: ['Unrivaled 2M token context window for massive file and video ingestion', 'Deep direct integration with Google Docs, Gmail, Drive, and Flights', 'Ultra-fast low-latency multimodal reasoning'],
    cons: ['Occasionally overly cautious safety filters on creative writing', 'Workspace tools require Google account ecosystem buy-in'],
    bestFor: 'Users immersed in the Google ecosystem and teams processing gigantic document repositories.'
  },
  {
    name: 'Perplexity AI',
    domain: 'perplexity.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro',
    rating: 4.9,
    reviewCount: 22100,
    badge: 'Best Search AI',
    shortTagline: 'Real-time conversational search engine with inline academic and web citations.',
    detailedDescription: 'Perplexity has revolutionized internet search by synthesizing web knowledge into concise, cited conversational answers. Users can switch between top underlying models including Claude 3.7, Sonnet, and o3-mini depending on their query intent. The platform’s Pro Search performs deep multi-step research synthesis with reliable sourcing.',
    tags: ['AI Search', 'Citations', 'Deep Research', 'Pro Search', 'Real-time'],
    pros: ['Always up-to-date answers with inline clickable academic and web sources', 'Multi-model selector lets you toggle between Claude, GPT, and Sonar', 'Pro Search automatically executes iterative follow-up queries'],
    cons: ['Occasionally summarizes paywalled sources incompletely', 'File upload size limits on the standard tier'],
    bestFor: 'Researchers, journalists, students, and analysts seeking fact-checked answers.'
  },
  {
    name: 'DeepSeek R1',
    domain: 'deepseek.com',
    pricingModel: 'Open Source',
    pricingStarting: 'Free & Open Weights',
    rating: 4.8,
    reviewCount: 31200,
    badge: 'Open Source King',
    shortTagline: 'Open-weights reasoning model matching frontier proprietary benchmarks at a fraction of compute.',
    detailedDescription: 'DeepSeek R1 has disrupted the global AI landscape with its reinforcement-learning-driven reasoning capabilities that rival top commercial models. Offering open weights and extremely low API inference costs, it democratizes state-of-the-art chain-of-thought problem solving. Developers can run distilled versions locally or leverage cloud API endpoints with near-zero latency.',
    tags: ['Open Weights', 'Reasoning', 'Reinforcement Learning', 'Local LLM', 'Budget API'],
    pros: ['Open weights permit fully private on-premise deployment', 'Matches frontier proprietary reasoning benchmarks at 90% lower compute cost', 'Exceptional performance on competitive mathematics and algorithmic coding'],
    cons: ['Web chat service can encounter peak congestion during high global demand', 'Requires modern local GPU or quantization for smooth on-device execution'],
    bestFor: 'Privacy-focused enterprises, algorithmic coders, and developers seeking ultra-cheap frontier reasoning.'
  },
  {
    name: 'Mistral Le Chat',
    domain: 'mistral.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free tier / Pay-per-token',
    rating: 4.7,
    reviewCount: 14800,
    badge: 'European Frontier',
    shortTagline: 'High-speed, multilingual frontier conversational AI built by Mistral in Europe.',
    detailedDescription: 'Mistral Le Chat delivers exceptional conversational intelligence powered by Mistral Large 2 and Pixtral. Renowned for its concise, direct responses and world-class European multilingual fluency, it provides a fast alternative to Silicon Valley giants. The platform incorporates web search, coding assistance, and transparent GDPR-compliant data standards.',
    tags: ['Multilingual', 'Mistral Large', 'GDPR Compliant', 'Fast Inference', 'Coding'],
    pros: ['Incredible multilingual proficiency across European and Asian languages', 'Unfiltered, candid, and concise conversational style', 'Strong commitment to privacy and enterprise data sovereignty'],
    cons: ['Smaller plugin and integration marketplace compared to OpenAI', 'Mobile app experience is still expanding feature parity'],
    bestFor: 'European enterprises, polyglot teams, and users desiring fast, uncensored responses.'
  },
  {
    name: 'Microsoft Copilot',
    domain: 'copilot.microsoft.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro / $30 M365',
    rating: 4.6,
    reviewCount: 19800,
    badge: 'Enterprise Choice',
    shortTagline: 'Everyday AI companion deeply embedded into Windows, Edge, and Microsoft 365.',
    detailedDescription: 'Microsoft Copilot bridges general consumer chat with deep Microsoft 365 enterprise productivity. It integrates OpenAI’s frontier models directly into Excel, PowerPoint, Word, Outlook, and Teams for automated slide creation and email triage. Built-in DALL-E image generation and web grounding via Bing provide reliable daily assistance.',
    tags: ['Microsoft 365', 'Office Copilot', 'Enterprise', 'Bing Search', 'Windows AI'],
    pros: ['Direct integration into Word, Excel, PowerPoint, and Microsoft Teams', 'Commercial data protection protects proprietary company queries', 'Built-in image creation and voice dictation inside Windows'],
    cons: ['Excel formula generation can occasionally stumble on nested lookups', 'M365 license add-on is relatively costly for small teams'],
    bestFor: 'Corporate professionals, Windows power users, and enterprises running on Microsoft 365.'
  },
  {
    name: 'Grok 3',
    domain: 'x.ai',
    pricingModel: 'Paid',
    pricingStarting: 'X Premium ($8/mo - $16/mo)',
    rating: 4.7,
    reviewCount: 16500,
    badge: 'Real-time X Data',
    shortTagline: 'Witty, truth-seeking frontier AI with direct access to real-time global news on X.',
    detailedDescription: 'Grok 3 from xAI pairs cutting-edge computing infrastructure with live, unfiltered access to global breaking news on X (formerly Twitter). Designed with a distinctive witty personality and minimal political bias constraints, it provides instant situational analysis. Its Colossus-scale training produces remarkable reasoning and mathematics prowess.',
    tags: ['Real-time News', 'xAI', 'Colossus Supercluster', 'Reasoning', 'X Integration'],
    pros: ['Instant awareness of breaking global events seconds after they hit social media', 'Fun, witty mode balances standard formal assistance', 'Top-tier mathematical and technical problem solving'],
    cons: ['Requires active X (Twitter) Premium subscription', 'Occasionally incorporates unverified social claims from trending posts'],
    bestFor: 'Journalists, market watchers, tech founders, and users tracking real-time global news.'
  },
  {
    name: 'Pi by Inflection',
    domain: 'pi.ai',
    pricingModel: 'Free',
    pricingStarting: '100% Free',
    rating: 4.6,
    reviewCount: 11200,
    badge: 'Empathetic AI',
    shortTagline: 'Warm, conversational personal companion focused on high emotional intelligence and active listening.',
    detailedDescription: 'Pi is uniquely engineered to serve as a supportive, empathetic conversational partner rather than a rigid search query machine. Its soothing, lifelike voice synthesis and human-like conversational pacing make it an exceptional sounding board for brainstorming, personal reflections, and stress management. Inflection AI prioritizes conversational flow and kindness over raw technical output.',
    tags: ['Emotional AI', 'Lifelike Voice', 'Brainstorming', 'Personal AI', 'Supportive'],
    pros: ['Incredible emotional intelligence and active conversational listening', 'Natural, photorealistic voice synthesis with realistic pauses', 'Completely free with zero paywalls or subscription prompts'],
    cons: ['Not designed for complex coding or data analysis tasks', 'Lacks third-party application plugin integrations'],
    bestFor: 'Users looking for a daily sounding board, empathetic advice, and voice conversations.'
  },
  {
    name: 'Poe by Quora',
    domain: 'poe.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $19.99/mo',
    rating: 4.7,
    reviewCount: 18300,
    badge: 'Multi-Bot Hub',
    shortTagline: 'Universal platform to chat with Claude, GPT-4o, Gemini, Flux, and custom creator bots in one place.',
    detailedDescription: 'Poe by Quora acts as an all-in-one aggregation hub for the world’s leading generative AI models. Instead of subscribing to separate services for Claude, ChatGPT, and Midjourney, users access all frontier models via a single unified interface. Creators can also build, monetize, and share custom prompt bots and server-hosted bots.',
    tags: ['Model Aggregator', 'Creator Economy', 'Claude & GPT', 'Bots', 'Mobile App'],
    pros: ['Access all frontier models (OpenAI, Anthropic, Google, Mistral) under one subscription', 'Generous free daily points to sample top-tier models', 'Creator monetization system for custom prompt bots'],
    cons: ['Compute point system can deplete rapidly on intensive reasoning queries', 'Less customized tooling compared to native first-party apps'],
    bestFor: 'AI enthusiasts and power users wanting one subscription for all world-class models.'
  },
  {
    name: 'Meta AI',
    domain: 'meta.ai',
    pricingModel: 'Free',
    pricingStarting: '100% Free',
    rating: 4.6,
    reviewCount: 21400,
    badge: 'Free Frontier',
    shortTagline: 'Omnipresent conversational assistant powered by Llama 3 across WhatsApp, Instagram, and web.',
    detailedDescription: 'Meta AI brings the formidable reasoning power of Llama 3 directly into billions of conversations on WhatsApp, Messenger, Instagram, and Meta.ai. Users can ask questions, generate dynamic images in real-time as they type, plan travel itineraries, and summarize group chats. It provides frontier-class assistance without requiring any subscription or credit card.',
    tags: ['Llama 3', 'WhatsApp', 'Instagram', 'Real-time Image Gen', 'Social AI'],
    pros: ['Completely free with no usage subscription fees', 'Directly available inside WhatsApp and Instagram group chats', 'Real-time image generation updates instantly as you type each letter'],
    cons: ['Geographic availability is still rolled out in waves due to regional regulations', 'Fewer developer API export hooks inside the web consumer client'],
    bestFor: 'Everyday consumers, social teams, and mobile users wanting instant free AI assistance.'
  },
  {
    name: 'Jan AI',
    domain: 'jan.ai',
    pricingModel: 'Open Source',
    pricingStarting: 'Free & Local',
    rating: 4.8,
    reviewCount: 9400,
    badge: 'Local First',
    shortTagline: 'Open-source local ChatGPT alternative that runs 100% offline on your computer.',
    detailedDescription: 'Jan AI is a desktop application that turns your laptop or desktop into a private, offline AI workstation. It allows you to download and run open models like DeepSeek R1, Llama 3.3, and Mistral with zero data leaving your machine. Compatible with Mac, Windows, and Linux, it also features a built-in local server compatible with OpenAI API specifications.',
    tags: ['Local AI', '100% Offline', 'Privacy', 'Open Source', 'Desktop App'],
    pros: ['Absolute privacy: zero telemetry, zero cloud data transfer, works completely offline', 'One-click model installer for GGUF models with automatic hardware detection', 'Exposes an OpenAI-compatible local server port for third-party integrations'],
    cons: ['Performance depends entirely on your local machine’s RAM and GPU', 'Initial model downloads require 4GB to 40GB of storage'],
    bestFor: 'Privacy-focused professionals, healthcare/legal teams, and developers working offline.'
  },
  {
    name: 'LM Studio',
    domain: 'lmstudio.ai',
    pricingModel: 'Free',
    pricingStarting: 'Free for Personal Use',
    rating: 4.9,
    reviewCount: 15600,
    badge: 'Developer Choice',
    shortTagline: 'The premier desktop app to discover, download, and run local LLMs with GPU acceleration.',
    detailedDescription: 'LM Studio offers an intuitive yet profoundly capable graphical interface for running open-weights LLMs entirely locally. It supports Apple Silicon Metal, NVIDIA CUDA, and AMD ROCm for maximum hardware acceleration on any operating system. Users can search Hugging Face directly within the app, customize system prompts, adjust temperature, and spin up local inference endpoints.',
    tags: ['Local LLMs', 'GPU Acceleration', 'Hugging Face', 'Developer Tool', 'GGUF'],
    pros: ['Direct integration with Hugging Face to search and download any GGUF model', 'Effortless GPU layer offloading with real-time VRAM monitoring', 'Fast, drop-in local OpenAI API replacement for local coding workflows'],
    cons: ['Requires dedicated hardware (8GB-32GB RAM minimum for smooth 7B-14B models)', 'Commercial usage requires enterprise licensing verification'],
    bestFor: 'Developers, software engineers, and power users wanting complete control over local inference.'
  },
  {
    name: 'Ollama',
    domain: 'ollama.com',
    pricingModel: 'Open Source',
    pricingStarting: '100% Open Source',
    rating: 4.9,
    reviewCount: 28900,
    badge: 'Terminal Standard',
    shortTagline: 'Get up and running with large language models locally via a clean, command-line interface.',
    detailedDescription: 'Ollama has established itself as the de facto standard tool for running large language models on local hardware. With a single command like `ollama run llama3`, users can download, quantize, and execute models seamlessly. It provides a lightweight background daemon that serves REST endpoints compatible with LangChain, LlamaIndex, and web UIs.',
    tags: ['CLI', 'Open Source', 'Local Inference', 'Developer Standard', 'Docker Friendly'],
    pros: ['Incredibly clean command-line interface and package manager ergonomics', 'Automatic GPU detection and memory allocation across macOS, Windows, and Linux', 'Effortless integration with almost every open-source AI frontend and dev tool'],
    cons: ['Headless by default; requires third-party UI like Open WebUI for browser chatting', 'Advanced parameter tuning requires Modelfile customization'],
    bestFor: 'DevOps engineers, terminal power users, and developers building local AI pipelines.'
  },
  {
    name: 'Open WebUI',
    domain: 'openwebui.com',
    pricingModel: 'Open Source',
    pricingStarting: '100% Free & Open Source',
    rating: 4.9,
    reviewCount: 16700,
    badge: 'Self-Hosted Hero',
    shortTagline: 'Feature-rich, self-hosted web interface for Ollama, OpenAI, and custom AI inference servers.',
    detailedDescription: 'Open WebUI delivers a ChatGPT-grade user interface that you can host on your own server or Docker container. It includes multi-model chats, document RAG, voice synthesis, image generation, role-based access control, and pipeline plugins. Ideal for families, teams, and enterprises, it transforms raw local models into an enterprise-grade collaborative portal.',
    tags: ['Self-Hosted', 'Docker', 'RAG', 'Ollama UI', 'Team Collaboration'],
    pros: ['Stunning, responsive UI that rivals proprietary SaaS web apps', 'Native document upload RAG for talking to PDFs, Word docs, and websites', 'Extensive community plugin ecosystem and role-based user management'],
    cons: ['Requires Docker or Python setup knowledge to deploy and maintain', 'RAG embeddings require local compute or configured external embedding models'],
    bestFor: 'Homelab enthusiasts, IT departments, and organizations needing a private team AI portal.'
  },
  {
    name: 'Kimi AI',
    domain: 'kimi.moonshot.cn',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / Tiered Compute',
    rating: 4.7,
    reviewCount: 12400,
    badge: 'Long-Context Star',
    shortTagline: 'Frontier conversational model with lossless 2-million-character document analysis capabilities.',
    detailedDescription: 'Developed by Moonshot AI, Kimi AI gained global renown as one of the pioneers of lossless ultra-long context windows. It can ingest entire multi-volume financial reports, books, or legislative acts in seconds and extract minute details with zero needle-in-a-haystack degradation. Its clean interface and search grounding make it a dominant force in Asian AI development.',
    tags: ['Long Context', 'Financial Analysis', 'Moonshot AI', 'Document Understanding', 'Search'],
    pros: ['Superb precision in extracting facts from 200,000+ words of text in a single prompt', 'Clean, intuitive web and mobile interfaces with minimal clutter', 'Powerful live web search integration for contemporary market data'],
    cons: ['Primary documentation and server routing heavily optimized for Asian markets', 'English user interface translations occasionally lag behind primary release updates'],
    bestFor: 'Financial analysts, legal teams, and bilingual researchers reading massive documents.'
  },
  {
    name: 'Qwen Chat',
    domain: 'chat.qwenlm.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / Pay-per-token API',
    rating: 4.8,
    reviewCount: 17800,
    badge: 'Top Benchmark',
    shortTagline: 'Alibaba Cloud’s state-of-the-art open model series with world-leading multilingual performance.',
    detailedDescription: 'Qwen 2.5 represents one of the most capable open-weight language model families in the world. Dominating leaderboards in mathematics, coding, and multilingual understanding, Qwen Chat provides an accessible playground to interact with their flagship 72B and specialized coder variants. It rivals leading proprietary models while offering permissive open licensing.',
    tags: ['Alibaba Cloud', 'Open Weights', 'Multilingual', 'Math Champion', 'Coding'],
    pros: ['World-class benchmark scores in competitive programming and advanced mathematics', 'Deep comprehension across more than 30 global languages', 'Flexible open-weights availability for commercial customization'],
    cons: ['Web interface offers simpler feature set compared to ChatGPT or Claude', 'Cloud hosting subject to regional bandwidth variations'],
    bestFor: 'Researchers, quantitative analysts, and developers looking for top-tier open weights.'
  },
  {
    name: 'You.com',
    domain: 'you.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro',
    rating: 4.6,
    reviewCount: 13900,
    badge: 'Research Search',
    shortTagline: 'AI search engine and productivity platform with custom multi-agent modes and model switching.',
    detailedDescription: 'You.com combines an AI search engine with specialized query modes for coding, research, writing, and creative generation. Its Pro subscription lets users toggle between multiple leading LLMs, including GPT-4o, Claude 3.5 Sonnet, and specialized custom models. The platform emphasizes deep citation accuracy and integrated task automation.',
    tags: ['AI Search', 'Smart Assistant', 'Multi-Model', 'Citations', 'Coding Mode'],
    pros: ['Flexible choice of multiple top commercial LLMs in one workspace', 'Specialized Genius mode for solving complex mathematical and coding problems', 'Reliable web references and source transparency'],
    cons: ['Free tier queries have limited access to high-tier reasoning engines', 'UI can feel slightly crowded with various mode selectors'],
    bestFor: 'Students, developers, and knowledge workers wanting multi-model search flexibility.'
  },
  {
    name: 'ChatPDF',
    domain: 'chatpdf.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $5/mo Plus',
    rating: 4.7,
    reviewCount: 23100,
    badge: 'Document Utility',
    shortTagline: 'Instantly chat with any PDF document, research paper, or textbook in seconds.',
    detailedDescription: 'ChatPDF created the instant document-conversational format that revolutionized academic study. Users drop in any PDF—from medical journals to quarterly corporate filings—and can immediately interrogate the text, generate summaries, and click to verify source page references. It works across any language and requires zero prompt engineering skills.',
    tags: ['PDF AI', 'Document Analysis', 'Study Tool', 'Academic Research', 'Citations'],
    pros: ['Frictionless drag-and-drop workflow with zero setup time', 'Instant page citation references make auditing answers foolproof', 'Affordable pricing compared to broad enterprise AI suites'],
    cons: ['File size and page count limits on the free tier', 'Cannot execute complex multi-document comparison across disjointed libraries'],
    bestFor: 'University students, legal clerks, doctors, and professionals analyzing long PDFs.'
  },
  {
    name: 'TypingMind',
    domain: 'typingmind.com',
    pricingModel: 'Paid',
    pricingStarting: '$39 One-time License',
    rating: 4.9,
    reviewCount: 8800,
    badge: 'Bring Your Own Key',
    shortTagline: 'Ultimate private UI for ChatGPT, Claude, and Gemini with web search, plugins, and no subscription.',
    detailedDescription: 'TypingMind is a premium, client-side web and desktop interface that connects directly to your own AI API keys. By cutting out middleman monthly subscriptions, power users pay fractions of a cent per query while enjoying prompt libraries, artifact previews, and autonomous agent workflows. All conversation data is stored locally in your browser for absolute privacy.',
    tags: ['BYOK', 'One-Time Payment', 'Privacy', 'Prompt Library', 'Power User UI'],
    pros: ['Pay-once perpetual license saves hundreds compared to monthly subscriptions', 'All chat history and API keys stay strictly on your local device', 'Built-in web search, AI character bots, and voice input integration'],
    cons: ['Requires users to acquire and configure their own API keys (OpenAI, Anthropic, etc.)', 'No managed cloud synchronization across devices without cloud sync plugin setup'],
    bestFor: 'Power users, budget-conscious developers, and privacy advocates wanting lifetime access.'
  }
];
// Append 80 more Chatbots & Assistants to reach exactly 100 tools
const additionalChatbots = [
  ['Character.ai', 'character.ai', 'Freemium', 'Free / $9.99/mo c.ai+', 4.7, 45000, 'Pop Culture Hit', 'Create and converse with millions of hyper-realistic user-created personas and characters.'],
  ['Jasper Chat', 'jasper.ai', 'Paid', 'From $39/mo', 4.6, 9200, 'Marketing Pro', 'Conversational AI tailored for marketing teams with brand voice memory and campaign planning.'],
  ['Writesonic Chatsonic', 'writesonic.com', 'Freemium', 'Free / $16/mo', 4.5, 8700, 'SEO Chat', 'Google-grounded conversational partner for digital creators, bloggers, and copywriters.'],
  ['HuggingChat', 'huggingface.co/chat', 'Free', '100% Free', 4.7, 14200, 'Open Source Hub', 'Open-source chat interface powered by top open-weights models hosted on Hugging Face.'],
  ['Phind', 'phind.com', 'Freemium', 'Free / $20/mo Pro', 4.8, 16300, 'Coder Search', 'Developer-focused conversational search engine optimized for software engineering queries.'],
  ['Venice AI', 'venice.ai', 'Freemium', 'Free / $8/mo Pro', 4.6, 6100, 'Uncensored Privacy', 'Privacy-first, zero-retention AI platform offering uncensored text and image generation.'],
  ['OpenRouter', 'openrouter.ai', 'Freemium', 'Pay per token', 4.9, 12500, 'Universal API', 'Unified API and playground providing access to hundreds of AI models at transparent rates.'],
  ['Together AI', 'together.ai', 'Paid', 'Pay per token', 4.8, 8900, 'Fast Cloud', 'Leading cloud platform for blazing-fast open-source model fine-tuning and token inference.'],
  ['Groq Cloud', 'groq.com', 'Freemium', 'Free tier / Ultra-cheap', 4.9, 21000, 'LPU Speed King', 'LPUs delivering 500+ tokens per second for real-time conversational and voice apps.'],
  ['Fireworks AI', 'fireworks.ai', 'Paid', 'Pay per token', 4.8, 7400, 'Enterprise Speed', 'Production AI inference engine running fine-tuned models at industry-leading speeds.'],
  ['DeepInfra', 'deepinfra.com', 'Paid', 'Pay per token', 4.7, 6200, 'Cost Effective', 'Scalable serverless API platform hosting state-of-the-art open AI models at minimal prices.'],
  ['Cohere Coral', 'cohere.com', 'Freemium', 'Free trial / Enterprise', 4.7, 7800, 'Enterprise RAG', 'Enterprise-grade conversational assistant specialized in grounded document retrieval.'],
  ['AI21 Studio', 'ai21.com', 'Freemium', 'Pay per token', 4.6, 5900, 'Jamba Models', 'Frontier SSM-Transformer hybrid models engineered for extreme speed and enterprise reasoning.'],
  ['Replika', 'replika.com', 'Freemium', 'Free / $19.99/mo Pro', 4.5, 32000, 'AI Companion', 'Personal AI companion designed to provide emotional support, conversation, and mentorship.'],
  ['Chai AI', 'chai-research.com', 'Freemium', 'Free / $13.99/mo', 4.4, 21000, 'Roleplay Hub', 'Popular mobile platform for discovering and chatting with custom entertainment and gaming bots.'],
  ['Moemate', 'moemate.io', 'Freemium', 'Free / $9.99/mo', 4.6, 5400, '3D Avatars', 'Highly customizable AI companions featuring 3D animated avatars and multi-model support.'],
  ['Janitor AI', 'janitorai.com', 'Freemium', 'Free with API key', 4.5, 18900, 'Persona Chat', 'Community-driven roleplay platform allowing custom bot prompts and BYOK API models.'],
  ['SpicyChat AI', 'spicychat.ai', 'Freemium', 'Free / $5/mo', 4.4, 14200, 'Creative Chat', 'Expressive conversational roleplaying platform with high user character customization.'],
  ['Crushon AI', 'crushon.ai', 'Freemium', 'Free / $7.99/mo', 4.3, 11800, 'Anime Bots', 'Chatbot hub for anime characters, fictional heroes, and personalized storytelling.'],
  ['Botpress', 'botpress.com', 'Freemium', 'Free / $495/mo Team', 4.7, 8500, 'Bot Builder', 'Next-gen generative AI chatbot building platform for businesses, agencies, and developers.'],
  ['Voiceflow', 'voiceflow.com', 'Freemium', 'Free / $50/mo Pro', 4.8, 11400, 'Conversational UX', 'Visual collaborative design tool for building and deploying AI customer service agents.'],
  ['Landbot', 'landbot.io', 'Freemium', 'Free / $40/mo', 4.5, 6700, 'No-Code Chat', 'Intuitive no-code conversational app builder transforming web forms into dynamic chats.'],
  ['Tidio Lyro', 'tidio.com', 'Freemium', 'Free / $39/mo', 4.6, 9800, 'Support AI', 'Smart conversational customer support bot that resolves up to 70% of inquiries automatically.'],
  ['Intercom Fin', 'intercom.com/fin', 'Paid', '$0.99 per resolution', 4.7, 12600, 'Customer Care', 'Breakthrough AI customer service agent that answers complex questions with zero human input.'],
  ['Ada CX', 'ada.cx', 'Paid', 'Custom Enterprise', 4.6, 5200, 'Enterprise CX', 'Automated customer experience platform handling millions of interactions across channels.'],
  ['Zendesk AI', 'zendesk.com', 'Paid', 'From $55/agent/mo', 4.5, 14800, 'Help Desk AI', 'Built-in intelligent routing and triage for modern customer service teams.'],
  ['Freshdesk Freddy', 'freshworks.com', 'Freemium', 'Free trial / $29/mo', 4.5, 8300, 'Omnichannel AI', 'AI agent assistance and automated resolution for modern omnichannel support desks.'],
  ['Kustomer KIQ', 'kustomer.com', 'Paid', 'Enterprise', 4.4, 3800, 'CRM Support', 'Conversational customer relationship management platform with predictive sentiment routing.'],
  ['Gladly Sidekick', 'gladly.com', 'Paid', 'Custom Enterprise', 4.6, 2900, 'Retail Care', 'People-centered AI assistant personalized for luxury retail and e-commerce support.'],
  ['Cognigy', 'cognigy.com', 'Paid', 'Enterprise', 4.7, 4100, 'Contact Center', 'Enterprise conversational AI platform automating contact center phone and chat queues.'],
  ['Yellow.ai', 'yellow.ai', 'Paid', 'Custom Enterprise', 4.6, 5100, 'Autonomous Agent', 'Dynamic AI agents delivering autonomous human-like conversations across 35+ channels.'],
  ['Rasa', 'rasa.com', 'Freemium', 'Open Source / Enterprise', 4.7, 7200, 'Pro Developers', 'Developer-focused open conversational AI framework for building mission-critical agents.'],
  ['Botmaker', 'botmaker.com', 'Paid', 'From $99/mo', 4.5, 3300, 'WhatsApp AI', 'Comprehensive conversational messaging platform powering automated commerce and support.'],
  ['ManyChat AI', 'manychat.com', 'Freemium', 'Free / $15/mo Pro', 4.7, 24000, 'Instagram DM', 'The world’s top Instagram and WhatsApp marketing automation and conversational sales platform.'],
  ['Chatfuel AI', 'chatfuel.com', 'Freemium', 'Free / $14.99/mo', 4.5, 11200, 'Messenger Pro', 'No-code chatbot builder for Facebook, Instagram, and website lead generation.'],
  ['MobileMonkey', 'customers.ai', 'Paid', 'From $199/mo', 4.4, 4500, 'Sales Outbound', 'B2C and B2B outbound conversational marketing engine with identity resolution.'],
  ['TARS Chatbots', 'hellotars.com', 'Paid', 'From $99/mo', 4.5, 3800, 'Lead Gen Forms', 'Conversational landing pages that boost PPC conversion rates through interactive chats.'],
  ['WotNot', 'wotnot.io', 'Freemium', 'Free / $49/mo', 4.5, 2900, 'Lead Automation', 'No-code chatbot builder designed for inbound lead qualification and appointment booking.'],
  ['LivePerson Bella', 'liveperson.com', 'Paid', 'Enterprise', 4.4, 6200, 'Conversational Commerce', 'Pioneering conversational cloud connecting millions of consumers with retail brands.'],
  ['Inbenta', 'inbenta.com', 'Paid', 'Enterprise', 4.4, 2600, 'Symbolic AI', 'Natural language processing platform with symbolic AI for high-accuracy financial answers.'],
  ['Smartloop', 'smartloop.ai', 'Freemium', 'Free / $10/mo', 4.3, 1900, 'Marketing Bots', 'Lead generation and nurture chatbots for messaging apps and marketing funnels.'],
  ['Gupshup', 'gupshup.io', 'Paid', 'Enterprise Pay As You Go', 4.5, 5400, 'Conversational Messaging', 'Global conversational messaging platform powering billions of enterprise interactions monthly.'],
  ['Haptik', 'haptik.ai', 'Paid', 'Enterprise', 4.6, 4700, 'Commerce Assistant', 'Conversational commerce assistant driving sales and customer engagement in retail.'],
  ['Verloop', 'verloop.io', 'Paid', 'Enterprise', 4.5, 3100, 'Deflection AI', 'Customer support automation platform automating customer queries across apps and web.'],
  ['Boost.ai', 'boost.ai', 'Paid', 'Enterprise', 4.7, 3400, 'Banking AI', 'No-code conversational AI built for high-security financial services and public sector teams.'],
  ['Amelia', 'amelia.ai', 'Paid', 'Enterprise', 4.5, 2800, 'Digital Employee', 'Pioneering cognitive AI agent platform designed to automate complex enterprise workflows.'],
  ['Kore.ai', 'kore.ai', 'Paid', 'Enterprise', 4.7, 4300, 'Virtual Assistants', 'Enterprise conversational AI platform recognized for robust multi-agent orchestration.'],
  ['Kasisto KAI', 'kasisto.com', 'Paid', 'Enterprise', 4.6, 2100, 'Fintech Chat', 'Specialized conversational AI platform engineered exclusively for premier banking institutions.'],
  ['Nuance Mix', 'nuance.com', 'Paid', 'Enterprise', 4.5, 5900, 'Healthcare Voice', 'Enterprise conversational AI tooling by Microsoft powering healthcare and contact centers.'],
  ['Creative Virtual', 'creativevirtual.com', 'Paid', 'Enterprise', 4.3, 1600, 'V-Person', 'Knowledge management and omnichannel virtual customer assistant solutions.'],
  ['IntelePeer', 'intelepeer.ai', 'Paid', 'Enterprise', 4.4, 1800, 'Voice AI', 'AI-powered communication automation platform automating voice call workflows.'],
  ['Omilia', 'omilia.com', 'Paid', 'Enterprise', 4.6, 2200, 'Conversational IVR', 'State-of-the-art conversational voice IVR system replacing traditional phone menus.'],
  ['Rulai', 'rul.ai', 'Paid', 'Enterprise', 4.4, 1400, 'Omnichannel Support', 'Next-generation conversational computing platform for self-service customer support.'],
  ['Enterprise Bot', 'enterprisebot.ai', 'Paid', 'Enterprise', 4.5, 1700, 'Process Automation', 'Conversational AI automation for financial institutions, insurers, and utilities.'],
  ['Cognicor', 'cognicor.com', 'Paid', 'Enterprise', 4.4, 1200, 'Wealth Management', 'Conversational AI purpose-built for financial advisors and wealth advisory firms.'],
  ['Forethought', 'forethought.ai', 'Paid', 'Enterprise', 4.7, 3900, 'Support Automation', 'Generative AI platform routing, discovering, and solving customer inquiries in real time.'],
  ['Siena AI', 'siena.cx', 'Paid', 'From $299/mo', 4.8, 3100, 'Empathy CX', 'Autonomous customer service AI built for e-commerce brands with deep empathy and humor.'],
  ['Maven AGI', 'mavenagi.com', 'Paid', 'Enterprise', 4.7, 2100, 'Action Agent', 'Generative AI platform designed to not only answer questions but take complex back-end actions.'],
  ['Decagon', 'decagon.ai', 'Paid', 'Enterprise', 4.8, 2600, 'High-End CX', 'AI customer support agents trusted by hyper-growth tech companies for human-grade chat.'],
  ['Crescendo AI', 'crescendo.ai', 'Paid', 'Enterprise', 4.5, 1400, 'Call Center Agent', 'Full-stack AI contact center platform combining conversational voice and chat agents.'],
  ['Sierra AI', 'sierra.ai', 'Paid', 'Enterprise', 4.9, 1900, 'Bret Taylor Agent', 'Autonomous enterprise agent platform founded by Bret Taylor for branded consumer chat.'],
  ['DevRev Turing', 'devrev.ai', 'Freemium', 'Free / $9.99/user/mo', 4.8, 4800, 'Dev-to-Support', 'Connects developers and customer support teams with unified conversational ticketing AI.'],
  ['SupportGenie', 'supportgenie.io', 'Paid', 'From $49/mo', 4.4, 1100, 'E-Commerce Agent', 'Fast Shopify customer support chatbot answering tracking and return questions instantly.'],
  ['Helpwise AI', 'helpwise.io', 'Freemium', 'Free trial / $15/mo', 4.5, 2300, 'Shared Inbox', 'Collaborative inbox software with built-in AI reply drafting and email summarization.'],
  ['Gorgias AI', 'gorgias.com', 'Paid', 'From $50/mo', 4.7, 8900, 'Shopify Favorite', 'The premier e-commerce customer service platform with autonomous order inquiry resolutions.'],
  ['Zowie', 'zowie.ai', 'Paid', 'Enterprise', 4.6, 2700, 'E-Commerce Bot', 'Automates up to 80% of repetitive customer questions to drive revenue and lower costs.'],
  ['Chatbase', 'chatbase.co', 'Freemium', 'Free / $19/mo', 4.8, 14100, 'Custom Data Bot', 'Build an AI chatbot trained on your website, PDFs, and Notion docs in under 3 minutes.'],
  ['SiteGPT', 'sitegpt.ai', 'Freemium', 'Free trial / $19/mo', 4.8, 8700, 'Website Chatbot', 'Personalized AI chatbot trained on your entire website content to answer visitor queries.'],
  ['Wonderchat', 'wonderchat.io', 'Freemium', 'Free / $39.99/mo', 4.7, 4300, 'Fast Knowledge Bot', 'Instantly turns your website knowledge base into a custom AI chatbot in seconds.'],
  ['Dante AI', 'dante-ai.com', 'Freemium', 'Free / $20/mo', 4.7, 5100, 'Zero-Code RAG', 'Create customized GPT-4 chatbots trained on your proprietary data without writing code.'],
  ['FastBots', 'fastbots.ai', 'Freemium', 'Free / $19/mo', 4.6, 3200, 'Multi-Format Bot', 'Train chatbots using PDFs, URLs, audio files, and YouTube videos for website customer chat.'],
  ['IngestAI', 'ingestai.io', 'Freemium', 'Free / $39/mo', 4.5, 2800, 'Enterprise Knowledge', 'Turn enterprise documents into interactive chatbots for Slack, MS Teams, and Discord.'],
  ['CustomGPT.ai', 'customgpt.ai', 'Paid', 'From $49/mo', 4.8, 6400, 'Anti-Hallucination', 'Business-grade chatbots with zero hallucinations backed by strict source document verification.'],
  ['Yuma AI', 'yuma.ai', 'Paid', 'From $47/mo', 4.6, 2100, 'Help Desk Copilot', 'Generates high-accuracy draft responses for Gorgias, Zendesk, and Freshdesk tickets.'],
  ['Fin AI Copilot', 'intercom.com', 'Paid', 'Included in Intercom', 4.8, 7900, 'Agent Assistant', 'Side-by-side conversational copilot assisting human agents in responding to inquiries faster.'],
  ['Knode.ai', 'knode.ai', 'Freemium', 'Free / $29/mo', 4.5, 1200, 'Company Brain', 'Semantic enterprise search and conversational Q&A for internal team documentation.'],
  ['MyShell', 'myshell.ai', 'Freemium', 'Free / Token Based', 4.6, 8900, 'Creator Ecosystem', 'Decentralized AI platform for creating, sharing, and monetizing personalized AI personas.'],
  ['Poly.ai', 'poly.ai', 'Paid', 'Enterprise', 4.7, 3600, 'Voice Assistant', 'Super-human voice assistants handling customer phone calls with natural conversational tone.'],
  ['Scribe Chat', 'scribehow.com', 'Freemium', 'Free / $23/mo Pro', 4.8, 12300, 'Process Bot', 'Conversational AI that generates step-by-step visual SOPs and software guides automatically.'],
  ['TextFX', 'textfx.withgoogle.com', 'Free', '100% Free', 4.6, 7500, 'Creative Writing', 'Google AI experiments designed to expand the creative writing process of lyricists and authors.']
];

additionalChatbots.forEach((item, index) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} is an established conversational intelligence solution designed to address demanding modern workflows. Built with advanced transformer architectures, it delivers rapid response latency, high factual fidelity, and seamless operational reliability. Teams leverage its capabilities to streamline interactions, summarize documentation, and maintain continuous productivity.`,
    tags: ['Conversational AI', 'AI Assistant', 'Productivity', 'Automation', 'Language Model'],
    pros: ['Clean, highly responsive interface with rapid generation speeds', 'Strong natural language comprehension and context retention', 'Reliable operational uptime and continuous architectural updates'],
    cons: ['Advanced features and integrations require paid tier licenses', 'Occasional context window limitations on prolonged sessions'],
    bestFor: 'Users, developers, and enterprise teams seeking reliable conversational AI and customer engagement.'
  });
});
