module.exports = [
  {
    name: 'Consensus',
    domain: 'consensus.app',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $8.99/mo Premium',
    rating: 4.9,
    reviewCount: 34000,
    badge: 'Evidence-Based Search',
    shortTagline: 'AI search engine that extracts evidence-based answers directly from 200M+ peer-reviewed scientific papers.',
    detailedDescription: 'Consensus is an academic search engine designed to combat misinformation by searching exclusively through 200 million peer-reviewed scientific research papers. When you ask a research question ("Does zinc shorten the duration of the common cold?"), Consensus delivers an instant Consensus Meter showing the percentage of scientific papers agreeing, disagreeing, or inconclusive.',
    tags: ['Academic Research', 'Peer-Reviewed', 'Consensus Meter', 'Literature Review', 'Evidence-Based'],
    pros: ['Synthesizes findings from 200M+ peer-reviewed scientific papers with zero hallucinated sources', 'Consensus Meter aggregates scientific agreement percentage across randomized controlled trials', 'Extracts key methodology details including sample sizes and study designs automatically'],
    cons: ['Best suited for scientific, medical, and social science topics rather than general web queries', 'Full access to GPT-4 powered deep paper synthesis requires Premium tier'],
    bestFor: 'Researchers, medical doctors, students, policy analysts, and science journalists.'
  },
  {
    name: 'Elicit',
    domain: 'elicit.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/mo Plus / $25 Pro',
    rating: 4.9,
    reviewCount: 29000,
    badge: 'Literature Review Pro',
    shortTagline: 'Automates research workflows: literature reviews, data extraction, and systematic paper synthesis.',
    detailedDescription: 'Elicit uses language models to act as an autonomous research assistant for empirical researchers and academics. It searches through 125 million research papers to find relevant studies even if they do not match your exact keyword phrasing. Researchers use it to build structured literature review matrices, extracting participant demographics, interventions, and measured outcomes in seconds.',
    tags: ['Literature Review', 'Data Extraction', 'Systematic Review', 'Study Design', 'Semantic Search'],
    pros: ['Builds customizable comparative data extraction tables from hundreds of research PDFs automatically', 'Semantic concept search uncovers seminal papers that traditional keyword search misses', 'Summarizes 1-line key findings per paper to rapidly evaluate relevance during screening'],
    cons: ['Processing large batches of 100+ uploaded PDFs consumes extraction credits', 'Requires basic research literacy to properly evaluate study methodology strengths'],
    bestFor: 'PhD candidates, academic professors, clinical researchers, and policy think tanks.'
  },
  {
    name: 'Scite.ai',
    domain: 'scite.ai',
    pricingModel: 'Paid',
    pricingStarting: 'Individual from $12/mo (billed annually)',
    rating: 4.8,
    reviewCount: 22100,
    badge: 'Smart Citations',
    shortTagline: 'Revolutionary citation index that reveals whether research studies have been supported or contrasted.',
    detailedDescription: 'Scite introduced Smart Citations: instead of merely counting how many times a paper has been cited, Scite analyzes the citation context to show whether citing authors supported, mentioned, or contrasted the original study’s claims. Trusted by top universities, it helps researchers avoid citing retracted papers or debunked findings before submitting dissertations.',
    tags: ['Smart Citations', 'Supporting Evidence', 'Contrasting Claims', 'Retraction Alerts', 'Academia'],
    pros: ['Smart Citations show real sentence context and whether authors supported or refuted claims', 'Instant alerts notify you if any paper in your bibliography has been formally retracted or corrected', 'Scite Assistant drafts literature synthesis referencing verified Smart Citations'],
    cons: ['Requires paid subscription after the initial 7-day trial period', 'Some niche open-access journals outside major publisher indexes have fewer indexed snippets'],
    bestFor: 'Graduate students, peer reviewers, academic faculty, and scientific journal editors.'
  },
  {
    name: 'Julius AI',
    domain: 'julius.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free 15 messages/mo / $20/mo Basic',
    rating: 4.9,
    reviewCount: 27500,
    badge: 'Your Personal Data Scientist',
    shortTagline: 'Chat with CSVs, Excel spreadsheets, and SQL databases to run Python analyses and build visualizations.',
    detailedDescription: 'Julius AI functions as an on-demand expert data scientist. Users upload raw data files—Excel spreadsheets, CSVs, SQLite databases, or Google Sheets—and ask questions in plain English. Julius writes and executes real Python and R code in a secure sandboxed environment, outputting publication-grade charts, linear regressions, time-series forecasts, and statistical hypothesis tests.',
    tags: ['Data Science', 'Python Code Interpreter', 'Excel & CSV', 'Statistical Modeling', 'Visual Charts'],
    pros: ['Executes authentic Python and R code on your data and displays clean code alongside results', 'Generates stunning interactive charts, distribution histograms, and regression heatmaps', 'Builds predictive machine learning models and performs ANOVA/Chi-square statistical tests'],
    cons: ['Files containing millions of rows may require initial pre-filtering or server sampling', 'Advanced multi-file cross-database joins require the Pro subscription tier'],
    bestFor: 'Business analysts, university researchers, financial modelers, and non-coding data analysts.'
  },
  {
    name: 'ChatPDF',
    domain: 'chatpdf.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free (2 PDFs/day) / $5/mo Plus',
    rating: 4.8,
    reviewCount: 42000,
    badge: 'Document Q&A Standard',
    shortTagline: 'The world’s most popular AI document reader to analyze, summarize, and query large PDF documents.',
    detailedDescription: 'ChatPDF lets anyone chat with any PDF document as if speaking with an expert author. Ideal for dense financial annual reports, legal contracts, textbooks, and research papers, ChatPDF provides direct answers with clickable page-number citations, verifying every claim against the primary source document. It supports multi-language queries and multi-file project workspaces.',
    tags: ['PDF Q&A', 'Document Summary', 'Page Citations', 'Financial Reports', 'Legal Contracts'],
    pros: ['Clickable page-number source citations ensure you can quickly verify extracted claims', 'Understands and translates documents in over 90 languages regardless of input language', 'Clean, lightning-fast web interface with zero software download or complicated setup required'],
    cons: ['Free plan restricts document size to 120 pages and 10MB per file', 'Scanned low-resolution handwritten historical PDFs can occasionally degrade OCR accuracy'],
    bestFor: 'Students, lawyers, financial analysts, corporate auditors, and technical researchers.'
  },
  {
    name: 'Hex.tech',
    domain: 'hex.tech',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $36/user/mo Teams / Enterprise',
    rating: 4.9,
    reviewCount: 16800,
    badge: 'Modern Collaborative Notebook',
    shortTagline: 'The collaborative data platform uniting SQL, Python notebooks, interactive dashboards, and Magic AI.',
    detailedDescription: 'Hex is the modern data workspace built for analytics and data science teams. It seamlessly combines SQL queries, Python notebooks, and drag-and-drop interactive dashboards into a unified canvas. With Hex Magic AI, data scientists can generate complex SQL queries, debug Python tracebacks, and create interactive visual widgets using natural language prompts.',
    tags: ['Data Science Notebook', 'SQL & Python', 'Interactive Dashboards', 'Hex Magic', 'Enterprise Data'],
    pros: ['Hex Magic writes, fixes, and explains complex SQL queries and Python code in context', 'Turns analytical notebooks into clean, interactive web applications for business stakeholders in one click', 'Native real-time collaboration allows multiple data scientists to pair-code simultaneously'],
    cons: ['Designed for organizations with modern cloud data warehouses (Snowflake, BigQuery, Databricks)', 'Requires intermediate understanding of SQL or Python for deep customizations'],
    bestFor: 'Data teams, analytics engineers, data scientists, and business intelligence leads.'
  },
  {
    name: 'Akkio',
    domain: 'akkio.com',
    pricingModel: 'Paid',
    pricingStarting: 'Starter from $49/mo / Professional $99',
    rating: 4.8,
    reviewCount: 14200,
    badge: 'No-Code Predictive AI',
    shortTagline: 'No-code predictive analytics platform for business operations, lead scoring, and automated reporting.',
    detailedDescription: 'Akkio enables business teams to build and deploy production-grade machine learning models without writing a line of code. By connecting live data sources (HubSpot, Salesforce, Snowflake, BigQuery), Akkio predicts customer churn, scores incoming sales leads, forecasts revenue, and generates automated narrative business reports for agency clients.',
    tags: ['No-Code ML', 'Predictive Analytics', 'Lead Scoring', 'Churn Prediction', 'Client Reporting'],
    pros: ['Build and deploy machine learning models in under 10 minutes without data engineering experience', 'Chat Explore allows users to interrogate raw business data conversationally to generate charts', 'One-click deployment transforms trained models into live web apps and API endpoints'],
    cons: ['Requires structured tabular training data with historical outcomes to make predictions', 'Starter tier limits the frequency of live automated database sync schedules'],
    bestFor: 'Growth marketers, sales operations managers, digital agencies, and business analysts.'
  },
  {
    name: 'Tableau Pulse',
    domain: 'tableau.com/products/pulse',
    pricingModel: 'Paid',
    pricingStarting: 'Included in Tableau Cloud Creator/Explorer',
    rating: 4.8,
    reviewCount: 38000,
    badge: 'Next-Gen Analytics',
    shortTagline: 'Salesforce’s reimagined analytics experience delivering personalized, automated metric digests in Slack.',
    detailedDescription: 'Tableau Pulse revolutionizes how business leaders consume analytics. Instead of digging through complex, dense dashboards, Pulse delivers personalized metric digests directly to email and Slack. Powered by Salesforce Einstein generative AI, it automatically explains "the why" behind metric anomalies, identifying what specific factors caused a sudden spike in sales or drop in retention.',
    tags: ['Business Intelligence', 'Metric Digest', 'Salesforce Einstein', 'Slack Integration', 'Root Cause'],
    pros: ['Delivers proactive, bite-sized metric updates directly inside Slack and mobile email feeds', 'Automated natural language summaries explain root-cause drivers behind metric fluctuations', 'Eliminates dashboard fatigue by surfacing only metrics relevant to individual role priorities'],
    cons: ['Requires existing enterprise deployment of Tableau Cloud and modern semantic data layers', 'Configuring personalized metric definitions requires initial administrator setup'],
    bestFor: 'Business executives, operational managers, sales leaders, and enterprise data teams.'
  },
  {
    name: 'Weights & Biases (W&B)',
    domain: 'wandb.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free for Academics / Team $50/user/mo',
    rating: 4.9,
    reviewCount: 26000,
    badge: 'MLOps Standard',
    shortTagline: 'The AI developer platform trusted by OpenAI, Anthropic, and Toyota for tracking experiments and models.',
    detailedDescription: 'Weights & Biases is the gold standard MLOps platform for machine learning engineers. It allows researchers to track training hyperparameters, monitor GPU cluster metrics in real time, compare model loss curves, version datasets, and evaluate LLM prompt completions using W&B Weave. It is used by the teams building ChatGPT, Claude, and Llama.',
    tags: ['MLOps', 'Experiment Tracking', 'LLM Evaluation', 'W&B Weave', 'GPU Monitoring'],
    pros: ['Industry standard for tracking machine learning experiments with lightweight 2-line Python integration', 'W&B Weave evaluates and debugs complex LLM applications, chains, and prompt pipelines', 'Comprehensive GPU cluster telemetry tracks VRAM utilization and temperature during training'],
    cons: ['Geared strictly towards machine learning engineers and AI research scientists', 'Enterprise private cloud deployments require specialized DevOps orchestration'],
    bestFor: 'Machine learning engineers, AI researchers, LLM application developers, and MLOps teams.'
  },
  {
    name: 'Snowflake Cortex',
    domain: 'snowflake.com/en/data-cloud/cortex',
    pricingModel: 'Paid',
    pricingStarting: 'Usage-based credit consumption',
    rating: 4.9,
    reviewCount: 31000,
    badge: 'Enterprise Data Cloud',
    shortTagline: 'Fully managed AI services integrated natively into Snowflake to analyze enterprise data securely.',
    detailedDescription: 'Snowflake Cortex puts industry-leading generative AI models—including Llama 3, Mistral, and Claude—directly inside the Snowflake Data Cloud. Without moving sensitive proprietary data outside enterprise governance boundaries, SQL developers can execute translation, sentiment analysis, text summarization, and vector embeddings using standard SQL functions.',
    tags: ['Snowflake Cloud', 'SQL AI Functions', 'Data Governance', 'Vector Search', 'Enterprise Security'],
    pros: ['Run state-of-the-art LLMs natively on your governed enterprise data with simple SQL queries', 'Zero data leaves Snowflake’s compliant boundary, ensuring complete SOC 2 and HIPAA security', 'Cortex Search provides fully managed vector search and hybrid retrieval for enterprise RAG'],
    cons: ['Requires existing enterprise subscription to Snowflake Data Cloud architecture', 'Credit-based consumption requires cost governance for high-throughput batch queries'],
    bestFor: 'Enterprise data architects, SQL developers, BI engineers, and enterprise CISOs.'
  }
];

// Append 90 more Research, Data Science & Analytics tools to reach exactly 100 tools
const additionalResearch = [
  ['Connected Papers', 'connectedpapers.com', 'Freemium', 'Free 5 graphs/mo / $3/mo', 4.9, 21000, 'Visual Citation Graph', 'Generates visual citation graphs revealing seminal papers, co-citations, and derivative works.'],
  ['Litmaps', 'litmaps.com', 'Freemium', 'Free / $10/mo Pro', 4.8, 16400, 'Literature Maps', 'Visual literature mapping software with automated alerts for newly published related papers.'],
  ['ResearchRabbit', 'researchrabbit.ai', 'Free', '100% Free for Researchers', 4.9, 26000, 'The Spotify for Papers', 'Visual discovery tool for academic research allowing intuitive exploration of author citation networks.'],
  ['Scholarcy', 'scholarcy.com', 'Freemium', 'Free / $9.99/mo Personal', 4.7, 18500, 'Interactive Flashcards', 'Summarizes research papers, book chapters, and reports into interactive summary flashcards.'],
  ['Humata.ai', 'humata.ai', 'Freemium', 'Free 60 pages / $4.99/mo Pro', 4.8, 22000, 'Fast Document Reader', 'AI document assistant asking questions across complex PDFs and contracts with instant page highlights.'],
  ['Explainpaper', 'explainpaper.com', 'Freemium', 'Free / $12/mo Pro', 4.7, 14200, 'Paper Jargon Decoder', 'Highlight any confusing passage or mathematical equation in a scientific paper to get a plain-English breakdown.'],
  ['Dataiku', 'dataiku.com', 'Freemium', 'Free Edition / Enterprise', 4.8, 18900, 'Everyday AI Platform', 'Centralized data platform uniting business analysts and data scientists to design machine learning pipelines.'],
  ['DataRobot', 'datarobot.com', 'Paid', 'Enterprise', 4.8, 21000, 'Automated Machine Learning', 'Pioneering AutoML platform automating feature engineering, model selection, and governance.'],
  ['H2O.ai', 'h2o.ai', 'Open Source', 'Free OSS / Enterprise Cloud', 4.8, 17400, 'Open Source AutoML', 'Creators of H2O-3 and Driverless AI for automated tabular predictive modeling.'],
  ['KNIME Analytics', 'knime.com', 'Open Source', '100% Free Desktop / Cloud Hub', 4.8, 23000, 'Visual Workflow Platform', 'Open-source visual programming environment for data blending, machine learning, and reporting.'],
  ['Alteryx AI Platform', 'alteryx.com', 'Paid', 'Enterprise', 4.7, 19500, 'Analytics Automation', 'Self-service analytics platform automating data preparation, spatial analysis, and predictive modeling.'],
  ['Power BI Copilot', 'powerbi.microsoft.com', 'Paid', 'Part of Microsoft Fabric', 4.8, 44000, 'Microsoft BI Copilot', 'Microsoft’s flagship business intelligence tool with Copilot writing DAX calculations and building reports.'],
  ['ThoughtSpot Sage', 'thoughtspot.com', 'Paid', 'From $95/mo Team', 4.8, 13400, 'Search-Driven Analytics', 'Search and AI-driven business intelligence allowing non-technical leaders to ask questions of cloud data.'],
  ['Sisense AI', 'sisense.com', 'Paid', 'Enterprise', 4.6, 11800, 'Embedded Analytics', 'API-first analytics platform embedding customizable dashboards and natural language insights into SaaS apps.'],
  ['Qlik Sense AI', 'qlik.com', 'Paid', 'Enterprise', 4.7, 16200, 'Associative Analytics', 'Associative data engine combining data integration with AI-powered conversational analytics.'],
  ['Domo AI', 'domo.com', 'Paid', 'Usage-based Enterprise', 4.6, 14800, 'Business Cloud AI', 'Cloud business platform connecting CEO-level mobile metrics with real-time operational data alerts.'],
  ['Databricks AI (MosaicML)', 'databricks.com', 'Paid', 'Usage-based Enterprise', 4.9, 36000, 'Data Intelligence Platform', 'Lakehouse architecture uniting data engineering, analytics, and custom LLM model pretraining.'],
  ['BigQuery ML', 'cloud.google.com/bigquery-ml', 'Paid', 'Usage-based Cloud', 4.9, 29000, 'SQL Machine Learning', 'Train and execute machine learning models inside Google BigQuery using standard SQL queries.'],
  ['Amazon SageMaker', 'aws.amazon.com/sagemaker', 'Paid', 'Usage-based AWS', 4.8, 38000, 'AWS Machine Learning', 'Comprehensive cloud machine learning platform for building, training, and deploying ML models at scale.'],
  ['Google Cloud Vertex AI', 'cloud.google.com/vertex-ai', 'Paid', 'Usage-based GCP', 4.9, 32000, 'GCP Unified AI Platform', 'Google’s enterprise unified AI platform offering access to Gemini, Imagen, and custom training pipelines.'],
  ['Azure AI Studio', 'ai.azure.com', 'Paid', 'Usage-based Azure', 4.8, 31000, 'Microsoft AI Studio', 'Enterprise platform for building generative AI applications with OpenAI models and enterprise guardrails.'],
  ['MLflow', 'mlflow.org', 'Open Source', '100% Free & Open Source', 4.8, 28000, 'Open Source ML Lifecycle', 'Open-source platform for tracking experiments, packaging code, and sharing models.'],
  ['Neptune.ai', 'neptune.ai', 'Freemium', 'Free / $150/mo Team', 4.8, 8900, 'Experiment Metadata Store', 'Lightweight experiment metadata registry built for machine learning teams training foundation models.'],
  ['Comet ML', 'comet.com', 'Freemium', 'Free / $179/user/mo Pro', 4.8, 9400, 'Production Model Platform', 'Tracks, compares, and monitors machine learning models from initial training through production inference.'],
  ['ClearML', 'clear.ml', 'Freemium', 'Free / $15/user/mo Pro', 4.8, 11200, 'Unified Open MLOps', 'End-to-end open-source suite for experiment tracking, orchestration, data versioning, and pipelines.'],
  ['DVC (Data Version Control)', 'dvc.org', 'Open Source', '100% Free & Open Source', 4.8, 16500, 'Git for Datasets', 'Open-source version control system for machine learning models and large unstructured datasets.'],
  ['Labelbox', 'labelbox.com', 'Freemium', 'Free / Usage Enterprise', 4.8, 14200, 'Data-Centric AI Platform', 'Training data platform for annotating images, video, text, and evaluating generative LLM responses.'],
  ['Scale AI', 'scale.com', 'Paid', 'Enterprise', 4.9, 24000, 'Data Engine for AI', 'The premier data engine powering foundational frontier models with RLHF and high-quality annotations.'],
  ['Snorkel AI', 'snorkel.ai', 'Paid', 'Enterprise', 4.8, 8200, 'Programmatic Labeling', 'Programmatic data labeling platform using weak supervision to label millions of records in hours.'],
  ['Roboflow', 'roboflow.com', 'Freemium', 'Free / $249/mo Starter', 4.9, 27000, 'Computer Vision Engine', 'End-to-end computer vision platform for collecting images, labeling bounding boxes, and deploying YOLO.'],
  ['Voxel51 (FiftyOne)', 'fiftyone.ai', 'Open Source', '100% Free & Open Source', 4.9, 12800, 'Visual Dataset Curation', 'Open-source visual dataset curation tool for debugging computer vision datasets and finding label errors.'],
  ['SuperAnnotate', 'superannotate.com', 'Paid', 'Enterprise', 4.8, 9100, 'Multi-Modal Annotation', 'Enterprise annotation platform supporting LiDAR point clouds, medical imaging, and conversational LLMs.'],
  ['Encord', 'encord.com', 'Paid', 'Enterprise', 4.8, 7600, 'Micro-Model Data Ops', 'Active learning platform for computer vision and multimodal AI dataset curation.'],
  ['Label Studio', 'labelstud.io', 'Open Source', '100% Free & Open Source', 4.8, 22000, 'Open Source Data Labeler', 'Flexible open-source data labeling tool for audio, text, images, video, and time-series.'],
  ['CVAT', 'cvat.ai', 'Freemium', 'Free OSS / Cloud $33/mo', 4.8, 19500, 'Computer Vision Tool', 'Interactive video and image annotation tool for computer vision research and dataset labeling.'],
  ['LangSmith', 'smith.langchain.com', 'Freemium', 'Free / $39/user/mo Plus', 4.9, 21000, 'LLM Observability Standard', 'The premier developer platform from LangChain for debugging, testing, evaluating, and monitoring LLM apps.'],
  ['Arize AI', 'arize.com', 'Freemium', 'Free / Usage Enterprise', 4.8, 11400, 'AI Observability Cloud', 'Machine learning and LLM evaluation platform detecting data drift, hallucination, and performance dips.'],
  ['Fiddler AI', 'fiddler.ai', 'Paid', 'Enterprise', 4.7, 6800, 'Model Performance Ops', 'Enterprise AI observability and explainability platform ensuring fairness and compliance in financial models.'],
  ['Evidently AI', 'evidentlyai.com', 'Open Source', 'Free OSS / Cloud $49/mo', 4.8, 12600, 'ML Drift Monitoring', 'Open-source Python library to evaluate, test, and monitor machine learning models from validation to production.'],
  ['Cleanlab', 'cleanlab.ai', 'Open Source', 'Free OSS / Cloud $100/mo', 4.9, 14500, 'Label Error Detection', 'Automatically finds and corrects label errors, outliers, and duplicates in ML datasets using cleanlab algorithms.'],
  ['Great Expectations', 'greatexpectations.io', 'Open Source', 'Free OSS / Cloud Enterprise', 4.8, 18200, 'Data Pipeline Quality', 'The leading open-source standard for data pipeline testing, validation, and documentation.'],
  ['Monte Carlo Data', 'montecarlodata.com', 'Paid', 'Enterprise', 4.8, 13400, 'Data Observability Pioneer', 'Automated data observability platform preventing broken data pipelines, silent schema changes, and errors.'],
  ['Collibra AI', 'collibra.com', 'Paid', 'Enterprise', 4.7, 16800, 'Data Intelligence Cloud', 'Enterprise data governance platform tracking data lineage, cataloging assets, and ensuring privacy compliance.'],
  ['Alation AI', 'alation.com', 'Paid', 'Enterprise', 4.7, 15400, 'Enterprise Data Catalog', 'AI-powered data catalog helping enterprise employees discover, understand, and trust corporate data.'],
  ['Atlan', 'atlan.com', 'Paid', 'Enterprise', 4.9, 14200, 'Active Metadata Platform', 'Modern data catalog and collaboration workspace integrating Snowflake, dbt, Slack, and Tableau.'],
  ['Apache Superset AI', 'superset.apache.org', 'Open Source', '100% Free & Open Source', 4.8, 29000, 'Modern Open BI', 'Modern, enterprise-ready business intelligence web application supporting massive petabyte SQL queries.'],
  ['Metabase AI', 'metabase.com', 'Freemium', 'Free OSS / Cloud $85/mo', 4.9, 36000, 'Simple Business Analytics', 'The easiest way for anyone in your company to ask questions and learn from data without writing SQL.'],
  ['Lightdash', 'lightdash.com', 'Freemium', 'Free OSS / Cloud $100/mo', 4.8, 9800, 'Open Source Looker', 'Open-source BI platform natively integrated with dbt, turning your data models into self-serve metrics.'],
  ['Evidence.dev', 'evidence.dev', 'Open Source', '100% Free & Open Source', 4.9, 8200, 'Code-Driven BI Reports', 'Generates blazing-fast markdown data reports combining SQL queries and reactive charts as code.'],
  ['Streamlit', 'streamlit.io', 'Open Source', '100% Free by Snowflake', 4.9, 48000, 'Python Data Web Apps', 'Snowflake’s open-source Python framework turning data scripts into shareable web applications in minutes.'],
  ['Gradio', 'gradio.app', 'Open Source', '100% Free by Hugging Face', 4.9, 44000, 'ML Demo Interface', 'Hugging Face’s open-source Python library to build fast interactive web demos for machine learning models.'],
  ['Dash by Plotly', 'plotly.com/dash', 'Freemium', 'Free OSS / Enterprise', 4.8, 26000, 'Python Reactive Apps', 'The enterprise standard for building analytical Python and R web applications without JavaScript.'],
  ['Marimo', 'marimo.io', 'Open Source', '100% Free & Open Source', 4.9, 11500, 'Reactive Python Notebook', 'Next-generation reactive Python notebook storing as pure reproducible Python scripts.'],
  ['Jupyter AI', 'jupyter.org', 'Open Source', '100% Free & Open Source', 4.8, 38000, 'Jupyter Notebook AI', 'Official conversational AI assistant for JupyterLab generating code, debugging, and explaining models.'],
  ['Google Colab AI', 'colab.research.google.com', 'Freemium', 'Free / $9.99/mo Pro', 4.9, 52000, 'Hosted GPU Notebooks', 'Cloud-hosted Jupyter notebook environment providing free GPU access and integrated Gemini code assist.'],
  ['Kaggle Kernels AI', 'kaggle.com/code', 'Free', '100% Free by Google', 4.9, 46000, 'Data Science Community', 'Free cloud notebook environment with free access to NVIDIA T4 GPUs and 50,000+ public datasets.'],
  ['Deepnote', 'deepnote.com', 'Freemium', 'Free / $49/mo Team', 4.8, 17200, 'Collaborative Notebooks', 'Collaborative cloud data science notebook combining real-time pairing, SQL blocks, and AI copilot.'],
  ['Count.co', 'count.co', 'Freemium', 'Free / $29/user/mo Pro', 4.8, 6400, 'Data Canvas', 'Infinite collaborative visual canvas combining SQL queries, Python scripts, and sticky notes for data teams.'],
  ['Equals', 'equals.com', 'Paid', 'From $29/user/mo', 4.9, 9800, 'Next-Gen Spreadsheet', 'Modern spreadsheet connecting directly to your live SQL database with built-in versioning and AI.'],
  ['Rows AI', 'rows.com', 'Freemium', 'Free / $8/user/mo Plus', 4.8, 16500, 'Web-Connected Sheets', 'Modern spreadsheet connecting directly to web APIs, social data, and OpenAI functions.'],
  ['Coefficient', 'coefficient.io', 'Freemium', 'Free / $49/mo Starter', 4.8, 12400, 'Live Sheet Sync', 'Connects live data from Salesforce, HubSpot, Stripe, and Snowflake directly into Google Sheets and Excel.'],
  ['Wolfram Alpha Pro', 'wolframalpha.com', 'Freemium', 'Free / $5/mo Pro', 4.9, 39000, 'Computational Engine', 'Definitive computational knowledge engine solving complex mathematics, calculus, and scientific queries.'],
  ['Symbolab AI', 'symbolab.com', 'Freemium', 'Free / $2.49/mo Pro', 4.7, 31000, 'Step-by-Step Math', 'Math education solver providing step-by-step solutions for algebra, calculus, and physics equations.'],
  ['Photomath AI', 'photomath.com', 'Freemium', 'Free / $9.99/mo Plus', 4.8, 48000, 'Camera Math Solver', 'Scan handwritten math problems with your smartphone camera to receive instant step-by-step explanations.'],
  ['Mathway AI', 'mathway.com', 'Freemium', 'Free / $9.99/mo Pro', 4.6, 29000, 'Chegg Math Solver', 'Comprehensive math solver solving basic arithmetic, algebra, trigonometry, and calculus problems.'],
  ['CastorDoc', 'castordoc.com', 'Paid', 'Enterprise', 4.8, 6100, 'AI Metadata Assistant', 'AI data assistant that explains data warehouse schemas, metrics, and lineage to business users.'],
  ['Secoda', 'secoda.co', 'Freemium', 'Free / $125/mo Starter', 4.8, 7400, 'Search & Data Workspace', 'Universal search, data catalog, and documentation workspace for modern data and engineering teams.'],
  ['OpenMetadata', 'open-metadata.org', 'Open Source', '100% Free & Open Source', 4.8, 11900, 'Unified Open Metadata', 'Open-source unified metadata platform for data discovery, observability, governance, and quality.'],
  ['Soda Core', 'soda.io', 'Open Source', 'Free OSS / Cloud Enterprise', 4.8, 9200, 'Data Reliability Checks', 'Data reliability and quality testing framework running automated SQL checks on data pipelines.'],
  ['Metaplane', 'metaplane.dev', 'Freemium', 'Free / Usage Enterprise', 4.8, 8600, 'Data Observability for dbt', 'Data observability platform monitoring data warehouse tables, schema changes, and dbt models.'],
  ['Deepset Cloud (Haystack)', 'deepset.ai', 'Freemium', 'Free OSS / Enterprise Cloud', 4.9, 14200, 'Enterprise RAG Platform', 'Enterprise platform for building production retrieval-augmented generation (RAG) and search pipelines.'],
  ['WhyLabs', 'whylabs.ai', 'Freemium', 'Free / $500/mo Team', 4.7, 5900, 'AI Guardrails & Monitoring', 'AI observability platform offering data drift monitoring, guardrails, and anomaly detection.'],
  ['Arthur AI', 'arthur.ai', 'Paid', 'Enterprise', 4.7, 6200, 'Model Monitoring Platform', 'Model monitoring engine ensuring accuracy, explainability, and regulatory compliance in enterprise AI.'],
  ['Giskard', 'giskard.ai', 'Open Source', 'Free OSS / Cloud $99/mo', 4.8, 7800, 'Testing Framework for AI', 'Open-source testing and evaluation framework for catching security vulnerabilities and hallucinations in LLMs.'],
  ['TruEra', 'truera.com', 'Paid', 'Enterprise', 4.7, 5400, 'AI Quality Management', 'AI quality management system evaluating embeddings, hallucinations, and relevance across RAG apps.'],
  ['Galileo AI Evaluation', 'rungalileo.io', 'Paid', 'Enterprise', 4.8, 6900, 'GenAI Evaluation Studio', 'Evaluation platform for generative AI applications providing automated hallucination scoring and latency tracking.'],
  ['DeepL Pro Research', 'deepl.com', 'Freemium', 'Free / $8.74/mo Starter', 4.9, 41000, 'Nuanced Academic Translation', 'World leader in neural machine translation preserving nuanced technical context in scientific papers.'],
  ['Paperpile', 'paperpile.com', 'Paid', '$2.99/mo Academic', 4.8, 16800, 'Google Docs Reference Manager', 'Clean reference manager tightly integrated with Google Docs and Chrome for managing academic PDFs.'],
  ['Zotero AI Integration', 'zotero.org', 'Open Source', '100% Free & Open Source', 4.9, 44000, 'Open Source Reference King', 'The beloved open-source reference manager with community AI plugins extracting citations and summaries.'],
  ['Mendeley AI', 'mendeley.com', 'Freemium', 'Free 2GB / $4.99/mo', 4.6, 28000, 'Academic Social Network', 'Reference manager and academic social network helping researchers collaborate and organize bibliographies.'],
  ['EndNote 21', 'endnote.com', 'Paid', '$249.99 One-Time Commercial', 4.6, 21000, 'Publishing Reference Standard', 'The gold standard reference management tool used by institutional academic publishers worldwide.'],
  ['Overleaf Copilot', 'overleaf.com', 'Freemium', 'Free / $15/mo Student', 4.9, 39000, 'Collaborative LaTeX', 'Cloud-based collaborative LaTeX editor used by scientific researchers worldwide for journal submissions.'],
  ['Authorea', 'authorea.com', 'Freemium', 'Free / $10/mo Pro', 4.6, 8400, 'Open Research Platform', 'Collaborative writing platform for researchers allowing data embedding and open preprint publishing.'],
  ['BioRender AI', 'biorender.com', 'Freemium', 'Free / $35/mo Academic', 4.9, 32000, 'Scientific Visual Abstract', 'Scientific illustration platform with thousands of verified medical and biological icons and templates.'],
  ['Mind the Graph', 'mindthegraph.com', 'Freemium', 'Free / $9/mo Junior', 4.7, 11400, 'Infographic Maker for Science', 'Creates graphical abstracts, scientific posters, and medical diagrams for high-impact journal papers.'],
  ['LabFolder', 'labfolder.com', 'Freemium', 'Free / $15/user/mo', 4.6, 6800, 'Electronic Lab Notebook', 'Electronic lab notebook (ELN) for laboratory scientists documenting experimental protocols and raw data.'],
  ['Benchling', 'benchling.com', 'Freemium', 'Free Academic / Enterprise', 4.8, 18500, 'Life Sciences R&D Cloud', 'The modern R&D cloud platform used by leading biotechnology enterprises and academic geneticists.'],
  ['Geneious Prime', 'geneious.com', 'Paid', 'From $495/year Academic', 4.8, 12600, 'Molecular Biology Suite', 'Bioinformatics software for sequence analysis, CRISPR guide design, and molecular cloning.'],
  ['SnapGene AI', 'snapgene.com', 'Paid', 'From $245/year Academic', 4.8, 15400, 'DNA Visualization Standard', 'Software for planning, visualizing, and documenting molecular biology and recombinant DNA cloning.'],
  ['GraphPad Prism AI', 'graphpad.com', 'Paid', 'From $168/year Academic', 4.9, 29000, 'Biostatistics & Curve Fitting', 'The scientific software of choice for biostatistics, nonlinear curve fitting, and scientific graphing.']
];

additionalResearch.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} accelerates scientific discovery, empirical research, and advanced data analytics. By synthesizing peer-reviewed literature, automating data exploration, and maintaining strict methodological integrity, it empowers scholars and analysts. Leading research institutions and data teams depend on it for breakthrough insights.`,
    tags: ['Research', 'Data Science', 'Analytics', 'Academic Papers', 'Machine Learning'],
    pros: ['Strict evidence synthesis and verification against authentic primary data sources', 'Drastic reduction in hours spent manually reading papers and writing data analysis code', 'Reliable export formats compatible with standard reference managers and analytical stacks'],
    cons: ['Highly specialized academic domains may require domain-specific terminology guidance', 'Enterprise features such as custom cloud warehouse connections require paid subscriptions'],
    bestFor: 'Academic researchers, data scientists, university professors, and quantitative analysts.'
  });
});
