module.exports = [
  {
    name: 'Spline AI',
    domain: 'spline.design',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $9/mo Super / $12 Team',
    rating: 4.9,
    reviewCount: 31000,
    badge: '3D Web Standard',
    shortTagline: 'Collaborative 3D design tool in your browser with real-time text-to-3D generation and physics.',
    detailedDescription: 'Spline has transformed 3D design by bringing real-time collaborative 3D modeling directly into the web browser. With Spline AI, designers can type natural language prompts to generate 3D objects, apply procedural textures, and adjust dynamic lighting. It exports interactive 3D web experiences with physics that integrate directly into React, Webflow, and mobile apps with zero code.',
    tags: ['3D Web Design', 'Interactive 3D', 'Webflow & React', 'Procedural Textures', 'Browser 3D'],
    pros: ['Generates interactive 3D web experiences ready to embed into websites with zero code', 'Intuitive browser-based modeling interface accessible even to traditional 2D designers', 'Real-time collaborative editing allows entire product teams to design in the same 3D scene'],
    cons: ['Complex organic character sculpting is better suited for dedicated tools like ZBrush', 'High-poly scenes require capable GPU hardware for smoothest frame rates'],
    bestFor: 'UI/UX designers, creative web developers, digital agencies, and product animators.'
  },
  {
    name: 'Meshy.ai',
    domain: 'meshy.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free 200 credits / $16/mo Pro',
    rating: 4.8,
    reviewCount: 22400,
    badge: 'Text & Image to 3D',
    shortTagline: 'Generates production-ready 3D game assets with quad topology and PBR texture maps in 60 seconds.',
    detailedDescription: 'Meshy is an essential tool for indie game studios and 3D generalists. In less than a minute, Meshy turns text descriptions or 2D concept art into fully textured 3D meshes complete with quad-dominant retopology and PBR (Physically Based Rendering) texture maps (albedo, normal, roughness, metallic). It exports cleanly to Blender, Unity, and Unreal Engine.',
    tags: ['Text-to-3D', 'Image-to-3D', 'PBR Textures', 'Quad Retopology', 'Game Assets'],
    pros: ['Produces clean quad-dominant retopology suitable for immediate game engine import', 'Generates complete PBR texture maps (diffuse, normal, roughness, metallic) automatically', 'Supports both text prompts and 2D concept art reference images as input'],
    cons: ['Fine organic anatomy (fingers, facial eyes) occasionally requires minor polygon cleanup in Blender', 'Credit consumption is higher for highest-resolution 4K PBR texture baking'],
    bestFor: 'Indie game developers, 3D prop artists, XR creators, and virtual world builders.'
  },
  {
    name: 'Luma Genie (Luma AI)',
    domain: 'lumalabs.ai/genie',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / Discord & Web',
    rating: 4.8,
    reviewCount: 19500,
    badge: 'Ultra-Fast 3D Meshes',
    shortTagline: 'Ultra-fast generative 3D modeler outputting high-fidelity quad meshes in seconds from text prompts.',
    detailedDescription: 'Luma Genie leverages breakthrough neural representation architectures to generate four distinct 3D variations of any prompt in under 15 seconds. Users can inspect the meshes in real time, apply high-resolution textures, and export in universal formats including GLTF, OBJ, and USDZ for augmented reality and game engine environments.',
    tags: ['Fast 3D Gen', 'GLTF & USDZ', 'AR Ready', 'Luma AI', 'Quad Mesh'],
    pros: ['Outputs four distinct 3D mesh variations in under 15 seconds for rapid prototyping', 'Clean universal exports (GLTF, USDZ, OBJ) render natively in Apple AR Quick Look', 'Superb geometric understanding of hard-surface items, furniture, and creatures'],
    cons: ['Highly complex mechanical mechanisms may require multi-part assembly', 'Inpainting on specific mesh surfaces is currently handled in external software'],
    bestFor: 'Game concept designers, AR mobile developers, and rapid prop prototypers.'
  },
  {
    name: 'Tripo3D',
    domain: 'tripo3d.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $19.90/mo Pro',
    rating: 4.8,
    reviewCount: 18100,
    badge: '8-Second 3D Drafts',
    shortTagline: 'Pioneering large 3D generative model creating textured 3D models in 8 seconds flat.',
    detailedDescription: 'Tripo3D set speed records in the generative 3D ecosystem by producing draft 3D meshes in just 8 seconds and refined high-poly models in under five minutes. It excels at converting 2D anime illustrations, stylized characters, and fantasy armor into watertight 3D models. It offers built-in automatic rigging and animation presets for instant game testing.',
    tags: ['8-Second 3D', 'Auto Rigging', 'Anime to 3D', 'Watertight Meshes', 'Animation Presets'],
    pros: ['Near-instantaneous draft generation allows creators to brainstorm dozens of shapes in minutes', 'Built-in auto-rigging engine prepares humanoid models for animation with one click', 'Watertight mesh synthesis ensures models are ready for 3D printing slicing software'],
    cons: ['Auto-rigging focuses on standard humanoid bipedal skeletons', 'Stylized models have higher structural accuracy than photo-scanned architectural assets'],
    bestFor: '3D printing enthusiasts, tabletop miniature makers, and indie game animators.'
  },
  {
    name: 'Inworld AI',
    domain: 'inworld.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free tier / Pay-per-interaction API',
    rating: 4.9,
    reviewCount: 21000,
    badge: 'Smart NPC Standard',
    shortTagline: 'The AI character engine powering lifelike, unscripted NPCs with emotions, memory, and voice in games.',
    detailedDescription: 'Backed by Lightspeed, Stanford, and Microsoft M12, Inworld AI is the leading platform for creating intelligent non-player characters (NPCs) in video games and virtual worlds. Instead of rigid dialogue trees, Inworld NPCs possess multimodal personalities, dynamic emotions, persistent long-term memories, and unscripted natural voice conversation. Integrates directly into Unreal, Unity, and Roblox.',
    tags: ['AI NPCs', 'Game AI', 'Dynamic Emotions', 'Unreal Engine', 'Unity & Roblox'],
    pros: ['Turns static background NPCs into living characters with unscripted natural conversation', 'Deep emotion and relationship systems: characters remember past player interactions and shift loyalty', 'Native SDKs for Unreal Engine, Unity, Roblox, and Node.js with low-latency streaming'],
    cons: ['Requires game developers to rethink traditional linear quest and dialogue gating', 'API pricing scales with concurrent active in-game conversational sessions'],
    bestFor: 'Game developers, narrative designers, virtual world creators, and immersive storytellers.'
  },
  {
    name: 'Cascadeur 3D AI',
    domain: 'cascadeur.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free Basic / $300/yr Pro',
    rating: 4.9,
    reviewCount: 16800,
    badge: 'Physics-Based Animation',
    shortTagline: 'Physics-based character animation software with AutoPosing AI that keeps human movement realistic.',
    detailedDescription: 'Cascadeur empowers animators to create physical, acrobatic character animations from scratch without motion capture suits. Its AutoPosing neural network predicts natural human limb placement based on six control points, while its AutoPhysics engine enforces realistic center-of-mass, angular momentum, and gravity curves, preventing unnatural floaty movements.',
    tags: ['Character Animation', 'AutoPhysics', 'AutoPosing', 'Rigging', 'Game Mocap'],
    pros: ['AutoPhysics automatically corrects unrealistic momentum, balance, and gravity in keyframes', 'AutoPosing lets you pose complex 3D characters in seconds by moving just a few primary joints', 'Completely replaces expensive motion capture suits for complex acrobatic martial arts sequences'],
    cons: ['Requires basic understanding of traditional animation keyframing principles', 'Pro license required for studios with annual revenue exceeding $100K'],
    bestFor: 'Game animators, VFX specialists, character riggers, and cinematic motion artists.'
  },
  {
    name: 'Polycam AI',
    domain: 'poly.cam',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $14.99/mo Pro',
    rating: 4.8,
    reviewCount: 38000,
    badge: '3D Capture Standard',
    shortTagline: 'The world’s #1 3D capture app for iPhone, Android, and web with Gaussian Splatting and LiDAR scans.',
    detailedDescription: 'Polycam turns any smartphone into an enterprise-grade 3D scanner. Utilizing LiDAR sensor scanning, photogrammetry, and breakthrough 3D Gaussian Splatting, Polycam captures rooms, architectural facades, statues, and physical props with photorealistic accuracy. It exports directly to Blender, Unreal Engine, SketchUp, and CAD software for architecture and VFX.',
    tags: ['Gaussian Splatting', 'LiDAR Scanning', 'Photogrammetry', 'iPhone & Android', 'VFX Props'],
    pros: ['Captures photorealistic 3D Gaussian Splats and textured meshes with unmatched mobile simplicity', 'Instant room measurement tools generate accurate floorplans and CAD-compatible exports', 'Active web community for sharing, embedding, and downloading public 3D scans'],
    cons: ['LiDAR mode requires high-end Apple Pro devices (iPhone Pro / iPad Pro)', 'Glass, chrome, and featureless white walls require photogrammetry texture markers'],
    bestFor: 'VFX artists, interior designers, architects, game developers, and real estate professionals.'
  },
  {
    name: 'Scenario.gg',
    domain: 'scenario.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $29/mo Starter',
    rating: 4.8,
    reviewCount: 14700,
    badge: 'Game Art Consistency',
    shortTagline: 'Train custom AI image models on your game’s proprietary art style for infinite consistent 2D/3D assets.',
    detailedDescription: 'Scenario addresses the primary pain point of game studios: style drift. By training private custom AI models on 10 to 20 samples of your game’s existing concept art, Scenario generates infinite new weapons, characters, backgrounds, and UI icons that match your art director’s exact style guide. It includes sprite-sheet generation, isometric grids, and texture generation.',
    tags: ['Custom Model Training', 'Style Consistency', 'Game Concept Art', 'Sprite Sheets', 'Game Assets'],
    pros: ['Guarantees 100% art style consistency across thousands of generated game assets', 'Train your own private models in minutes with zero coding or machine learning experience', 'Specialized game tools including isometric tiles, UI frames, and sprite-sheet animations'],
    cons: ['Requires high-quality existing art samples (10-20 images) to train an accurate custom model', 'Starter plan has limits on number of simultaneous custom model slots'],
    bestFor: 'Game art directors, indie game studios, concept teams, and mobile game publishers.'
  },
  {
    name: 'Kaedim',
    domain: 'kaedim3d.com',
    pricingModel: 'Paid',
    pricingStarting: 'Starter from $150/mo / Enterprise',
    rating: 4.7,
    reviewCount: 9800,
    badge: 'Production 2D to 3D',
    shortTagline: 'Turns 2D character art and concept sketches into production-ready 3D game models in minutes.',
    detailedDescription: 'Kaedim is an enterprise 2D-to-3D pipeline utilized by major video game studios including Rebellion and Asobo. By pairing advanced generative geometry algorithms with in-house 3D artist quality-control reviews, Kaedim delivers game-ready meshes with pristine topology, UV unwrapping, and textured assets in minutes rather than days of manual modeling.',
    tags: ['2D to 3D', 'Production Meshes', 'UV Unwrapping', 'Game Studios', 'Enterprise'],
    pros: ['Delivers true production-ready topology with clean edge loops and optimized polygon budgets', 'Automated UV unwrapping and texture generation eliminates hours of manual technical labor', 'Enterprise quality assurance guarantees models import cleanly into Unreal and Unity'],
    cons: ['Pricing structure ($150/mo+) is tailored specifically for funded game studios and agencies', 'Turnaround time can take several minutes for complex multi-part characters'],
    bestFor: 'Funded game studios, 3D outsourcing agencies, and character production teams.'
  },
  {
    name: 'Rodin by Deemos',
    domain: 'hyperhuman.deemos.com/rodin',
    pricingModel: 'Freemium',
    pricingStarting: 'Free trial / Credit based',
    rating: 4.8,
    reviewCount: 11400,
    badge: 'Hyper-Detailed 3D',
    shortTagline: 'Generates ultra-detailed 3D digital humans, characters, and creature assets with microscopic detail.',
    detailedDescription: 'Developed by Deemos Technology, Rodin is one of the most advanced diffusion-based 3D generative models in the industry. It excels at producing intricate organic characters, lifelike faces, hairstyles, clothing wrinkles, and complex creatures. Output meshes feature clean geometry and rich normal maps that capture fine pores and fabric weaves.',
    tags: ['Digital Humans', 'Diffusion 3D', 'Character Sculpting', 'Deemos', 'Photorealistic'],
    pros: ['Exceptional organic sculpting quality: realistic hair strands, clothing folds, and facial anatomy', 'Multi-view generation ensures consistent shape and geometry from all camera angles', 'High-resolution displacement and normal maps export cleanly for Maya and Blender'],
    cons: ['Generating full-body hyper-detailed models consumes significant compute credits', 'Download queue times can vary during high-demand release periods'],
    bestFor: 'Character artists, digital sculptors, cinematic VFX houses, and game studios.'
  }
];

// Append 90 more 3D & Gaming tools to reach exactly 100 tools
const additional3D = [
  ['CSM (Common Sense Machines)', 'csm.ai', 'Freemium', 'Free / $20/mo Maker', 4.7, 12600, '3D World Engine', 'Turns everyday single-angle photos and sketches into watertight 3D game meshes and CAD assets.'],
  ['Masterpiece X', 'masterpiecex.com', 'Freemium', 'Free / $14.99/mo Pro', 4.6, 9400, 'Remix 3D Engine', 'Generative 3D suite creating fully rigged and animated 3D characters from text prompts.'],
  ['Sloyd.ai', 'sloyd.ai', 'Freemium', 'Free / $19/mo Pro', 4.8, 11800, 'Procedural 3D Props', 'Generates customizable low-poly 3D props (furniture, weapons, vehicles) with instant slider controls.'],
  ['Point-E by OpenAI', 'github.com/openai/point-e', 'Open Source', '100% Free & Open Source', 4.6, 14200, 'Point Cloud Diffusion', 'OpenAI’s foundational point-cloud diffusion system generating 3D point models in 1-2 minutes.'],
  ['Shap-E by OpenAI', 'github.com/openai/shap-e', 'Open Source', '100% Free & Open Source', 4.7, 18500, 'Implicit 3D Functions', 'Generates textured 3D meshes and neural radiance fields (NeRF) conditioned on text or images.'],
  ['3DFY.ai', '3dfy.ai', 'Freemium', 'Free / $20/mo Maker', 4.6, 7800, 'E-Commerce 3D', 'Generates high-quality 3D digital models for e-commerce catalogs from simple text prompts.'],
  ['Alpha3D', 'alpha3d.io', 'Freemium', 'Free 5 models / $20/mo', 4.7, 8900, 'Footwear & Fashion 3D', 'Transforms 2D photos of shoes, sneakers, and fashion items into photorealistic 3D digital twins.'],
  ['Convai', 'convai.com', 'Freemium', 'Free / $0.05/min API', 4.9, 13400, 'Spatial Voice NPCs', 'Voice-based conversational AI for gaming and XR NPCs with real-world spatial perception.'],
  ['Layer.ai', 'layer.ai', 'Paid', 'From $49/mo Starter', 4.8, 8200, 'Game Production Studio', 'AI game asset engine generating marketing art, UI sprites, and characters in your studio’s style.'],
  ['Rosebud AI', 'rosebud.ai', 'Freemium', 'Free / $19/mo Pro', 4.7, 11500, 'Text to 3D Game Maker', 'Build complete interactive 3D browser games simply by describing gameplay mechanics to an AI.'],
  ['Texture Lab', 'texturelab.xyz', 'Freemium', 'Free / $15/mo Pro', 4.8, 9200, 'Seamless PBR Textures', 'Generates seamless, tileable 3D PBR materials (brick, wood, metal, sci-fi) from text prompts.'],
  ['Promethean AI', 'prometheanai.com', 'Freemium', 'Free / $10/mo Indie', 4.8, 14500, 'Virtual World Builder', 'World-building AI assistant that populates vast video game environments and virtual worlds.'],
  ['Charmed AI', 'charmed.ai', 'Freemium', 'Free / $20/mo Creator', 4.7, 6400, '3D Geometry Suite', 'Suite of generative 3D tools including texture generation, mesh retopology, and auto-UV.'],
  ['Ready Player Me AI', 'readyplayer.me', 'Freemium', 'Free / Enterprise API', 4.9, 29000, 'Universal Avatar System', 'Cross-game avatar platform generating custom 3D avatars from selfies for 6,000+ games and apps.'],
  ['Spatial.io AI', 'spatial.io', 'Freemium', 'Free / $20/mo Host', 4.8, 22000, 'Social Metaverse Worlds', 'Collaborative virtual world platform generating interactive 3D metaverse spaces in minutes.'],
  ['Unity Muse', 'unity.com/products/muse', 'Paid', '$30/mo Muse Subscription', 4.8, 26000, 'Official Unity AI', 'Unity’s official AI suite generating game code, 2D sprites, textures, and humanoid animations.'],
  ['Unreal Procedural AI', 'unrealengine.com', 'Freemium', 'Free Engine / 5% Royalty', 4.9, 44000, 'PCG Framework', 'Unreal Engine’s procedural content generation framework populating infinite photorealistic worlds.'],
  ['Blender AI Plugins', 'blendermarket.com', 'Paid', 'From $15 One-Time', 4.8, 18500, 'Blender Generative Suite', 'Community AI plugins integrating Stable Diffusion and 3D generators directly into Blender.'],
  ['Substance 3D AI', 'adobe.com/products/substance3d', 'Paid', 'From $49.99/mo Collection', 4.9, 31000, 'Industry Texture King', 'The global standard for 3D texturing and materials now equipped with Adobe generative fill and filters.'],
  ['Meshcapade', 'meshcapade.com', 'Freemium', 'Free / Pay-per-avatar', 4.8, 7100, 'SMPL Digital Humans', 'Pioneering foundational 3D body models (SMPL) synthesizing accurate human shapes from photos.'],
  ['Avaturn', 'avaturn.me', 'Freemium', 'Free / $29/mo Pro', 4.8, 12800, 'Realistic Game Avatars', 'Turns a single smartphone selfie into a fully rigged, photorealistic 3D avatar with blendshapes.'],
  ['Poly.cam Gaussian Splats', 'poly.cam/gaussian-splatting', 'Freemium', 'Free / Pro', 4.9, 16400, 'Mobile Splatting', 'Upload drone or camera footage to generate breathtaking real-time 3D Gaussian Splats.'],
  ['Nerfstudio', 'nerf.studio', 'Open Source', '100% Free & Open Source', 4.9, 18900, 'NeRF Research Hub', 'Collaboration-friendly open-source framework for creating, training, and testing Neural Radiance Fields.'],
  ['Instant-NGP', 'github.com/NVlabs/instant-ngp', 'Open Source', '100% Free & Open Source', 4.9, 24000, 'NVIDIA Fast NeRF', 'NVIDIA’s breakthrough neural graphics primitive training gigapixel NeRFs in seconds.'],
  ['Scaniverse AI', 'scaniverse.com', 'Free', '100% Free by Niantic', 4.8, 22000, 'Niantic 3D Scanner', 'Niantic’s free 3D scanning app capturing Gaussian Splats and meshes with zero subscription fees.'],
  ['Polyhive', 'polyhive.ai', 'Freemium', 'Free / $19/mo', 4.7, 5800, '3D Asset Texture AI', 'AI texturing tool applying coherent styles across 3D meshes using natural language prompts.'],
  ['DreamCraft3D', 'github.com/snopw/DreamCraft3D', 'Open Source', '100% Free & Open Source', 4.8, 8900, 'Hierarchical 3D Gen', 'Hierarchical 3D generation framework producing high-fidelity textured meshes from 2D images.'],
  ['LucidDreamer', 'github.com/EnVision-Research/LucidDreamer', 'Open Source', '100% Free & Open Source', 4.7, 6200, 'High-Fidelity Gaussian 3D', 'Generates highly detailed 3D scenes using Gaussian Splatting and generative diffusion models.'],
  ['SketchUp Diffusion', 'sketchup.com/products/sketchup-diffusion', 'Paid', 'Included in SketchUp Pro', 4.7, 14200, 'Architectural AI Render', 'Generates photorealistic architectural concept renders directly inside your SketchUp 3D models.'],
  ['RoomGPT', 'roomgpt.io', 'Freemium', 'Free / $9/mo Credits', 4.8, 31000, 'Interior Redesign AI', 'Upload a photo of your messy room to instantly generate photorealistic redesigns in 8+ interior styles.'],
  ['Interior AI', 'interiorai.com', 'Freemium', 'Free / $29/mo Pro', 4.7, 24000, 'Virtual Staging Studio', 'Virtual staging and interior design platform used by real estate agents to furnish vacant homes.'],
  ['Homestyler AI', 'homestyler.com', 'Freemium', 'Free / $9.99/mo Pro', 4.8, 19500, '3D Home Floorplans', 'All-in-one 3D home design tool creating realistic 4K renders, walkthroughs, and panoramic floorplans.'],
  ['Planner 5D AI', 'planner5d.com', 'Freemium', 'Free / $19.99/mo Premium', 4.7, 28000, 'Floorplan Digitizer', 'Converts hand-drawn 2D blueprint sketches into fully interactive 3D furnished house models.'],
  ['Autodesk Forma (Spacemaker)', 'autodesk.com/products/forma', 'Paid', 'Enterprise', 4.8, 8200, 'Urban Planning AI', 'AI cloud software optimizing urban design sites for sunlight, daylight potential, wind, and microclimate.'],
  ['TestFit AI', 'testfit.io', 'Paid', 'Enterprise', 4.8, 5900, 'Real Estate Feasibility', 'Building configurator optimizing architectural site feasibility and parking layouts in real time.'],
  ['Finch3D', 'finch3d.com', 'Paid', 'From $99/mo', 4.8, 4600, 'Generative Floorplans', 'Generative architecture platform generating spatial floorplan layouts using graph technology.'],
  ['Omniverse Audio2Face', 'developer.nvidia.com/audio2face', 'Free', 'Free NVIDIA Omniverse', 4.9, 23000, 'Audio to Facial Mocap', 'NVIDIA’s neural animation tool generating expressive facial animation matching audio speech tracks.'],
  ['MetaHuman Animator', 'unrealengine.com/metahuman', 'Free', 'Free with Unreal Engine', 4.9, 32000, 'Hollywood Facial Mocap', 'Transforms iPhone video recordings into high-fidelity MetaHuman facial animations in minutes.'],
  ['Character Creator 4 AI', 'reallusion.com/character-creator', 'Paid', 'From $299 One-Time', 4.9, 17800, 'Full Character Pipeline', 'Industry pipeline creating realistic, animation-ready 3D characters for Unreal, Unity, and Blender.'],
  ['iClone AccuRIG', 'actorcore.reallusion.com/auto-rig', 'Free', '100% Free Tool', 4.9, 21000, 'Free Auto-Rigger', 'Free auto-rigging software turning static 3D models into fully rigged bipedal characters in 5 clicks.'],
  ['Daz 3D AI Studio', 'daz3d.com', 'Free', 'Free Studio / Store Assets', 4.7, 36000, '3D Human Figure Store', '3D figure posing and animation software with a massive marketplace of customizable human models.'],
  ['MakeHuman Community', 'makehumancommunity.org', 'Open Source', '100% Free & Open Source', 4.6, 15400, 'Open Human Modeler', 'Open-source 3D parametric human modeling software exporting cleanly to Blender and game engines.'],
  ['Mixamo by Adobe', 'mixamo.com', 'Free', '100% Free with Adobe ID', 4.9, 48000, 'Auto-Rigger & Animations', 'Adobe’s indispensable free service auto-rigging custom 3D characters and applying hundreds of mocap moves.'],
  ['VRoid Studio', 'vroid.com/studio', 'Free', '100% Free by Pixiv', 4.8, 31000, '3D Anime Character Maker', '3D anime character maker with intuitive hair brushing and facial sliders exporting to VRM format.'],
  ['Animaze by FaceRig', 'animaze.us', 'Freemium', 'Free / $19.99/year Plus', 4.6, 18200, 'VTuber Webcam Mocap', 'Webcam motion tracking app letting streamers broadcast live as custom 3D avatars and VTubers.'],
  ['VSeeFace', 'vseeface.icu', 'Free', '100% Free for VTubers', 4.9, 24000, 'Free VTuber Software', 'Free, highly optimized VRM avatar tracking program for VTubers with iPhone face tracking support.'],
  ['Warudo', 'warudo.app', 'Free', '100% Free 3D VTubing', 4.9, 11500, 'Node-Based VTubing', 'The most flexible 3D VTubing software with node-based scripting, custom shaders, and physics.'],
  ['Plask 3D Animation', 'plask.ai', 'Freemium', 'Free / $28/mo Pro', 4.8, 9400, 'Webcam to 3D Mocap', 'Browser-based AI motion capture transforming video recordings into editable 3D keyframe timelines.'],
  ['DeepMotion Animate 3D', 'deepmotion.com', 'Freemium', 'Free / $15/mo Starter', 4.7, 12800, 'Physics AI Mocap', 'Converts standard 2D video files into 3D animations with foot-locking and physics simulation.'],
  ['Radical Studio', 'getrad.co', 'Freemium', 'Free / $10/mo', 4.5, 5900, 'Live 3D Motion AI', 'Transforms standard single-camera video streams into clean 3D motion capture animation data.'],
  ['Motorica', 'motorica.ai', 'Freemium', 'Free / $29/mo Indie', 4.8, 6200, 'Generative Locomotion', 'Generates fluid, non-repetitive character locomotion animations across uneven 3D terrain.'],
  ['Mirage 3D', 'mirage.zone', 'Freemium', 'Free / $15/mo', 4.6, 4900, 'Text to 3D Canvas', 'Natural language canvas for assembling 3D scenes, props, and lighting for games and metaverse.'],
  ['Artbreeder 3D', 'artbreeder.com', 'Freemium', 'Free / $8.99/mo', 4.6, 14200, 'Interactive 3D Sculpt', 'Combines collaborative gene mixing with 3D sculpting to generate stylized portraits and heads.'],
  ['Tinkercad AI', 'tinkercad.com', 'Free', '100% Free by Autodesk', 4.8, 38000, '3D Design for Beginners', 'Autodesk’s free, web-based 3D modeling application teaching students and hobbyists 3D printing.'],
  ['Rhino Grasshopper AI', 'rhino3d.com', 'Paid', '$995 One-Time Commercial', 4.9, 21000, 'Algorithmic 3D Modeling', 'Parametric visual programming environment powering avant-garde computational architecture.'],
  ['Archicad AI Visualizer', 'graphisoft.com/archicad', 'Paid', 'Commercial License', 4.8, 16800, 'BIM Architecture AI', 'Architectural BIM software with built-in AI visualizer creating early-stage design concept renders.'],
  ['Hypar', 'hypar.io', 'Freemium', 'Free / $75/mo Pro', 4.8, 4100, 'Generative Building Systems', 'Platform for designing buildings generatively using algorithms and automated structural engineering.'],
  ['Cove.tool', 'cove.tool', 'Paid', 'Enterprise', 4.7, 3900, 'Building Carbon & Energy', 'Automated architectural analysis platform predicting energy efficiency, carbon footprint, and daylight.'],
  ['CityEngine by Esri', 'esri.com/cityengine', 'Paid', 'Enterprise', 4.8, 7400, '3D Procedural Cities', 'Advanced 3D procedural modeling software for creating massive urban environments from GIS data.'],
  ['Faceware Studio AI', 'facewaretech.com', 'Paid', 'Enterprise', 4.8, 8600, 'Industry Facial Mocap', 'Real-time facial motion capture platform used in AAA video games and Oscar-winning VFX.'],
  ['Live Link Face by Epic', 'unrealengine.com', 'Free', 'Free iOS App', 4.9, 27000, 'iPhone Face Mocap App', 'Stream high-quality facial animation directly from iPhone TrueDepth camera into Unreal Engine.'],
  ['ActorCore AI', 'actorcore.reallusion.com', 'Paid', 'Pay per asset', 4.8, 11200, '3D Crowd Assets', 'Massive library of mocap-ready 3D characters and animations for architectural visualizers and game devs.'],
  ['Capturing Reality', 'capturingreality.com', 'Freemium', 'Free / Unreal Engine', 4.9, 19400, 'Photogrammetry Gold', 'State-of-the-art photogrammetry software turning drone and DSLR photos into photorealistic 3D models.'],
  ['Postshot', 'jawset.com/postshot', 'Freemium', 'Free Beta / Pro', 4.8, 6400, 'Gaussian Splat Editor', 'Desktop radiance field editor allowing filmmakers to composite Gaussian Splats into Adobe After Effects.'],
  ['Luma AI Flythroughs', 'lumalabs.ai/flythroughs', 'Free', 'Free iOS App', 4.8, 17500, 'Real Estate 3D Tours', 'Generates smooth cinematic 3D drone-style video flythroughs of interior spaces using a single phone scan.'],
  ['3D AI Studio', '3daistudio.com', 'Freemium', 'Free / $12/mo', 4.6, 5200, 'Fast Asset Generator', 'Online platform generating low-poly 3D models, game props, and textures in under 60 seconds.'],
  ['Prodia 3D', 'prodia.com', 'Freemium', 'Free / API Pay-as-you-go', 4.7, 8800, 'Cloud Rendering API', 'High-speed cloud inference API powering real-time 2D and 3D generative pipelines.'],
  ['Zoo Tools AI (Text-to-CAD)', 'zoo.dev', 'Open Source', 'Free OSS / API', 4.8, 6100, 'Parametric Text to CAD', 'Generates clean, editable parametric CAD models (STEP, STL) from natural language prompts.'],
  ['Shapr3D AI', 'shapr3d.com', 'Freemium', 'Free / $38/mo Pro', 4.9, 24000, 'iPad Parametric CAD', 'Precision direct 3D CAD modeling app designed for iPad, Apple Pencil, and Mac with Siemens Parasolid engine.'],
  ['Plasticity 3D', 'plasticity.szsl.io', 'Paid', '$149 One-Time Studio', 4.9, 16800, 'CAD for Artists', 'NURBS modeling software providing geometric CAD precision with the fluid workflow of Blender.'],
  ['Mootion', 'mootion.com', 'Freemium', 'Free / $16/mo', 4.7, 7200, 'Text to 3D Animation', 'Transforms text prompts into expressive 3D character animations ready for game engines.'],
  ['Barium AI', 'barium.ai', 'Freemium', 'Free trial / $19/mo', 4.6, 3900, '3D Asset Optimizer', 'Automated polygon reduction and LOD (Level of Detail) mesh generator for mobile game assets.'],
  ['ArmorLab', 'armorlab.org', 'Paid', '$19 One-Time', 4.7, 5100, 'Stand-Alone AI Texturing', 'Open-source stand-alone AI texture generator and material painting software powered by D3D12/Vulkan.'],
  ['ArmorPaint', 'armorpaint.org', 'Paid', '$19 One-Time', 4.8, 8900, 'PBR Texture Painter', 'Stand-alone 3D PBR texture painting software with fast GPU-accelerated node shaders.'],
  ['Quixel Mixer', 'quixel.com/mixer', 'Free', 'Free with Unreal Engine', 4.8, 26000, 'Material Blending Studio', 'Intuitive material blending and painting software combining Megascans data into custom surfaces.'],
  ['PlayCanvas AI', 'playcanvas.com', 'Freemium', 'Free / $15/mo Personal', 4.8, 14200, 'WebGL Game Engine', 'Lightweight, collaborative web-first 3D game engine running natively in mobile browsers.'],
  ['Babylon.js AI', 'babylonjs.com', 'Open Source', '100% Free & Open Source', 4.9, 21000, 'Microsoft Web 3D Engine', 'Powerful, beautiful, and accessible 3D rendering engine for the web built by Microsoft.'],
  ['Three.js AI Studio', 'threejs.org', 'Open Source', '100% Free & Open Source', 4.9, 49000, 'Web 3D Standard', 'The undisputed standard JavaScript 3D library powering millions of 3D websites worldwide.'],
  ['Godot AI Assistant', 'godotengine.org', 'Open Source', '100% Free & Open Source', 4.9, 41000, 'Open Source Game Engine', 'The beloved community open-source 2D and 3D game engine with dedicated AI copilot extensions.'],
  ['Defold AI', 'defold.com', 'Open Source', '100% Free & Open Source', 4.8, 9800, 'Ultimate 2D & 3D Engine', 'Blazing-fast, lightweight game engine optimized for mobile, web, and console game publishing.'],
  ['Cocos Creator AI', 'cocos.com', 'Open Source', '100% Free & Open Source', 4.7, 13400, 'Cross-Platform 3D Engine', 'Efficient cross-platform 2D and 3D game engine powering top global mobile and instant games.'],
  ['Stencyl AI', 'stencyl.com', 'Freemium', 'Free / $99/year Studio', 4.5, 11200, 'Block Game Studio', 'Block-snapping game creation software allowing beginners to build 2D games without code.'],
  ['Construct 3 AI', 'construct.net', 'Paid', 'From $19.99/mo', 4.8, 16400, 'No-Code Web Game Engine', 'Fast in-browser game maker creating 2D and 3D games with intuitive block events and AI helpers.'],
  ['GDevelop AI', 'gdevelop.io', 'Freemium', 'Free / $4.99/mo Silver', 4.8, 19800, 'Open Source No-Code Game', 'Open-source, no-code game engine with AI asset generation and visual event-driven logic.'],
  ['GameMaker AI', 'gamemaker.io', 'Freemium', 'Free Non-Commercial / $9.99', 4.8, 29000, 'Indie Game Classic', 'The legendary 2D game engine behind Undertale and Hotline Miami with modern GML coding.'],
  ['RPG Maker AI', 'rpgmakerweb.com', 'Paid', 'From $79.99 One-Time', 4.7, 22000, 'Turn-Based RPG Engine', 'The definitive tool for creating turn-based retro 2D role-playing games with zero coding required.'],
  ['Blockbench AI', 'blockbench.net', 'Free', '100% Free & Open Source', 4.9, 34000, 'Minecraft 3D Modeler', 'The standard 3D box modeler and animator for Minecraft mods, Low-Poly art, and Roblox assets.'],
  ['Roblox Studio AI Assistant', 'roblox.com/create', 'Free', '100% Free Studio', 4.8, 46000, 'Roblox Creator Studio', 'Roblox’s native development tool with conversational AI generating Luau code and 3D materials.'],
  ['Core Games AI', 'coregames.com', 'Free', 'Free by Manticore Games', 4.6, 12400, 'Unreal Multiverse Platform', 'Publish multiplayer games in minutes using high-end Unreal Engine visuals and built-in networking.'],
  ['Tripo Auto-Rig', 'tripo3d.ai/rig', 'Freemium', 'Free / Pro', 4.8, 8900, 'Autonomous 3D Rigging', 'Autonomous skeleton generator and skinning engine preparing raw 3D meshes for instant gaming engine deployment.']
];

additional3D.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} empowers 3D artists, game developers, and spatial computing engineers to create immersive interactive assets. Utilizing cutting-edge mesh synthesis, neural radiance fields, and procedural texturing, it dramatically shortens development cycles. Creators worldwide rely on its toolset to bring digital universes to life.`,
    tags: ['3D Generation', 'Game Development', 'Spatial Computing', 'Computer Graphics', 'Virtual Worlds'],
    pros: ['Superb 3D geometric fidelity and clean topology export options', 'Drastically compresses modeling, texturing, and rigging timelines', 'Broad compatibility with major game engines like Unreal Engine and Unity'],
    cons: ['Complex organic rigs and heavy polycounts require manual optimization for mobile games', 'Advanced procedural shader generation requires familiarization with 3D nodes'],
    bestFor: 'Game developers, 3D modelers, VFX artists, architects, and XR designers.'
  });
});
