module.exports = [
  {
    name: 'Notion AI',
    domain: 'notion.so',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/member/mo AI add-on',
    rating: 4.9,
    reviewCount: 46000,
    badge: 'Workspace Standard',
    shortTagline: 'Connected AI workspace that searches across all team docs, summarizes notes, and automates databases.',
    detailedDescription: 'Notion AI transforms Notion from a passive knowledge wiki into an active, intelligent workspace. It can answer complex questions by searching across all your team’s connected documents, meeting notes, project trackers, and integrations (Slack, Google Drive, Jira). It can auto-populate database properties, draft status updates, and extract action items from messy notes in seconds.',
    tags: ['Connected Workspace', 'Q&A Search', 'Database Autofill', 'Meeting Notes', 'Wikis'],
    pros: ['Q&A feature searches your entire company knowledge base across docs, Slack, and Drive', 'Autofills database columns with summaries, tags, and sentiment analysis automatically', 'Seamlessly embedded inside documents without switching contexts or opening separate tabs'],
    cons: ['Requires $10/member/mo add-on fee on top of standard Notion workspace tiers', 'Advanced formula generation occasionally requires manual verification'],
    bestFor: 'Startups, engineering teams, remote companies, and knowledge workers.'
  },
  {
    name: 'Mem.ai',
    domain: 'mem.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $8/mo Mem+',
    rating: 4.8,
    reviewCount: 21500,
    badge: 'Self-Organizing Second Brain',
    shortTagline: 'The self-organizing workspace that connects notes, people, and meetings automatically with zero folders.',
    detailedDescription: 'Mem eliminates the tedious chore of organizing files, tagging notes, and maintaining folder hierarchies. Powered by custom language models, Mem automatically links related thoughts, meeting minutes, and contact notes together. Its Mem Chat assistant acts as an omniscient personal chief of staff, recalling conversations from months ago and synthesizing briefs from scattered notes.',
    tags: ['Self-Organizing', 'Zero Folders', 'Second Brain', 'Personal Knowledge', 'Mem Chat'],
    pros: ['Zero organization required; AI automatically clusters, tags, and connects related notes', 'Mem Chat acts as a personal chief of staff with total recall of your historical notes', 'Fast capture across mobile, web, and email forwarding'],
    cons: ['Lack of rigid traditional folders may feel disorienting to structured filing purists', 'Mobile app has fewer granular formatting options compared to the desktop app'],
    bestFor: 'Founders, researchers, consultants, and busy executives with heavy meeting loads.'
  },
  {
    name: 'Superhuman AI',
    domain: 'superhuman.com',
    pricingModel: 'Paid',
    pricingStarting: 'Starter from $30/user/mo',
    rating: 4.9,
    reviewCount: 32000,
    badge: 'Inbox Zero Speed',
    shortTagline: 'The fastest email experience ever made, now supercharged with instant email drafting and auto-summaries.',
    detailedDescription: 'Superhuman is renowned for helping busy executives and founders reach Inbox Zero twice as fast. Superhuman AI takes speed to another level: it summarizes long email threads in one sentence, writes instant contextual replies matching your personal tone of voice, and turns rough bullet points into perfectly phrased professional messages. It features keyboard-first navigation.',
    tags: ['Email Productivity', 'Inbox Zero', 'Thread Summaries', 'Tone Matching', 'Keyboard First'],
    pros: ['Blazing-fast keyboard shortcuts save 4+ hours every week on email triage', 'AI drafts full contextual email replies that sound exactly like your personal writing style', 'Instant 1-line thread summaries allow instant comprehension of long forwarded chains'],
    cons: ['Premium subscription price ($30/mo) is an investment for solo individuals', 'Works exclusively with Gmail and Microsoft Outlook accounts'],
    bestFor: 'Venture capitalists, founders, CEOs, and professionals drowning in daily email.'
  },
  {
    name: 'Motion (UseMotion)',
    domain: 'usemotion.com',
    pricingModel: 'Paid',
    pricingStarting: 'Individual from $19/mo (billed annually)',
    rating: 4.8,
    reviewCount: 24500,
    badge: 'Autonomous Calendar',
    shortTagline: 'Autonomous AI calendar and task manager that dynamically builds your daily schedule for you.',
    detailedDescription: 'Motion takes the stress out of daily time management by automatically scheduling tasks, meetings, and project deadlines into your calendar. If a sudden emergency meeting pops up, Motion’s rescheduling algorithm instantly rearranges your day so you never miss a priority deadline. It replaces traditional to-do lists, calendars, and project management tools in one smart dashboard.',
    tags: ['Dynamic Scheduling', 'Time Blocking', 'Task Prioritization', 'Meeting Booking', 'AI Calendar'],
    pros: ['Dynamically reschedules incomplete tasks around meetings automatically without manual dragging', 'Eliminates calendar tetris by auto-blocking focus time based on strict project deadlines', 'Includes integrated meeting booking links that guard your preferred focus hours'],
    cons: ['Requires strict commitment to logging all tasks within Motion to maximize benefits', 'No free tier beyond the initial 7-day trial period'],
    bestFor: 'Busy professionals, agency leads, project managers, and people with ADHD.'
  },
  {
    name: 'Reclaim.ai',
    domain: 'reclaim.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free Lite / $8/user/mo Starter',
    rating: 4.8,
    reviewCount: 19800,
    badge: 'Smart Habits & Calendar',
    shortTagline: 'Smart calendar assistant that defends habits, syncs personal calendars, and optimizes team meetings.',
    detailedDescription: 'Acquired by Dropbox, Reclaim.ai is an intelligent calendar management engine designed for modern teams. It automatically finds the best time for your daily habits (exercise, lunch, email catch-up), defends your focus time, and dynamically syncs work and personal Google Calendars to eliminate scheduling conflicts. It also coordinates 1-on-1 and team meetings automatically.',
    tags: ['Calendar Defense', 'Habit Tracking', 'Focus Time', 'Calendar Sync', 'Dropbox'],
    pros: ['Defends daily habits (lunch, gym, meditation) while keeping slots flexible for urgent meetings', 'Flawless 2-way sync between personal and work calendars protects privacy and prevents double-booking', 'Generous free tier with support for up to 3 habits and basic time tracking'],
    cons: ['Currently focuses primarily on Google Calendar ecosystems (Outlook support rolling out)', 'Can feel overly rigid if you prefer spontaneous, unscheduled workdays'],
    bestFor: 'Software engineers, remote knowledge workers, and multi-calendar professionals.'
  },
  {
    name: 'ClickUp Brain',
    domain: 'clickup.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $7/mo Unlimited + $7/mo Brain',
    rating: 4.7,
    reviewCount: 38000,
    badge: 'Connected Knowledge Network',
    shortTagline: 'Conversational AI network connecting tasks, docs, team members, and company knowledge in ClickUp.',
    detailedDescription: 'ClickUp Brain is a deeply integrated AI neural network built directly into the ClickUp productivity platform. It connects tasks, documents, wikis, and team chats. It can answer questions about project statuses ("What is John working on this week?"), write project briefs, generate subtasks, and automatically post daily standup summaries without team members typing a single word.',
    tags: ['Task Management', 'Daily Standup', 'Project Management', 'Wiki Q&A', 'Subtask Generation'],
    pros: ['Answers complex cross-project questions instantly based on live task and doc activity', 'Automates daily standups, project status rollups, and sprint retrospectives', 'Generates detailed subtasks and acceptance criteria directly from high-level task titles'],
    cons: ['ClickUp platform feature density can feel overwhelming for small solo teams', 'Brain add-on fee applies across all workspace members'],
    bestFor: 'Cross-functional agile teams, product managers, and enterprise operations.'
  },
  {
    name: 'Coda AI',
    domain: 'coda.io',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/mo Pro / AI Included',
    rating: 4.8,
    reviewCount: 18200,
    badge: 'Document-App Hybrid',
    shortTagline: 'Transform documents into living interactive workflows and applications with intelligent data columns.',
    detailedDescription: 'Coda blends the simplicity of a text document with the computational power of a relational database. With Coda AI, users can generate dynamic content tables, summarize user interviews, categorize survey feedback, and trigger automated multi-step workflows. Its AI columns compute natural language queries across rows, turning spreadsheets into intelligent data engines.',
    tags: ['Interactive Docs', 'AI Columns', 'Workflow Automation', 'Product Specs', 'Databases'],
    pros: ['AI columns automatically analyze, translate, or summarize entire spreadsheet tables row-by-row', 'Rich ecosystem of Pack integrations connects Coda to Jira, Slack, Figma, and Salesforce', 'Flexible interactive canvas lets teams build custom internal tools and team portals'],
    cons: ['Learning curve for mastering Coda formulas and table relations', 'Document performance can slow down with very large databases (tens of thousands of rows)'],
    bestFor: 'Product managers, operations leads, and creators of custom internal team tools.'
  },
  {
    name: 'Taskade AI',
    domain: 'taskade.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $8/mo Pro / $19/mo Team',
    rating: 4.8,
    reviewCount: 22400,
    badge: 'Autonomous AI Agents',
    shortTagline: 'Real-time collaborative workspace featuring custom autonomous AI agents for task execution.',
    detailedDescription: 'Taskade combines mind maps, task lists, org charts, and Kanban boards with autonomous AI agents. Users can deploy custom AI agent personas—such as a Virtual Marketer, Scrum Master, or SEO Auditor—that actively execute tasks, research topics, and update project boards. Its mind-map generator transforms high-level ideas into structured project roadmaps instantly.',
    tags: ['AI Agents', 'Mind Mapping', 'Kanban & Lists', 'Workflow Automation', 'Collaboration'],
    pros: ['Deploy customizable autonomous AI agents that perform actual research and work on tasks', 'Switch between 5 views instantly: List, Board, Calendar, Action, and Mind Map', 'Generous free tier with real-time video chat and team collaboration included'],
    cons: ['Mobile app navigation takes time to learn due to the multiplicity of views', 'Agent execution tokens require monitoring for heavy automated workflows'],
    bestFor: 'Agile teams, remote agencies, solo founders, and visual project planners.'
  },
  {
    name: 'Granola AI',
    domain: 'granola.so',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/mo Pro',
    rating: 4.9,
    reviewCount: 14200,
    badge: 'Human + AI Notes',
    shortTagline: 'Intelligent notepad for meetings that combines your rough typed notes with AI audio transcription.',
    detailedDescription: 'Granola takes a fundamentally better approach to meeting notes: instead of an intrusive AI recording bot that annoys participants, Granola runs quietly on your Mac, recording audio while you type your own brief bullet points. It then uses AI to seamlessly blend your personal notes with precise details from the audio transcript, outputting clean, personalized meeting summaries.',
    tags: ['No Bot Notes', 'Mac Native', 'Human + AI', 'Meeting Notes', 'Executive Summaries'],
    pros: ['No awkward bot joins your meeting; captures computer audio cleanly on Mac', 'Honors your own typed notes as the primary outline, filling in specifics from the audio', 'Export formatted summaries directly to Slack, Notion, or your email draft in one click'],
    cons: ['Currently macOS only (Windows version in active development)', 'Requires user to jot down at least a few keywords to guide AI note structuring'],
    bestFor: 'Designers, product managers, founders, and anyone who hates meeting bots.'
  },
  {
    name: 'Shortwave',
    domain: 'shortwave.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $7/user/mo Personal / $14 Pro',
    rating: 4.8,
    reviewCount: 16800,
    badge: 'AI Email Assistant',
    shortTagline: 'The next-generation AI email client built by ex-Googlers to search, summarize, and draft emails effortlessly.',
    detailedDescription: 'Built by the team behind Firebase and Google Inbox, Shortwave turns your Gmail inbox into a modern, organized messaging feed. Its AI Assistant can answer questions about your entire email archive ("What did Sarah say about the contract terms?"), draft personalized replies, translate incoming messages, and bundle newsletters into clean daily digests.',
    tags: ['Email Intelligence', 'Google Inbox Heir', 'Email Q&A', 'AI Drafting', 'Gmail Native'],
    pros: ['Ask questions about your entire email history and get precise answers with source citations', 'Clean bundling system organizes promotional emails and newsletters into single lines', 'Built-in AI voice-to-email transcription crafts polished emails from quick voice notes'],
    cons: ['Exclusively integrates with Google Workspace and Gmail accounts', 'Advanced multi-year historical search requires Pro subscription'],
    bestFor: 'Professionals who loved Google Inbox and want an AI-first email experience.'
  }
];

// Append 90 more Productivity, Notes & Knowledge tools to reach exactly 100 tools
const additionalProductivity = [
  ['Reflect Notes', 'reflect.app', 'Paid', '$10/mo (billed annually)', 4.8, 8900, 'Networked Thought', 'Fast, encrypted note-taking app with AI audio transcription and backlinked networked notes.'],
  ['Obsidian AI (Smart Connections)', 'obsidian.md', 'Freemium', 'Free / $4/mo Sync', 4.9, 39000, 'Local Privacy King', 'Local-first Markdown knowledge base with AI plugins connecting notes using vector embeddings.'],
  ['Linear Insights', 'linear.app', 'Freemium', 'Free / $8/user/mo Standard', 4.9, 29000, 'Issue Tracking Gold', 'High-performance software project tracker with AI issue triage, duplicate detection, and summaries.'],
  ['Asana Intelligence', 'asana.com', 'Freemium', 'Free / $10.99/user/mo', 4.7, 34000, 'Enterprise Workflows', 'Work management platform using AI to identify project bottlenecks, summarize updates, and draft tasks.'],
  ['Monday.com AI', 'monday.com', 'Freemium', 'Free / $9/seat/mo Basic', 4.7, 41000, 'Work OS Automation', 'Cloud Work OS with AI formula builders, email categorization, and automated workflow triggers.'],
  ['Clockwise', 'getclockwise.com', 'Freemium', 'Free / $6.75/user/mo', 4.8, 17500, 'Team Focus Time', 'AI scheduling assistant coordinating team meetings to create uninterrupted blocks of Focus Time.'],
  ['Trevor AI', 'trevorai.com', 'Freemium', 'Free / $3.99/mo Pro', 4.6, 7200, 'Time Blocking Assistant', 'Intuitive day-planner connecting Todoist and Google Calendar with smart AI time-blocking suggestions.'],
  ['Akiflow', 'akiflow.com', 'Paid', 'From $19/mo', 4.8, 11400, 'Universal Inbox', 'Consolidates all your tasks from Asana, Trello, Jira, and Slack into a single daily calendar schedule.'],
  ['Morgen Calendar', 'morgen.so', 'Freemium', 'Free / $9/mo Pro', 4.7, 9800, 'Unified Calendar', 'Unified calendar and task manager integrating Outlook, Google, and Apple Calendars with AI scheduling.'],
  ['Routine', 'routine.co', 'Freemium', 'Free / $10/mo Professional', 4.7, 6500, 'Daily Cockpit', 'Fast personal productivity cockpit combining calendar, tasks, notes, and contacts on Mac and iOS.'],
  ['Sunsama', 'sunsama.com', 'Paid', '$16/mo (billed annually)', 4.9, 15400, 'Mindful Productivity', 'The mindful daily planner guiding you to plan realistic workdays, pull tasks from Jira, and shut down on time.'],
  ['Todoist AI', 'todoist.com', 'Freemium', 'Free / $4/mo Pro', 4.8, 51000, 'Task List Standard', 'The world’s favorite to-do list with AI assistant that breaks daunting tasks into actionable subtasks.'],
  ['TickTick AI', 'ticktick.com', 'Freemium', 'Free / $35.99/year', 4.8, 28000, 'Habit & Pomodoro', 'Feature-packed to-do list combining habits, Pomodoro timer, calendar views, and smart task parsing.'],
  ['Any.do AI', 'any.do', 'Freemium', 'Free / $5/mo Premium', 4.6, 23000, 'Daily Review', 'Award-winning task manager featuring smart WhatsApp integration and daily review planning.'],
  ['Spark Mail AI', 'sparkmailapp.com', 'Freemium', 'Free / $4.99/mo Premium', 4.7, 31000, 'Smart Email Client', 'Smart email client featuring AI email drafting, thread summarization, and priority email filtering.'],
  ['SaneBox', 'sanebox.com', 'Paid', 'From $7/mo', 4.7, 14200, 'Email Triage AI', 'Cleans your inbox by automatically filing unimportant newsletters and receipts into a SaneLater folder.'],
  ['Clean Email', 'clean.email', 'Paid', 'From $9.99/mo', 4.6, 12800, 'Bulk Email Cleaner', 'Inbox cleaning tool that unsubscribes from annoying mailing lists and organizes emails with smart views.'],
  ['Mailbutler', 'mailbutler.io', 'Freemium', 'Free / $4.95/mo', 4.6, 8900, 'Email Extension', 'Email companion for Apple Mail, Outlook, and Gmail with AI email drafting and tracking.'],
  ['Boomerang AI', 'boomeranggmail.com', 'Freemium', 'Free / $4.98/mo Personal', 4.6, 18500, 'Email Follow-Up', 'Legendary email scheduling tool with Respondable AI predicting likelihood of receiving email responses.'],
  ['Spike Mail', 'spikenow.com', 'Freemium', 'Free / $6/user/mo', 4.6, 11400, 'Conversational Email', 'Turns email threads into clean chat-style messenger conversations with built-in voice notes and docs.'],
  ['Saner.ai', 'saner.ai', 'Freemium', 'Free / $8/mo Pro', 4.8, 5200, 'ADHD Friendly Notes', 'Minimalist, distraction-free note-taking app designed for ADHD minds with conversational recall.'],
  ['Heptabase', 'heptabase.com', 'Paid', '$9.99/mo (billed annually)', 4.9, 13400, 'Visual Research Canvas', 'Visual knowledge base helping researchers and thinkers visually map complex topics on whiteboards.'],
  ['Capacities', 'capacities.io', 'Freemium', 'Free / $10/mo Pro', 4.8, 11200, 'Object-Based Notes', 'Object-based note-taking app that models knowledge as real-world entities (books, people, projects).'],
  ['Roam Research AI', 'roamresearch.com', 'Paid', '$15/mo or $180/yr', 4.7, 21000, 'Bi-Directional Links', 'The pioneer of networked bi-directional thought and daily research journals.'],
  ['Logseq AI', 'logseq.com', 'Open Source', '100% Free & Open Source', 4.8, 17400, 'Privacy Knowledge Base', 'Local-first, privacy-focused outliner with built-in PDF annotation and flashcards.'],
  ['Scrintal', 'scrintal.com', 'Paid', 'From $5/mo', 4.7, 6800, 'Visual Mind Mapping', 'Combines the flexibility of digital mind-mapping whiteboards with structured note-taking.'],
  ['Affine AI', 'affine.pro', 'Open Source', 'Free OSS / Cloud $8/mo', 4.8, 12600, 'Notion + Miro Alternative', 'Next-gen open-source collaborative knowledge base combining docs, whiteboards, and database tables.'],
  ['Anytype', 'anytype.io', 'Open Source', 'Free OSS / Membership', 4.8, 14200, 'P2P Encrypted Notes', 'Decentralized, local-first, peer-to-peer knowledge base built on cryptographic privacy principles.'],
  ['Walling', 'walling.app', 'Freemium', 'Free / $8/mo Pro', 4.7, 7900, 'Visual Idea Walls', 'Organizes project ideas, moodboards, and team deliverables on clean, modular visual walls.'],
  ['Milanote AI', 'milanote.com', 'Freemium', 'Free / $9.99/mo Pro', 4.8, 22000, 'Creative Moodboards', 'Visual board tool organized for creative directors, film producers, and interior designers.'],
  ['Whimsical AI', 'whimsical.com', 'Freemium', 'Free / $10/user/mo Pro', 4.8, 16800, 'Fast Flowcharts & Docs', 'Ultra-fast visual workspace generating flowcharts, wireframes, and mind maps with AI prompts.'],
  ['Miro Assist', 'miro.com', 'Freemium', 'Free / $8/user/mo Starter', 4.8, 44000, 'Collaborative Whiteboard', 'Enterprise visual collaboration whiteboard generating user stories, mind maps, and sticky note summaries.'],
  ['Mural AI', 'mural.co', 'Freemium', 'Free / $9.99/user/mo', 4.7, 21000, 'Design Thinking Board', 'Visual collaboration platform guiding design thinking workshops with AI idea clustering.'],
  ['FigJam AI', 'figma.com/figjam', 'Freemium', 'Free / $3/user/mo', 4.9, 36000, 'Figma Whiteboard', 'Figma’s collaborative whiteboard instantly generating sprint retrospectives, diagrams, and timeline charts.'],
  ['Lucidspark AI', 'lucidspark.com', 'Freemium', 'Free / $7.95/user/mo', 4.7, 19400, 'Virtual Brainstorming', 'Virtual whiteboard platform with Collaborative AI generating brainstorming ideas and sorting sticky notes.'],
  ['Boardmix', 'boardmix.com', 'Freemium', 'Free / $5.90/mo', 4.6, 8400, 'AI Diagram Board', 'Online whiteboard equipped with AI flowchart generators, presentation decks, and mind maps.'],
  ['EdrawMind', 'edrawmind.wondershare.com', 'Freemium', 'Free / $59/year', 4.6, 9200, 'Mind Mapping Suite', 'Collaborative mind mapping and brainstorming tool with one-click AI outline expansion.'],
  ['XMind AI', 'xmind.app', 'Freemium', 'Free / $59.99/year', 4.7, 24000, 'Visual Outliner', 'Clean, modern mind-mapping software generating multi-branch visual concept maps effortlessly.'],
  ['GitMind', 'gitmind.com', 'Freemium', 'Free / $9/mo', 4.6, 11500, 'Collaborative Mind Maps', 'Free online mind map and flowchart maker powered by AI ideation and auto-formatting.'],
  ['MindMeister AI', 'mindmeister.com', 'Freemium', 'Free / $6/user/mo', 4.6, 18500, 'Web Mind Mapping', 'Web-based mind-mapping tool allowing distributed teams to brainstorm ideas visually in real time.'],
  ['Process Street AI', 'process.st', 'Freemium', 'Free / $25/user/mo', 4.7, 8900, 'SOP & Workflow Engine', 'No-code process management platform generating standard operating procedures (SOPs) instantly.'],
  ['Pipefy AI', 'pipefy.com', 'Freemium', 'Free / $19/user/mo', 4.6, 12400, 'Business Process AI', 'Process automation platform allowing business teams to build custom approval workflows in plain English.'],
  ['Kissflow', 'kissflow.com', 'Paid', 'From $15/user/mo', 4.5, 7800, 'Low-Code Work Platform', 'Low-code platform for managing enterprise procurement, HR requests, and IT ticketing workflows.'],
  ['Hive AI', 'hive.com', 'Freemium', 'Free / $12/user/mo Starter', 4.6, 11200, 'All-in-One Team Project', 'Project management platform featuring built-in AI writing, automated subtasks, and time tracking.'],
  ['Wrike AI', 'wrike.com', 'Freemium', 'Free / $9.80/user/mo Team', 4.6, 19400, 'Enterprise Work Ops', 'Enterprise project management software utilizing AI risk prediction and work breakdown structures.'],
  ['Smartsheet AI', 'smartsheet.com', 'Freemium', 'Free / $9/user/mo Pro', 4.6, 26000, 'Spreadsheet Work Engine', 'Enterprise spreadsheet-style work platform with AI formula generation and automated reporting.'],
  ['Airtable AI', 'airtable.com', 'Freemium', 'Free / $20/seat/mo Plus', 4.8, 37000, 'Relational App Platform', 'Combines spreadsheet ease with database power, featuring AI field summarization and translation.'],
  ['Basecamp AI', 'basecamp.com', 'Paid', '$15/user/mo or $299/mo', 4.7, 28000, 'Calm Project Management', 'The original calm project management tool organizing message boards, to-dos, and team schedules.'],
  ['Fibery AI', 'fibery.io', 'Freemium', 'Free / $10/user/mo Standard', 4.8, 7900, 'Work & Knowledge Hub', 'Connected workspace platform replacing disparate tools with customizable relational databases and wikis.'],
  ['Nuclino AI', 'nuclino.com', 'Freemium', 'Free / $5/user/mo Standard', 4.8, 12800, 'Ultra-Lightweight Wiki', 'Blazing-fast modern team wiki combining real-time document editing with Sidekick AI writing.'],
  ['Slite AI', 'slite.com', 'Freemium', 'Free / $8/user/mo Standard', 4.7, 11400, 'Knowledge Base Q&A', 'Modern company knowledge base with Ask AI answering employee handbook questions instantly.'],
  ['Slab AI', 'slab.com', 'Freemium', 'Free / $6.67/user/mo', 4.7, 8900, 'Enterprise Knowledge Hub', 'Clean team wiki organizing technical documentation with unified search across all cloud tools.'],
  ['Guru AI', 'getguru.com', 'Freemium', 'Free / $15/user/mo All-in-One', 4.7, 16500, 'Enterprise Search & Wiki', 'AI company wiki that surfaces verified knowledge directly inside Slack, Chrome, and Teams.'],
  ['Tettra', 'tettra.com', 'Freemium', 'Free / $4/user/mo Basic', 4.6, 7400, 'Slack Wiki Assistant', 'Internal knowledge base with Kai AI answering repetitive team questions automatically in Slack.'],
  ['Document360 AI', 'document360.com', 'Paid', 'From $149/mo Starter', 4.7, 8100, 'Customer Knowledge Base', 'Self-service knowledge base software powered by Eddy AI for automated user manual search.'],
  ['Archbee', 'archbee.com', 'Paid', 'From $49/mo Growing', 4.8, 5900, 'Developer Docs Platform', 'Documentation platform tailored for software developers and API documentation with interactive code blocks.'],
  ['GitBook AI', 'gitbook.com', 'Freemium', 'Free / $6.70/user/mo Plus', 4.8, 22000, 'Technical Documentation', 'The documentation platform of choice for open-source engineering teams with Git synchronization.'],
  ['ReadMe AI', 'readme.com', 'Paid', 'From $99/mo Startup', 4.8, 11200, 'Interactive API Hubs', 'Interactive developer documentation hubs that make API exploration and testing frictionless.'],
  ['Mintlify', 'mintlify.com', 'Freemium', 'Free / $120/mo Startup', 4.9, 9800, 'Modern Docs Engine', 'Modern, beautiful documentation engine that turns codebase markdown into stunning developer docs.'],
  ['Dashworks', 'dashworks.ai', 'Paid', 'From $10/user/mo', 4.8, 6200, 'Universal Workplace Search', 'Enterprise search engine that unifies Slack, Notion, Jira, Drive, and GitHub with AI answers.'],
  ['Glean', 'glean.com', 'Paid', 'Enterprise', 4.9, 14200, 'Enterprise Work Assistant', 'The work assistant that searches across all enterprise company SaaS apps with SOC 2 compliance.'],
  ['Qatalog', 'qatalog.com', 'Paid', 'Custom Enterprise', 4.7, 4800, 'Enterprise Work Operating', 'Centralizes project updates, team wikis, and organizational goals into a single intelligent hub.'],
  ['Raycast AI', 'raycast.com', 'Freemium', 'Free / $8/mo Pro', 4.9, 39000, 'Mac Productivity Launcher', 'Extendable Mac launcher replacing Spotlight with instant AI chat, clipboard history, and window management.'],
  ['Alfred AI', 'alfredapp.com', 'Paid', 'Powerpack £34 One-Time', 4.8, 24000, 'Mac Workflow Automation', 'Legendary Mac automation tool with custom scripting workflows and hotkey search actions.'],
  ['Curiosity AI', 'curiosity.ai', 'Freemium', 'Free / $9.99/mo Pro', 4.7, 6100, 'Desktop Universal Search', 'Private local desktop search tool that indexes local folders, emails, and cloud storage.'],
  ['Klu.so', 'klu.so', 'Freemium', 'Free / $8/user/mo', 4.7, 3900, 'Internal Knowledge Search', 'Search platform connecting cloud documents and messaging channels into an instant Q&A bot.'],
  ['Unleash Search', 'unleash.so', 'Freemium', 'Free / $6/user/mo', 4.6, 4200, 'Cross-App Desktop Search', 'Search desktop tool connecting cloud drives, code repositories, and project boards.'],
  ['Workona', 'workona.com', 'Freemium', 'Free / $7/user/mo Pro', 4.7, 14200, 'Tab & Project Manager', 'Tab management workspace that organizes browser tabs by project and syncs across devices.'],
  ['Wavebox', 'wavebox.io', 'Paid', '$12.95/mo or $99.95/yr', 4.7, 5600, 'Work Browser', 'Chromium-based browser designed for SaaS power users juggling dozens of web accounts.'],
  ['Sidekick Browser', 'meetsidekick.com', 'Freemium', 'Free / $8/mo Pro', 4.7, 8200, 'Focus Work Browser', 'Fast, distraction-free browser blocking ads, muting tabs, and boosting battery life.'],
  ['Arc Max by The Browser Company', 'arc.net', 'Free', '100% Free', 4.9, 38000, 'The Modern Web Browser', 'Innovative web browser with AI link previews, tidy tabs, and natural language page questions.'],
  ['SigmaOS', 'sigmaos.com', 'Freemium', 'Free / $10/mo Pro', 4.7, 7400, 'Vertical Tab Browser', 'Keyboard-centric browser designed for rapid workflow execution with Airis AI assistant.'],
  ['Brave Leo AI', 'brave.com/leo', 'Freemium', 'Free / $14.99/mo Premium', 4.8, 21000, 'Private Browser AI', 'Privacy-first browser AI assistant built into Brave summarizing web pages and writing answers.'],
  ['Microsoft Edge Copilot', 'microsoft.com/edge', 'Free', 'Free with Windows / Edge', 4.7, 32000, 'Browser Sidebar Copilot', 'Built-in browser sidebar assistant that analyzes web articles, compares shopping items, and drafts text.'],
  ['Reader by Readwise', 'readwise.io/read', 'Paid', '$8.99/mo (billed annually)', 4.9, 26000, 'Read-It-Later Powerhouse', 'The ultimate read-it-later app with Ghostreader AI summarizing articles and defining terms.'],
  ['Matter', 'hq.getmatter.com', 'Freemium', 'Free / $59.99/year', 4.8, 14500, 'Curated Reading App', 'Reading app with audio narration, newsletter subscriptions, and AI article summaries.'],
  ['Pocket AI', 'getpocket.com', 'Freemium', 'Free / $4.99/mo Premium', 4.6, 31000, 'Save for Later Classic', 'Save articles, videos, and stories from any device with distraction-free offline reading.'],
  ['Instapaper AI', 'instapaper.com', 'Freemium', 'Free / $2.99/mo Premium', 4.6, 19500, 'Clean Text Reader', 'Clean bookmarking tool saving web pages as clean text for comfortable evening reading.'],
  ['Feedly Leo AI', 'feedly.com', 'Paid', 'From $8.25/mo Pro+', 4.8, 18900, 'Market Intelligence Feed', 'AI research assistant filtering out noise and flagging critical industry market trends.'],
  ['Inoreader AI', 'inoreader.com', 'Freemium', 'Free / $7.50/mo Pro', 4.7, 13400, 'RSS News Engine', 'Advanced RSS feed reader with automated keyword filters and article summarization.'],
  ['Upbase', 'upbase.io', 'Freemium', 'Free / $5/mo Unlimited', 4.8, 6700, 'Solo Project Platform', 'All-in-one project management tool engineered specifically for solo founders and freelancers.'],
  ['SmartSuite', 'smartsuite.com', 'Freemium', 'Free / $10/user/mo Team', 4.8, 9200, 'Work Management OS', 'Modern no-code work management platform coordinating workflows, spreadsheets, and databases.'],
  ['GoodNotes AI', 'goodnotes.com', 'Freemium', 'Free / $9.99/year or $29.99', 4.8, 41000, 'Handwriting Assistant', 'Digital handwriting and notebook app for iPad with AI handwriting spell-check and math solvers.'],
  ['Notability AI', 'notability.com', 'Freemium', 'Free / $14.99/year Plus', 4.7, 36000, 'Audio Synced Notes', 'Note-taking app with audio recording synced to pencil strokes and automated transcript summaries.'],
  ['Nebulaw AI', 'nebo.app', 'Freemium', 'Free trial / $8.99 One-Time', 4.7, 11400, 'Ink to Math & Text', 'Handwriting recognition engine converting handwritten notes and math equations into digital text.'],
  ['Concepts App', 'concepts.app', 'Freemium', 'Free / $4.99/mo Pro', 4.8, 19200, 'Infinite Vector Sketch', 'Infinite canvas vector sketching app used by product architects, industrial designers, and illustrators.'],
  ['Whimsical AI Mind Maps', 'whimsical.com/ai', 'Freemium', 'Free / $10/mo', 4.8, 8900, 'AI Mind Mapper', 'Brainstorm ideas and visually outline product strategies with instant AI branch expansion.'],
  ['GitMind AI Flow', 'gitmind.com/flow', 'Freemium', 'Free / $9/mo', 4.6, 5400, 'Process Map Generator', 'Generates detailed swimlane process diagrams and organizational hierarchies from text descriptions.'],
  ['Evernote AI Note Cleanup', 'evernote.com', 'Freemium', 'Free / $14.99/mo Personal', 4.5, 34000, 'Note Cleanup Tool', 'Formats disorganized meeting notes, adds action items, and summarizes documents automatically.'],
  ['OneNote Copilot', 'microsoft.com/onenote', 'Paid', 'Included in Microsoft 365 Copilot', 4.7, 29000, 'Digital Binder AI', 'Microsoft’s digital binder with Copilot summarizing pages, drafting to-do lists, and generating plans.']
];

additionalProductivity.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} optimizes modern knowledge organization, task orchestration, and workflow productivity. By automating repetitive administrative overhead and connecting scattered data into clear action items, it keeps teams aligned and focused. Thousands of busy operators depend on it daily to conquer complex project workflows.`,
    tags: ['Productivity', 'Knowledge Base', 'Task Management', 'Workflow Automation', 'Time Management'],
    pros: ['Eliminates manual task tracking and fragmented document sprawl', 'Intelligent search and contextual auto-summarization across project records', 'Seamless cross-platform availability supporting desktop and mobile devices'],
    cons: ['Team-wide adoption requires onboarding alignment and process consistency', 'Advanced automated rules and unlimited history require paid plan tiers'],
    bestFor: 'Founders, knowledge workers, project managers, and remote engineering teams.'
  });
});
