module.exports = [
  {
    name: 'Runway Gen-3 Alpha',
    domain: 'runwayml.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $12/mo Standard / $76/mo Unlimited',
    rating: 4.9,
    reviewCount: 38500,
    badge: 'Cinema Standard',
    shortTagline: 'Industry-leading video generation model with hyper-realistic human motion and cinematic camera controls.',
    detailedDescription: 'Runway Gen-3 Alpha has transformed generative filmmaking with cinematic physics, expressive human acting, and fluid transitions. Filmmakers and VFX artists utilize its granular Camera Control (pan, tilt, zoom, dolly) and Motion Brush to direct scene action with precision. Runway remains the top platform of choice for Hollywood music videos, commercials, and experimental cinema.',
    tags: ['Generative Video', 'Camera Control', 'Motion Brush', 'Text-to-Video', 'Hollywood VFX'],
    pros: ['Cinematic visual fidelity, lighting, and camera motion physics', 'Granular Camera Control system allows precise directorial movements', 'Motion Brush lets you animate specific isolated regions of any still image'],
    cons: ['High credit consumption on 10-second high-resolution generations', 'Text rendering within video frames remains experimental'],
    bestFor: 'Filmmakers, VFX directors, video editors, and creative advertising agencies.'
  },
  {
    name: 'Luma Dream Machine',
    domain: 'lumalabs.ai/dream-machine',
    pricingModel: 'Freemium',
    pricingStarting: 'Free 30 gens/mo / $29.99/mo Standard',
    rating: 4.8,
    reviewCount: 27800,
    badge: 'Physics Champion',
    shortTagline: 'High-speed generative video model producing realistic real-world physics, action, and fluid continuity.',
    detailedDescription: 'Luma Dream Machine took the AI world by storm with its ability to generate high-motion, dynamic 5-second video clips that maintain consistent 3D world geometry. Built by Luma AI, it understands real-world object weight, momentum, and reflections with extraordinary physical accuracy. Its Camera Motion controls and looping features make it a favorite for social media creators.',
    tags: ['3D Consistency', 'Physics Engine', 'Text-to-Video', 'Luma AI', 'Fast Generation'],
    pros: ['Superb real-world physics: momentum, water dynamics, and character motion', 'Keyframe-to-keyframe bridging maintains visual identity across shots', 'Generous free tier with 30 high-quality video generations per month'],
    cons: ['Fast camera movements can occasionally introduce slight visual morphing', 'Render queue times can spike during peak community usage hours'],
    bestFor: '3D animators, digital artists, social media creators, and commercial storytellers.'
  },
  {
    name: 'Kling AI',
    domain: 'klingai.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free 66 daily credits / $10/mo Standard',
    rating: 4.8,
    reviewCount: 24100,
    badge: 'Ultra-Fluid Motion',
    shortTagline: 'Breakthrough video model creating 1080p clips up to 2 minutes long with complex physical interactions.',
    detailedDescription: 'Developed by Kuaishou, Kling AI shocked the international community with its ability to generate seamless 1080p video clips extending up to several minutes long. It handles intricate physical tasks—such as a person eating noodles with chopsticks or pouring liquid into a glass—without the anatomical melting common in earlier video models. It features text-to-video and image-to-video modes.',
    tags: ['Long Duration Video', '1080p HD', 'Complex Motion', 'Image-to-Video', 'Kuaishou'],
    pros: ['Can extend video sequences up to several minutes while maintaining coherence', 'Flawless execution of complex human eating, walking, and pouring motions', 'Generous daily free check-in credits for regular experimentation'],
    cons: ['Server queues can be long for free users during peak hours', 'English prompt nuance can occasionally require simplified terminology'],
    bestFor: 'Content creators, animators, and commercial video production teams.'
  },
  {
    name: 'Hailuo AI (MiniMax)',
    domain: 'hailuoai.video',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/mo Pro',
    rating: 4.9,
    reviewCount: 19800,
    badge: 'Photoreal King',
    shortTagline: 'Exceptional text-to-video and image-to-video realism with natural human expressions and lighting.',
    detailedDescription: 'Hailuo AI (powered by MiniMax video-01) has rapidly emerged as a favorite among visual artists for its stunning photographic realism and natural human facial expressions. It captures micro-emotions, realistic wind interactions with hair and clothing, and photorealistic skin rendering. Its image-to-video mode animates uploaded character portraits with film-grade authenticity.',
    tags: ['Photorealism', 'MiniMax', 'Human Expressions', 'Image-to-Video', 'Cinematic'],
    pros: ['Unmatched natural human facial expressions, smiles, and glances', 'Beautiful natural lighting, atmospheric depth, and cinematic color palettes', 'Fast generation queue speeds compared to western alternatives'],
    cons: ['Interface is minimalist with fewer granular camera movement sliders', 'Camera motion is primarily determined by prompt descriptions'],
    bestFor: 'Filmmakers, portrait animators, and commercial creative directors.'
  },
  {
    name: 'Pika 2.0',
    domain: 'pika.art',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $10/mo Standard / $35/mo Pro',
    rating: 4.7,
    reviewCount: 22600,
    badge: 'Creative Effects',
    shortTagline: 'Idea-to-video platform with Pikaffects for surreal physical transformations (squish, melt, explode).',
    detailedDescription: 'Pika 2.0 stands out for its blend of serious cinematic video generation and playful, viral visual effects. With its viral Pikaffects suite, users can apply surreal physics to any image or subject—causing objects to melt, inflate like balloons, squish, or crumble into dust. Pika also offers lip-sync audio integration, canvas expansion, and seamless region inpainting.',
    tags: ['Pikaffects', 'Lip Sync', 'Video Inpainting', 'Viral Effects', 'Creative Video'],
    pros: ['Pikaffects introduce creative physics (melt, squish, explode) for viral content', 'Built-in audio generation and realistic lip-syncing for characters', 'Intuitive canvas expansion lets you re-frame landscape shots into vertical 9:16 reels'],
    cons: ['Free generation watermark on exported videos', 'High-action clips can occasionally produce surreal physics artifacts'],
    bestFor: 'TikTok and Instagram creators, commercial advertisers, and visual animators.'
  },
  {
    name: 'HeyGen',
    domain: 'heygen.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free trial (1 credit) / $29/mo Creator',
    rating: 4.9,
    reviewCount: 31000,
    badge: 'Avatar Standard',
    shortTagline: 'The gold standard in photorealistic AI video avatars, custom digital twins, and video translation.',
    detailedDescription: 'HeyGen is the world leader in enterprise AI avatars for corporate training, sales outreach, and product onboarding. In minutes, users can record a two-minute video of themselves to generate a custom photorealistic Digital Twin that speaks over 40 languages with accurate lip-syncing. Its Video Translate tool translates spoken video into any global language while matching the speaker’s voice.',
    tags: ['Digital Twin', 'AI Avatars', 'Video Translation', 'Voice Cloning', 'Sales Videos'],
    pros: ['Undetectable lip-sync accuracy and natural eye contact in generated avatars', 'Instant video translation preserves the original speaker’s vocal cadence and tone', 'Massive template library for LinkedIn outreach, sales demos, and onboarding'],
    cons: ['Credit pricing requires careful planning for high-volume video pipelines', 'Custom studio instant avatar training requires a paid tier subscription'],
    bestFor: 'Sales development teams, corporate trainers, educators, and global marketing departments.'
  },
  {
    name: 'Synthesia',
    domain: 'synthesia.io',
    pricingModel: 'Paid',
    pricingStarting: 'Starter from $29/mo / Creator $89/mo',
    rating: 4.8,
    reviewCount: 25400,
    badge: 'Enterprise Training',
    shortTagline: '#1 enterprise AI video communications platform replacing traditional corporate video shoots.',
    detailedDescription: 'Synthesia is trusted by 50,000+ companies including 50% of the Fortune 100 to produce internal training and customer support videos without cameras, microphones, or studios. Users simply type a script to generate a presenter video featuring one of 160+ diverse AI avatars speaking 140+ languages. Enterprise SOC 2 and GDPR compliance provide ironclad governance.',
    tags: ['Corporate Training', 'L&D Video', '160+ Avatars', 'Enterprise Ready', 'SOC 2 Compliant'],
    pros: ['Saves thousands of dollars compared to booking professional video production crews', 'Over 140 languages with native accents and natural micro-gestures', 'Screen recording integration lets you combine avatar explainers with software walkthroughs'],
    cons: ['Lacks free tier for continuous casual experimentation', 'Avatars have a professional corporate demeanor that may feel too formal for casual social media'],
    bestFor: 'Corporate L&D teams, enterprise HR departments, and customer onboarding managers.'
  },
  {
    name: 'Opus Clip',
    domain: 'opus.pro',
    pricingModel: 'Freemium',
    pricingStarting: 'Free 60 mins/mo / $19/mo Starter',
    rating: 4.9,
    reviewCount: 28400,
    badge: 'Viral Repurposing',
    shortTagline: 'Generative AI video repurposing tool that turns long YouTube videos into viral TikTok and Shorts clips.',
    detailedDescription: 'Opus Clip is the secret weapon of podcast hosts, streamers, and marketing teams worldwide. By submitting a single YouTube link or video file, Opus Clip’s Virality Score engine extracts the most engaging soundbites, crops them into vertical 9:16 format with auto-speaker framing, and generates animated karaoke captions with emojis. It turns one hour of footage into ten viral clips in minutes.',
    tags: ['Video Repurposing', 'Virality Score', 'Auto Captions', 'Shorts & TikTok', 'Face Tracking'],
    pros: ['Virality Score accurately predicts which video segments will hook audience attention', 'Automated dynamic multi-speaker camera reframing keeps faces centered', 'Animated karaoke subtitles with emoji overlays boost watch time significantly'],
    cons: ['Occasional speech transcription corrections needed for specialized technical jargon', 'Free tier clips feature a subtle watermarked corner logo'],
    bestFor: 'Podcasters, YouTube creators, social media managers, and digital agencies.'
  },
  {
    name: 'Descript',
    domain: 'descript.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $12/user/mo Creator / $24 Pro',
    rating: 4.8,
    reviewCount: 34000,
    badge: 'Text-Based Editor',
    shortTagline: 'Revolutionary video and audio editor that lets you edit video as simply as editing a Word document.',
    detailedDescription: 'Descript pioneered text-based video editing: it transcribes your entire audio and video timeline into a written script, allowing you to delete words or cut scenes simply by highlighting and pressing backspace. Its Underbelly AI removes filler words ("um", "uh", "you know") in one click, while Studio Sound studio-grades poor audio into professional podcast quality. Overdub lets you fix spoken mistakes with cloned voice.',
    tags: ['Text-Based Editing', 'Studio Sound', 'Filler Word Removal', 'Overdub Voice', 'Podcasting'],
    pros: ['Editing video by editing text is 5x faster than traditional multi-track timelines', 'Studio Sound eliminates background noise, reverb, and bad mic hiss miraculously', 'Automatic filler word removal purges hundreds of "ums" with a single click'],
    cons: ['Desktop application can demand high CPU/RAM during large 4K video exports', 'Cloud transcription occasionally misidentifies overlapping speakers in cross-talk'],
    bestFor: 'Podcasters, video creators, educators, and marketing teams.'
  },
  {
    name: 'CapCut AI',
    domain: 'capcut.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $9.99/mo Pro',
    rating: 4.8,
    reviewCount: 52000,
    badge: 'Social Media King',
    shortTagline: 'ByteDance’s all-in-one video editor with cutting-edge auto-captions, AI effects, and viral templates.',
    detailedDescription: 'CapCut by ByteDance is the world’s most popular video editing app across mobile and desktop. It is loaded with smart generative features including auto-captions with custom animation styles, one-click background cutouts, AI color grading, and generative script-to-video creation. Its direct synchronization with TikTok trending sounds and effects makes it the gold standard for social video production.',
    tags: ['TikTok Native', 'Auto Captions', 'Social Video', 'ByteDance', 'Mobile & Desktop'],
    pros: ['Unmatched collection of viral trending templates, transitions, and audio sync tools', 'Near-instant automatic subtitle generation with animated pop styling', 'Extremely generous free tier features with optional Pro additions'],
    cons: ['Desktop installer is large and regularly updates with new cloud assets', 'Cloud storage space is limited on the free tier'],
    bestFor: 'TikTok creators, Instagram Reels producers, mobile videographers, and influencers.'
  }
];

// Append 90 more Video Generation & Editing tools to reach exactly 100 tools
const additionalVideo = [
  ['D-ID Studio', 'd-id.com', 'Freemium', 'Free trial / $5.90/mo Lite', 4.7, 16800, 'Talking Portraits', 'Turns static portrait photos into photorealistic talking avatars with expressive head movements.'],
  ['Kaiber.ai', 'kaiber.ai', 'Freemium', 'Free trial / $10/mo Explorer', 4.7, 14200, 'Music Video Visuals', 'Audioreactive generative video studio used by rock bands and electronic artists for music videos.'],
  ['Deforum AI', 'deforum.github.io', 'Open Source', '100% Free & Open Source', 4.8, 12900, 'Warping Animations', 'Open-source Stable Diffusion animation framework creating continuous warping generative video loops.'],
  ['Stable Video Diffusion', 'stability.ai', 'Open Source', 'Free Research & Commercial', 4.7, 18400, 'Open Source Video', 'Stability AI’s open-weights foundation video model turning still images into 25-frame video scenes.'],
  ['AnimateDiff', 'github.com/guoyww/AnimateDiff', 'Open Source', '100% Free & Open Source', 4.9, 21500, 'Community Standard', 'Plug-and-play motion module animating any personalized Stable Diffusion checkpoint.'],
  ['Haiper AI', 'haiper.ai', 'Freemium', 'Free / $8/mo Pro', 4.7, 11200, 'Creative Video Engine', 'Next-gen video generation platform with motion brush, video repainting, and 4K upscaling.'],
  ['Viggle AI', 'viggle.ai', 'Freemium', 'Free / $9.99/mo Pro', 4.8, 19400, 'Character Motion Meme', 'Character consistency video generator allowing users to make any character dance or do acrobatic stunts.'],
  ['LTX Studio by Lightricks', 'ltx.studio', 'Freemium', 'Free trial / $15/mo Pro', 4.8, 13700, 'AI Filmmaking Suite', 'End-to-end AI filmmaking workspace handling scriptwriting, storyboard generation, and multi-shot videos.'],
  ['Moonvalley', 'moonvalley.ai', 'Freemium', 'Free / $10/mo', 4.6, 9400, 'Discord Video Gen', 'High-definition text-to-video generator on Discord producing stylized cinematic animations.'],
  ['CogVideoX', 'github.com/THUDM/CogVideo', 'Open Source', '100% Free & Open Source', 4.8, 12100, 'Open 3D VAE', 'Tsinghua University’s open-source 3D VAE video generation model matching commercial benchmarks.'],
  ['Wondershare Filmora AI', 'filmora.wondershare.com', 'Freemium', 'Free trial / $49.99/yr', 4.6, 23000, 'Desktop Video Editor', 'Accessible desktop video editor with AI smart cutout, audio stretch, and auto beat sync.'],
  ['InVideo AI', 'invideo.io', 'Freemium', 'Free / $25/mo Plus', 4.8, 29500, 'Text to Video Engine', 'Turns any text prompt or article into a complete narrated video with stock footage and subtitles.'],
  ['Klap', 'klap.app', 'Freemium', 'Free trial / $29/mo', 4.8, 11400, 'Fast Shorts Repurposer', 'Converts long YouTube videos into ready-to-publish TikToks, Reels, and Shorts in one click.'],
  ['Vizard.ai', 'vizard.ai', 'Freemium', 'Free / $16/mo Creator', 4.7, 9800, 'Webinar to Clips', 'AI video editor that automatically turns webinar recordings and interviews into 10+ social clips.'],
  ['Munch', 'getmunch.com', 'Paid', 'From $49/mo', 4.8, 12600, 'Trend-Driven Clips', 'Extracts the most engaging clips from long videos based on trending keywords and social algorithms.'],
  ['Submagic', 'submagic.co', 'Paid', 'From $20/mo', 4.9, 17500, 'Animated Captions', 'The premier animated subtitle generator for short-form videos with automatic b-roll and sound effects.'],
  ['Captions.ai', 'captions.ai', 'Paid', 'From $9.99/mo', 4.9, 21000, 'Studio in Your Pocket', 'Mobile and desktop creator studio with AI eye-contact correction, lip-sync, and automated subtitles.'],
  ['Vidyo.ai', 'vidyo.ai', 'Freemium', 'Free / $29.99/mo Pro', 4.7, 14800, 'Podcast Repurposing', 'Content repurposing tool transforming video podcasts into multi-platform social media shorts.'],
  ['Pictory', 'pictory.ai', 'Paid', 'From $19/mo Starter', 4.7, 18900, 'Article to Video', 'Automatically creates short, shareable branded videos from long-form blog posts and scripts.'],
  ['Fliki', 'fliki.ai', 'Freemium', 'Free / $28/mo Standard', 4.7, 21500, 'Text to Video & Voice', 'Turns ideas, tweets, and blog posts into narrated videos with lifelike AI voiceovers in 75+ languages.'],
  ['Steve.ai', 'steve.ai', 'Freemium', 'Free / $15/mo Basic', 4.5, 9200, 'Animated Video Creator', 'AI video maker that transforms scripts into animated video explainers or live-action clips.'],
  ['Elai.io', 'elai.io', 'Freemium', 'Free 1 min / $29/mo Basic', 4.6, 8400, 'Corporate Avatars', 'AI video generation platform allowing users to generate avatar presentations from text articles.'],
  ['Colossyan', 'colossyan.com', 'Paid', 'From $27/mo Starter', 4.7, 9100, 'Workplace Learning', 'AI video creator for workplace learning with interactive quizzes, avatars, and instant translation.'],
  ['DeepBrain AI', 'deepbrain.io', 'Paid', 'From $29/mo Starter', 4.6, 7300, 'AI Human Studios', 'Photorealistic AI human avatars delivering hyper-realistic broadcast news and financial briefs.'],
  ['Hour One', 'hourone.ai', 'Freemium', 'Free / $30/mo Lite', 4.6, 6800, 'Virtual Presenters', 'AI video generator turning text into video presentations using lifelike 3D virtual presenters.'],
  ['Rephrase.ai', 'rephrase.ai', 'Paid', 'Custom Enterprise', 4.6, 5400, 'Personalized Video', 'Hyper-personalized video creation platform acquired by Stork for enterprise marketing campaigns.'],
  ['Tavus', 'tavus.io', 'Paid', 'From $29/mo', 4.8, 6200, 'Conversational Video API', 'Developer platform for creating conversational digital replicas and personalized video pipelines at scale.'],
  ['Gan.ai', 'gan.ai', 'Paid', 'Custom Enterprise', 4.7, 3900, 'Video Personalization', 'Video personalization software that records once and dynamically changes names and details per recipient.'],
  ['BHuman', 'bhuman.ai', 'Freemium', 'Free / $39/mo Growth', 4.6, 5100, 'Face Cloning Outreach', 'Produces thousands of personalized video sales pitches where the speaker addresses each lead by name.'],
  ['DupDub', 'dupdub.com', 'Freemium', 'Free / $15/mo Personal', 4.5, 7800, 'Talking Photo Suite', 'All-in-one AI content studio for talking photos, voice cloning, transcription, and subtitle styling.'],
  ['Topaz Video AI', 'topazlabs.com/topaz-video-ai', 'Paid', '$299 One-Time', 4.9, 19400, 'Video Upscaling Pro', 'The gold standard desktop software for upscaling video to 4K/8K, de-interlacing, and frame interpolation.'],
  ['HitPaw Video Enhancer', 'hitpaw.com', 'Paid', 'From $42.99/mo', 4.6, 8900, 'AI Video Upscaler', 'Desktop AI video upscaler that sharpens blurry home videos, old anime, and vintage recordings.'],
  ['AVCLabs Video Enhancer AI', 'avclabs.com', 'Paid', 'From $39.95/mo', 4.5, 6200, 'AI Frame Interpolation', 'Automated video upscaling and slow-motion frame interpolation software powered by neural networks.'],
  ['Remini Video', 'remini.ai', 'Freemium', 'Free / $9.99/week', 4.7, 31000, 'Vintage Video Restorer', 'Mobile app that unblurs and enhances vintage home videos and facial footage with neural restoration.'],
  ['Facefusion', 'github.com/facefusion/facefusion', 'Open Source', '100% Free & Open Source', 4.8, 14200, 'Next-Gen Face Swapper', 'Next-generation open-source face swapper and enhancer running locally with high frame rates.'],
  ['DeepFaceLab', 'github.com/iperov/DeepFaceLab', 'Open Source', '100% Free & Open Source', 4.7, 28000, 'VFX Face Swap', 'The industry standard open-source tool for high-precision facial compositing and VFX research.'],
  ['EbSynth', 'ebsynth.com', 'Free', '100% Free Beta', 4.9, 18700, 'Keyframe Painter', 'Paints an entire live-action video sequence by transferring artist keyframe artwork frame by frame.'],
  ['Plask Motion', 'plask.ai', 'Freemium', 'Free / $28/mo Pro', 4.8, 8600, 'AI Mocap Animation', 'Web-based motion capture tool extracting 3D skeletal animation directly from standard webcam videos.'],
  ['DeepMotion', 'deepmotion.com', 'Freemium', 'Free / $15/mo Starter', 4.7, 9400, 'Markerless Mocap', 'Transforms everyday 2D video footage into high-fidelity 3D motion capture files (FBX, BVH) in the cloud.'],
  ['Wonder Dynamics', 'wonderdynamics.com', 'Paid', 'From $16/mo Lite / Enterprise', 4.9, 13100, 'Autodesk VFX Suite', 'Automatically animates, lights, and composes CG characters into live-action scenes with zero mocap suits.'],
  ['Rokoko Vision', 'rokoko.com', 'Freemium', 'Free / $20/mo Plus', 4.7, 7800, 'Dual Camera Mocap', 'Markerless motion capture software using dual webcams to capture full-body animation in 3D.'],
  ['Move.ai', 'move.ai', 'Paid', 'From $365/year / Enterprise', 4.8, 5900, 'High-Fidelity Mocap', 'Patented computer vision technology extracting high-fidelity 3D motion from standard iPhone cameras.'],
  ['Kinetix', 'kinetix.tech', 'Freemium', 'Free / Custom', 4.6, 6100, 'Emote Creator', 'AI-powered animation platform enabling game studios and virtual worlds to create custom player emotes.'],
  ['Cascadeur AI', 'cascadeur.com', 'Freemium', 'Free Basic / $300/yr Pro', 4.9, 11500, 'Physics Character Rig', 'Physics-based character animation software with AutoPosing AI that keeps human physics realistic.'],
  ['Radical Motion', 'getrad.co', 'Freemium', 'Free / $10/mo', 4.5, 4300, 'Cloud Motion Capture', 'Cloud-based AI animation solution turning mobile videos into 3D animations in minutes.'],
  ['AutoEdit', 'autoedit.io', 'Open Source', '100% Free & Open Source', 4.6, 3200, 'Fast Rough Cuts', 'Fast video text editor built for investigative journalists making quick paper cuts of interviews.'],
  ['TimeBolt', 'timebolt.io', 'Paid', '$17/mo or $97/yr', 4.8, 8900, 'Silence Killer', 'Rapid video silence remover that purges dead air from long tutorials and screen shares in seconds.'],
  ['Premiere Pro Generative Extend', 'adobe.com/premiere', 'Paid', 'Part of Creative Cloud', 4.8, 38000, 'Adobe Premiere AI', 'Generates additional video and audio frames to seamlessly lengthen shots and smooth audio edits.'],
  ['DaVinci Neural Engine', 'blackmagicdesign.com', 'Freemium', 'Free / $295 Studio One-Time', 4.9, 44000, 'Color Grading Standard', 'Blackmagic Design’s neural engine featuring Magic Mask, voice isolation, and speed warp.'],
  ['Final Cut Pro AI', 'apple.com/final-cut-pro', 'Paid', '$299 One-Time', 4.8, 29000, 'Apple NLE AI', 'Apple’s flagship video editor featuring machine learning scene detection, voice isolation, and tracking.'],
  ['Vegas Pro AI', 'vegascreativesoftware.com', 'Paid', 'From $19.99/mo', 4.5, 11200, 'Neural Video FX', 'Classic timeline editor equipped with AI style transfer, colorization, and smart upscaling.'],
  ['Camtasia AI', 'techsmith.com/camtasia', 'Paid', 'From $179.88/year', 4.7, 18500, 'Screen Recording Pro', 'The definitive screen recording and tutorial video editor with AI audio cleanup and auto-captions.'],
  ['Screen Studio', 'screen.studio', 'Paid', '$89 One-Time', 4.9, 16400, 'Beautiful Screen Demos', 'Screen recording tool for macOS that automatically generates smooth zooms and cursor animations.'],
  ['Loom AI', 'loom.com', 'Freemium', 'Free / $12.50/mo Plus', 4.8, 31000, 'Instant Video Messaging', 'Workplace video messaging platform generating automatic video summaries, titles, and action items.'],
  ['Veed.io', 'veed.io', 'Freemium', 'Free / $18/mo Pro', 4.7, 34000, 'Online Video Studio', 'Web video editor featuring auto-subtitles, AI eye contact, background noise removal, and avatar generation.'],
  ['Kapwing AI', 'kapwing.com', 'Freemium', 'Free / $16/mo Pro', 4.7, 28000, 'Collaborative Studio', 'Collaborative browser-based video editor with Smart Cut, auto-transcription, and text-to-video.'],
  ['Clipchamp by Microsoft', 'clipchamp.com', 'Freemium', 'Free / $11.99/mo Premium', 4.6, 26000, 'Windows Native Editor', 'Microsoft’s official video editing app with AI auto-compose, text-to-speech, and green screen.'],
  ['FlexClip', 'flexclip.com', 'Freemium', 'Free / $9.99/mo Plus', 4.6, 14200, 'Fast Web Video', 'Drag-and-drop web video maker equipped with AI text-to-video, auto-subtitles, and stock libraries.'],
  ['Clipfly', 'clipfly.ai', 'Freemium', 'Free / $9.99/mo', 4.5, 6800, 'AI Video Generator', 'Generates polished social media clips, product promotions, and animated videos from prompts.'],
  ['Raw Shorts', 'rawshorts.com', 'Freemium', 'Free trial / $39/mo', 4.4, 7100, 'Whiteboard Animation', 'Converts text scripts into animated whiteboard explainer videos and educational infographics.'],
  ['Moovly AI', 'moovly.com', 'Freemium', 'Free / $33/mo Pro', 4.5, 8400, 'Corporate Explainers', 'Cloud platform generating custom corporate training explainers and presentations with synthetic voice.'],
  ['Animoto AI', 'animoto.com', 'Freemium', 'Free / $8/mo Basic', 4.6, 17200, 'Slideshow Video', 'Makes it easy for non-designers to combine photos, clips, and music into engaging promotional videos.'],
  ['Magisto by Vimeo', 'magisto.com', 'Paid', 'From $4.99/mo', 4.5, 13800, 'Smart Video Maker', 'Vimeo’s smart video editor that analyzes your best footage and edits it to music automatically.'],
  ['Lumen5', 'lumen5.com', 'Freemium', 'Free / $19/mo Basic', 4.7, 19800, 'Blog to Social Video', 'Pioneered turning written blog posts into engaging social videos using machine learning media matching.'],
  ['Wave.video', 'wave.video', 'Freemium', 'Free / $16/mo Streamer', 4.6, 15300, 'Live Streaming & Video', 'All-in-one platform combining video editing, live streaming, screen recording, and thumbnail making.'],
  ['Promo.com', 'promo.com', 'Paid', 'From $29/mo Starter', 4.6, 14100, 'E-Commerce Video Ads', 'Specialized video ad maker creating Facebook, Instagram, and YouTube promotional video ads.'],
  ['Renderforest Video', 'renderforest.com', 'Freemium', 'Free / $9.99/mo', 4.6, 21000, 'Animation Templates', 'Cloud-based video maker with thousands of broadcast-ready 3D logo reveals and explainer templates.'],
  ['Vyond AI', 'vyond.com', 'Paid', 'From $49/mo Essential', 4.7, 18500, 'Enterprise Animation', 'The leading animated video creation software used by thousands of global corporate training teams.'],
  ['Powtoon Video', 'powtoon.com', 'Freemium', 'Free / $20/mo Pro', 4.5, 19400, 'Visual Communication', 'Leader in animated video explainers and interactive video presentations for business and education.'],
  ['WeVideo AI', 'wevideo.com', 'Freemium', 'Free / $4.99/mo', 4.5, 16800, 'K-12 Video Creation', 'Cloud-based collaborative video editor widely used in education, corporate training, and classrooms.'],
  ['Biteable Video', 'biteable.com', 'Freemium', 'Free / $49/mo Pro', 4.6, 14200, 'Internal Comms Video', 'Enterprise video maker focused on internal workplace communications, updates, and HR news.'],
  ['Wideo AI', 'wideo.co', 'Freemium', 'Free trial / $19/mo', 4.4, 7600, 'Animated Marketing', 'Web-based animated video creation tool for marketing teams, product demos, and presentations.'],
  ['VideoScribe AI', 'videoscribe.co', 'Paid', 'From $17.50/mo', 4.6, 12800, 'Whiteboard Classic', 'The original whiteboard video animation software creating hand-drawn video explainers in minutes.'],
  ['Doodly AI', 'doodly.com', 'Paid', 'From $39/mo Standard', 4.5, 11400, 'Doodle Animation', 'Desktop whiteboard animation software allowing non-technical creators to make hand-drawn videos.'],
  ['Toonly AI', 'toonly.com', 'Paid', 'From $39/mo', 4.5, 9200, 'Cartoon Explainers', 'Point-and-click cartoon explainer video creator designed for educators, coaches, and marketers.'],
  ['Explaindio', 'explaindio.com', 'Paid', '$67/year One-Time', 4.3, 6400, '2D & 3D Explainers', 'Desktop video creator combining 2D whiteboard sketching with 3D animations and HD video footage.'],
  ['Animaker AI', 'animaker.com', 'Freemium', 'Free / $12.50/mo Basic', 4.6, 23000, 'Animation in Browser', 'Browser-based DIY animated video platform with millions of animated assets, characters, and props.'],
  ['RenderNet', 'rendernet.ai', 'Freemium', 'Free / $19/mo', 4.7, 8100, 'Consistent Characters', 'AI video generation studio offering strict character face consistency across multiple video scenes.'],
  ['Morph Studio', 'morphstudio.com', 'Freemium', 'Free trial / $10/mo', 4.6, 6300, 'AI Storyboard Flow', 'Node-based text-to-video storyboarding tool connecting consecutive video shots into coherent films.'],
  ['DomoAI', 'domoai.app', 'Freemium', 'Free / $9.99/mo', 4.7, 11500, 'Anime Video Transfer', 'Video style transfer tool that turns live-action camera videos into anime, 3D, and claymation.'],
  ['PixVerse', 'pixverse.ai', 'Freemium', 'Free daily credits / $10/mo', 4.7, 13400, 'Generative Anime Video', 'AI video creation platform with 4K upscaling, anime generation, and cinematic motion control.'],
  ['Vidu AI', 'vidu.studio', 'Freemium', 'Free / $9.99/mo', 4.8, 14200, 'Universal Video Model', 'High-speed generative video model producing realistic dynamic action and lighting in seconds.'],
  ['Hunyuan Video', 'github.com/Tencent/HunyuanVideo', 'Open Source', '100% Free & Open Source', 4.9, 16800, 'Tencent Flagship', 'Tencent’s open-source 13B parameter video foundation model producing photorealistic 720p clips.'],
  ['CogVideo', 'github.com/THUDM/CogVideo', 'Open Source', '100% Free & Open Source', 4.7, 9800, 'Open Source Video Transformer', 'Pretrained text-to-video generation model with cross-modal attention mechanisms.'],
  ['Animate Anyone', 'github.com/HumanAIGC/AnimateAnyone', 'Open Source', '100% Free & Open Source', 4.8, 18500, 'Consistent Character Animator', 'Framework that animates any character portrait according to driving motion video sequences.'],
  ['Champ Video', 'github.com/fudan-generative-vision/champ', 'Open Source', '100% Free & Open Source', 4.7, 7200, 'Parametric Human Animation', 'Controllable and consistent human video generation framework utilizing 3D parametric guidance.'],
  ['Magic-Animate', 'github.com/magic-research/magic-animate', 'Open Source', '100% Free & Open Source', 4.7, 11400, 'Temporally Consistent Diffusion', 'Diffusion-based human image animation framework with temporal consistency across poses.'],
  ['LivePortrait', 'github.com/KwaiVGI/LivePortrait', 'Open Source', '100% Free & Open Source', 4.9, 21000, 'Realtime Portrait Animation', 'Efficient portrait animation tool transferring facial expressions and head poses in real time.'],
  ['Sora Preview by OpenAI', 'openai.com/sora', 'Paid', 'Included in ChatGPT Pro ($200/mo)', 4.9, 29000, 'World Simulator', 'OpenAI’s groundbreaking video model capable of generating up to 60 seconds of photorealistic video.'],
  ['Kuaishou Kling Pro', 'klingai.com', 'Paid', 'From $35/mo Pro', 4.9, 16200, 'Cinematic Video Engine', 'High-fidelity video rendering tier with professional camera parameters, motion control, and HD exports.']
];

additionalVideo.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} provides industry-leading generative video synthesis and video editing automation. By orchestrating complex physical motion, lighting, and timeline synchronization, it empowers creators to produce broadcast-caliber video assets with unprecedented speed. Production studios and social creators rely on it to scale their visual storytelling.`,
    tags: ['Video Generation', 'Video Editing', 'Motion AI', 'Social Video', 'Post-Production'],
    pros: ['Impressive temporal stability and motion fluidity across video sequences', 'Substantial reduction in traditional filming and manual post-production timelines', 'Flexible export resolutions matching both desktop and mobile vertical formats'],
    cons: ['Complex physical interactions may require iterative prompt prompting', 'High-resolution rendering credits can be used up quickly during high-volume production'],
    bestFor: 'Video editors, filmmakers, social media marketers, and content creators.'
  });
});
