module.exports = [
  {
    name: 'Midjourney v6.1',
    domain: 'midjourney.com',
    pricingModel: 'Paid',
    pricingStarting: 'Basic $10/mo / Standard $30/mo',
    rating: 4.9,
    reviewCount: 48000,
    badge: 'Artistic Pinnacle',
    shortTagline: 'Unmatched photorealism, artistic style coherence, and cinematic visual synthesis.',
    detailedDescription: 'Midjourney remains the premier benchmark in generative visual artistry. With version 6.1, it renders hyper-realistic textures, complex reflections, cinematic lighting, and legible typography with breathtaking fidelity. Available both via Discord and its dedicated web generation canvas, it serves as the ultimate concept art tool for directors, game studios, and designers.',
    tags: ['Photorealism', 'Cinematic Art', 'Concept Art', 'Text Rendering', 'Discord & Web'],
    pros: ['Unparalleled aesthetic beauty and nuanced artistic interpretation', 'Superb rendering of human skin textures, hands, and micro-details', 'Intuitive inpainting, panning, and visual style reference parameters'],
    cons: ['No free trial tier due to intense GPU computing demands', 'Prompt structure requires learning specialized parameter flags (--ar, --s, --c)'],
    bestFor: 'Concept artists, creative directors, illustrators, and visual storytellers.'
  },
  {
    name: 'Flux.1 by Black Forest Labs',
    domain: 'blackforestlabs.ai',
    pricingModel: 'Open Source',
    pricingStarting: 'Free Schnell / Paid Dev & Pro',
    rating: 4.9,
    reviewCount: 32000,
    badge: 'Open Weights King',
    shortTagline: 'State-of-the-art 12-billion parameter rectified flow model with precise prompt following.',
    detailedDescription: 'Created by the original inventors of Stable Diffusion at Black Forest Labs, Flux.1 is the reigning champion of open visual foundation models. Offered in Schnell (open Apache 2.0), Dev (non-commercial open), and Pro tiers, it excels at complex multi-subject prompts and perfect typographic text integration. It runs seamlessly on modern consumer hardware and cloud inference endpoints.',
    tags: ['Rectified Flow', 'Open Weights', 'Prompt Following', 'Typography', '12B Parameters'],
    pros: ['Flawless rendering of clean text, signs, logos, and intricate typography inside images', 'Exceptional prompt following that respects every compositional constraint', 'Schnell model is permissively licensed for commercial open-source projects'],
    cons: ['Dev and Pro models require high VRAM (16GB-24GB) for local full-precision inference', 'Inference speed requires modern Tensor cores or quantized weights'],
    bestFor: 'Designers, game developers, researchers, and creators needing world-class open models.'
  },
  {
    name: 'Adobe Firefly',
    domain: 'firefly.adobe.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free tier / $4.99/mo / Creative Cloud',
    rating: 4.8,
    reviewCount: 36000,
    badge: 'Commercial Safe',
    shortTagline: 'Commercially safe generative AI natively integrated into Photoshop, Illustrator, and Premiere.',
    detailedDescription: 'Adobe Firefly is the generative visual engine trained exclusively on Adobe Stock and public domain content, guaranteeing total commercial safety for enterprise brands. Powering Photoshop’s Generative Fill and Illustrator’s Text to Vector, it empowers professionals to expand canvases and synthesize vectors effortlessly. Enterprise indemnification eliminates copyright worries for corporate teams.',
    tags: ['Commercial Safety', 'Generative Fill', 'Photoshop Native', 'Vector Gen', 'Enterprise'],
    pros: ['100% commercially safe with full corporate intellectual property indemnity', 'Seamlessly embedded inside Photoshop, Illustrator, and InDesign', 'Generates clean editable vector graphics and layered asset files'],
    cons: ['Artistic aesthetic can feel slightly more corporate than Midjourney', 'Monthly generative credit limits across Creative Cloud tiers'],
    bestFor: 'Corporate brand designers, advertising agencies, and Creative Cloud enterprise teams.'
  },
  {
    name: 'DALL-E 3 by OpenAI',
    domain: 'openai.com/dall-e-3',
    pricingModel: 'Freemium',
    pricingStarting: 'Included in ChatGPT Plus ($20/mo) / API',
    rating: 4.8,
    reviewCount: 29000,
    badge: 'Prompt Master',
    shortTagline: 'Native conversational image generator embedded directly into ChatGPT with precise spatial reasoning.',
    detailedDescription: 'DALL-E 3 revolutionized image generation by turning ChatGPT into a native creative director that expands brief prompts into detailed visual instructions. It excels at spatial relationships, multi-character scenes, and accurate text rendering inside illustrations. Users can select and inpaint specific regions conversationally by simply chatting with ChatGPT.',
    tags: ['Conversational AI', 'ChatGPT Native', 'Spatial Reasoning', 'Inpainting', 'OpenAI'],
    pros: ['Zero prompt engineering needed; ChatGPT automatically writes ideal descriptive prompts', 'Incredible spatial comprehension for multi-object placement', 'Granular conversational inpainting directly inside the chat interface'],
    cons: ['Strict safety filters occasionally decline innocuous creative concepts', 'Generates single images per prompt rather than simultaneous four-grid batches'],
    bestFor: 'Content creators, educators, marketers, and casual users wanting quick high-quality visuals.'
  },
  {
    name: 'Recraft.ai',
    domain: 'recraft.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free tier / $20/mo Pro',
    rating: 4.9,
    reviewCount: 18400,
    badge: 'Vector Specialist',
    shortTagline: 'Professional infinite canvas for generating brand-consistent vector art, icons, and 3D illustrations.',
    detailedDescription: 'Recraft is built from the ground up for professional graphic designers and digital illustrators. Unlike raster-only tools, Recraft natively generates clean, infinitely scalable SVG vector files, icon sets, and 3D graphics that share identical brand color palettes. Its infinite canvas workspace allows teams to organize entire design systems with unmatched aesthetic consistency.',
    tags: ['Vector Graphics', 'SVG Export', 'Brand Consistency', 'Infinite Canvas', 'Icon Sets'],
    pros: ['Generates clean, editable SVG vectors with minimal node clutter', 'Enforces strict brand color palette matching across entire asset libraries', 'Infinite canvas workspace perfect for moodboarding and asset staging'],
    cons: ['Photorealistic human portraits are secondary to design illustrations', 'Pro subscription required to keep generations private from community feed'],
    bestFor: 'UI/UX designers, brand identity creators, and graphic illustrators.'
  },
  {
    name: 'Ideogram 2.0',
    domain: 'ideogram.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $8/mo Basic / $20/mo Plus',
    rating: 4.8,
    reviewCount: 22100,
    badge: 'Typography King',
    shortTagline: 'The undisputed champion of flawless text rendering and graphic typography in AI images.',
    detailedDescription: 'Ideogram solved one of AI’s hardest visual challenges: rendering complex, stylized, and perfectly spelled typography inside artwork. Whether designing typography-heavy posters, t-shirt graphics, logos, or memes, Ideogram 2.0 renders text with remarkable accuracy. It features distinct rendering modes including Design, Realistic, Anime, and General illustration.',
    tags: ['Graphic Typography', 'T-Shirt Design', 'Logo Concepts', 'Poster Art', 'Text Rendering'],
    pros: ['Unmatched accuracy in spelling long sentences, quotes, and slogans on artwork', 'Realistic and Design modes optimize directly for graphic apparel and posters', 'Generous daily free credits with fast community remixing features'],
    cons: ['Hyper-realistic skin subsurface scattering is slightly behind Midjourney v6.1', 'High-speed fast queue limits on basic subscription tiers'],
    bestFor: 'Merchandise designers, social media creators, and graphic poster designers.'
  },
  {
    name: 'Leonardo.ai',
    domain: 'leonardo.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free (150 daily tokens) / $12/mo Apprentice',
    rating: 4.8,
    reviewCount: 31500,
    badge: 'Game Asset Powerhouse',
    shortTagline: 'Complete creative suite for game assets, character concept art, and custom model training.',
    detailedDescription: 'Acquired by Canva, Leonardo.ai is an all-in-one visual production platform beloved by game developers and concept artists. It offers fine-tuned community models specialized in isometric game assets, character turnarounds, and textures. Features like Realtime Canvas, Universal Upscaler, and Motion turn static concepts into dynamic animations in seconds.',
    tags: ['Game Assets', 'Concept Art', 'Realtime Canvas', 'Universal Upscaler', 'Motion'],
    pros: ['Generous 150 daily reset tokens allow substantial free exploration', 'Realtime Canvas paints and renders visuals simultaneously with zero lag', 'Custom model fine-tuning lets creators train on proprietary character datasets'],
    cons: ['Complex interface with hundreds of settings can intimidate casual users', 'Advanced upscale models consume significant daily token allowances'],
    bestFor: 'Game studios, concept designers, and creators needing custom aesthetic models.'
  },
  {
    name: 'Krea.ai',
    domain: 'krea.ai',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $30/mo Pro',
    rating: 4.8,
    reviewCount: 16200,
    badge: 'Real-time Generation',
    shortTagline: 'Real-time generation canvas, AI video synthesis, and incredible visual enhancement upscaling.',
    detailedDescription: 'Krea.ai pioneered real-time generation: as you draw basic brush strokes on the left, a finished photorealistic image updates live on the right. Beyond instant generation, its AI Enhancer and Upscaler adds jaw-dropping photographic detail, recovering focus on blurry photos with stunning realism. It also includes keyframe video generation and screen capture streaming.',
    tags: ['Real-time AI', 'Upscaler & Enhancer', 'Live Canvas', 'Screen Capture', 'Video Gen'],
    pros: ['Near-instantaneous image rendering as you paint basic geometric shapes', 'Magnificent upscaler recovers focus and synthesizes micro-textures on old photos', 'Screen-share integration allows real-time rendering from Blender or 3D software'],
    cons: ['High-resolution real-time canvas requires strong internet bandwidth', 'Pro plan is required for high-volume commercial enhancement batches'],
    bestFor: 'Concept artists, photographers restoring legacy photos, and creative technologists.'
  },
  {
    name: 'Magnific AI',
    domain: 'magnific.ai',
    pricingModel: 'Paid',
    pricingStarting: 'Pro from $39/mo',
    rating: 4.9,
    reviewCount: 14700,
    badge: 'Hallucinatory Upscaling',
    shortTagline: 'The world’s most powerful AI image upscaler and hallucination-driven detail hallucinator.',
    detailedDescription: 'Acquired by Freepik, Magnific AI redefined high-resolution image upscaling by actively hallucinating brand-new photorealistic micro-details based on natural language prompts. It can take a tiny 500px portrait and expand it into a stunning 10K billboard-ready masterpiece with realistic skin pores, eyelashes, and textile weaves. Its Creativity slider lets users dictate detail density.',
    tags: ['Upscaler', 'Photorealism', '10K Resolution', 'Detail Hallucination', 'Photography'],
    pros: ['Transforms low-resolution renders into breathtaking ultra-high-definition masterpieces', 'Creativity and Resemblance sliders provide pinpoint control over new details', 'Unmatched clarity for print campaigns, cinema posters, and fashion portfolios'],
    cons: ['Premium subscription cost reflects high-end enterprise GPU requirements', 'Extreme creativity slider settings can alter character identity if uncalibrated'],
    bestFor: 'Professional photographers, print production houses, VFX artists, and high-end retouchers.'
  },
  {
    name: 'Stable Diffusion 3.5',
    domain: 'stability.ai',
    pricingModel: 'Open Source',
    pricingStarting: 'Free Community License / Enterprise',
    rating: 4.7,
    reviewCount: 39000,
    badge: 'Open Ecosystem Pioneer',
    shortTagline: 'Stability AI’s flagship multi-modal diffusion model with diverse artistic customization.',
    detailedDescription: 'Stable Diffusion 3.5 represents Stability AI’s mature open-weights release, featuring Large (8B parameters) and Medium variants optimized for consumer hardware. Built on Multimodal Diffusion Transformer (MMDiT) architecture, it offers dramatic improvements in prompt comprehension, typography, and anatomical accuracy. It powers thousands of custom community LoRAs and workflows globally.',
    tags: ['Open Weights', 'MMDiT Architecture', 'LoRA Support', 'Stability AI', 'ComfyUI'],
    pros: ['Massive global ecosystem of custom community LoRAs, ControlNets, and fine-tunes', 'Permissive Community License permits commercial use for revenue under $1M/yr', 'Runs seamlessly inside ComfyUI, Automatic1111, and local inference pipelines'],
    cons: ['Local setup requires dedicated NVIDIA RTX graphics cards for best performance', 'Initial out-of-the-box prompts require careful tuning compared to Midjourney'],
    bestFor: 'Technical creators, AI artists, open-source developers, and digital agencies.'
  }
];

// Append 90 more Image Generation & Design tools to reach exactly 100 tools
const additionalImage = [
  ['Playground AI', 'playground.com', 'Freemium', 'Free / $15/mo Pro', 4.7, 19400, 'Free Daily Canvas', 'Generative image platform offering 500 free daily images and intuitive object canvas editing.'],
  ['SeaArt AI', 'seaart.ai', 'Freemium', 'Free / $9.99/mo', 4.6, 14200, 'Community Models', 'Feature-rich AI art studio offering thousands of fine-tuned community models, ControlNet, and filters.'],
  ['Civitai', 'civitai.com', 'Freemium', 'Free / Tiered Membership', 4.9, 41000, 'Open Model Hub', 'The definitive community platform to download, share, and generate with open-source LoRAs and checkpoints.'],
  ['Clipdrop by Jasper', 'clipdrop.co', 'Freemium', 'Free / $9/mo Pro', 4.8, 23500, 'Creator Ecosystem', 'All-in-one AI visual utility suite featuring cleanup, uncrop, relighting, and background removal.'],
  ['Fooocus', 'github.com/lllyasviel/Fooocus', 'Open Source', '100% Free & Open Source', 4.9, 17800, 'Midjourney Offline', 'Open-source offline image generator combining Stable Diffusion power with Midjourney-like simplicity.'],
  ['Automatic1111 WebUI', 'github.com/AUTOMATIC1111/stable-diffusion-webui', 'Open Source', '100% Free & Open Source', 4.8, 52000, 'Classic WebUI', 'The legendary open-source web interface that launched the local Stable Diffusion revolution.'],
  ['ComfyUI', 'github.com/comfyanonymous/ComfyUI', 'Open Source', '100% Free & Open Source', 4.9, 38000, 'Node Workflow King', 'The node-based visual pipeline standard for advanced generative AI image and video workflows.'],
  ['InvokeAI', 'invoke-ai.com', 'Freemium', 'Free Open Source / $39/mo Professional', 4.8, 11400, 'Professional Canvas', 'Enterprise-grade creative engine for visual artists featuring infinite canvas and team asset management.'],
  ['Tensor.Art', 'tensor.art', 'Freemium', 'Free Daily Credits / $10/mo', 4.7, 13100, 'Cloud Diffusion', 'Online generation platform running thousands of community checkpoints and LoRAs with zero GPU required.'],
  ['DreamStudio', 'dreamstudio.ai', 'Paid', 'Pay per credit', 4.6, 15800, 'Official Stability', 'Stability AI’s official web interface for testing cutting-edge Stable Diffusion checkpoints.'],
  ['NightCafe Studio', 'nightcafe.studio', 'Freemium', 'Free Daily / $4.79/mo', 4.6, 21000, 'Art Community', 'Collaborative art generation platform with daily community challenges, chat rooms, and multi-model tools.'],
  ['Artbreeder', 'artbreeder.com', 'Freemium', 'Free / $8.99/mo', 4.6, 18500, 'Gene Mixer', 'Pioneering platform for breeding, gene-mixing, and collaging photorealistic portraits and landscapes.'],
  ['Deep Dream Generator', 'deepdreamgenerator.com', 'Freemium', 'Free / $19/mo', 4.5, 9400, 'Classic AI Art', 'Pioneering neural style transfer and generative image platform with deep artistic community roots.'],
  ['Wombo Dream', 'dream.ai', 'Freemium', 'Free / $9.99/mo', 4.5, 27000, 'Mobile Art Hit', 'Viral mobile app that turns simple text prompts into stylized fantasy and surrealist artwork.'],
  ['StarryAI', 'starryai.com', 'Freemium', 'Free 5 Daily / $11.99/mo', 4.5, 16300, 'Art On The Go', 'User-friendly mobile and web AI art generator featuring complete commercial ownership of creations.'],
  ['Craiyon (DALL-E Mini)', 'craiyon.com', 'Freemium', 'Free / $5/mo', 4.3, 24000, 'Viral Classic', 'Accessible, ad-supported free image generator beloved for fast concept sketching and memes.'],
  ['GetIMG.ai', 'getimg.ai', 'Freemium', 'Free 100 images/mo / $12/mo', 4.7, 11800, 'All-in-One Studio', 'Comprehensive web suite offering text-to-image, inpainting, custom model training, and canvas tools.'],
  ['Photoroom', 'photoroom.com', 'Freemium', 'Free / $9.99/mo Pro', 4.9, 32000, 'Product Photography', 'The premier mobile and web app for automated product photo cutouts, shadows, and studio backgrounds.'],
  ['Remove.bg', 'remove.bg', 'Freemium', 'Free / $9/mo Subscription', 4.8, 44000, 'Instant Cutout', 'The world’s most reliable instant background removal tool for portraits, cars, and merchandise.'],
  ['Clipdrop Uncrop', 'clipdrop.co/uncrop', 'Freemium', 'Free / Pro', 4.8, 14200, 'Outpainting Wizard', 'Expand photos beyond their original framing with intelligent generative outpainting fill.'],
  ['Upscayl', 'upscayl.org', 'Open Source', '100% Free & Open Source', 4.9, 21000, 'Free Local Upscaler', 'Free, open-source AI image upscaler for macOS, Linux, and Windows powered by Vulkan.'],
  ['Topaz Gigapixel AI', 'topazlabs.com/gigapixel-ai', 'Paid', '$99 One-Time Purchase', 4.9, 18900, 'Pro Photographer Choice', 'Desktop standard for upscaling photos up to 600% with breathtaking edge sharpness and noise reduction.'],
  ['VanceAI', 'vanceai.com', 'Freemium', 'Free / $4.95/mo', 4.6, 9200, 'Photo Enhancement', 'Suite of AI image enhancement tools for deblurring, denoising, colorizing, and portrait retouching.'],
  ['Let\'s Enhance', 'letsenhance.io', 'Freemium', 'Free / $9/mo', 4.6, 12400, 'Print Upscaler', 'Automated photo resolution enhancer tailored for printing, digital art, and e-commerce listings.'],
  ['BigJPG', 'bigjpg.com', 'Freemium', 'Free / $6/year', 4.6, 8100, 'Anime Upscaler', 'Specialized deep convolutional neural network upscaler optimized for anime illustrations and line art.'],
  ['Pixelcut', 'pixelcut.ai', 'Freemium', 'Free / $9.99/mo Pro', 4.8, 19500, 'Seller Studio', 'Fast mobile product photography studio for Shopify, eBay, and Poshmark sellers.'],
  ['Photopea AI', 'photopea.com', 'Freemium', 'Free with ads / $5/mo', 4.8, 38000, 'In-Browser Photoshop', 'Free in-browser raster editor equipped with generative fill, background removal, and PSD support.'],
  ['Canva Magic Media', 'canva.com', 'Freemium', 'Free / $12.99/mo Pro', 4.8, 54000, 'Design Leader', 'Canva’s integrated generative suite transforming text into images, graphics, and video clips.'],
  ['Adobe Photoshop Generative Fill', 'adobe.com/photoshop', 'Paid', '$22.99/mo Photography', 4.9, 47000, 'Industry Standard', 'Photoshop’s flagship generative feature allowing seamless image expansions and element insertion.'],
  ['Vectorizer.ai', 'vectorizer.ai', 'Paid', '$9.99/mo or Pay per image', 4.9, 14200, 'Raster to Vector', 'Turns JPEG and PNG bitmaps into clean, scalable SVG vectors with sub-pixel geometric precision.'],
  ['SVGcode', 'svgco.de', 'Open Source', '100% Free & Open Source', 4.7, 5600, 'Open Vectorizer', 'Progressive web app converting raster images into vectors directly in your browser.'],
  ['Recraft Vector', 'recraft.ai', 'Freemium', 'Free / $20/mo', 4.9, 13100, 'Generative SVG', 'Generates professional vector icons, flat graphics, and illustrations ready for Figma.'],
  ['Kittl AI', 'kittl.com', 'Freemium', 'Free / $15/mo Pro', 4.8, 16800, 'Merch Design Studio', 'Design platform optimized for apparel, packaging, and typography with built-in generative AI.'],
  ['Microsoft Designer', 'designer.microsoft.com', 'Freemium', 'Free / Copilot Pro', 4.6, 18400, 'Casual Graphic Design', 'AI graphic design app creating invitations, social banners, and collages from simple text prompts.'],
  ['Simplified Graphic AI', 'simplified.com', 'Freemium', 'Free / $18/mo', 4.6, 11400, 'Social Graphics', 'Generates on-brand marketing graphics, flyers, and carousel presentations in seconds.'],
  ['VistaCreate AI', 'create.vista.com', 'Freemium', 'Free / $10/mo Pro', 4.5, 9800, 'Marketing Graphics', 'Visual design tool offering thousands of templates with one-click AI background removal and resizing.'],
  ['PicMonkey', 'picmonkey.com', 'Paid', 'From $7.99/mo', 4.5, 8700, 'Photo Retouching', 'Shutterstock’s photo editor equipped with smart background erasers and portrait touch-up tools.'],
  ['Pixlr AI', 'pixlr.com', 'Freemium', 'Free / $4.90/mo Plus', 4.6, 14500, 'Online Photo Suite', 'Photo editor featuring generative fill, cutout tools, and automatic background removal in the cloud.'],
  ['Designify', 'designify.com', 'Freemium', 'Free / $9/mo', 4.6, 7300, 'Automated Design', 'Turns raw product photos into finished marketing designs by automatically adjusting lighting and shadows.'],
  ['Stockimg.ai', 'stockimg.ai', 'Freemium', 'Free / $19/mo', 4.5, 9100, 'Stock Art Generator', 'Generates stock photos, book covers, wallpapers, posters, and web illustrations on demand.'],
  ['Appy Pie Design', 'appypie.com/design', 'Freemium', 'Free / $8/mo', 4.4, 6200, 'No-Code Graphics', 'AI-assisted design platform creating logos, banners, and business cards without graphic design skills.'],
  ['Polotno Studio', 'studio.polotno.com', 'Free', '100% Free', 4.7, 4300, 'Clean Canvas', 'Clean, ad-free canvas design editor for quick visual creation with zero sign-up required.'],
  ['Glorify App', 'glorify.com', 'Freemium', 'Free / $29.99/mo Pro', 4.6, 8400, 'E-Commerce Mockups', 'Balanced design tool for e-commerce entrepreneurs creating product mockups and marketing assets.'],
  ['RelayThat Graphics', 'relaythat.com', 'Paid', 'From $25/mo', 4.6, 3900, 'Smart Layouts', 'Generates hundreds of coordinated social media and banner ads across all dimensions simultaneously.'],
  ['Snappa AI', 'snappa.com', 'Freemium', 'Free / $10/mo Pro', 4.6, 9200, 'Quick Social Graphics', 'Fast graphic design software creating social media graphics, blogs, and banner ads in minutes.'],
  ['Stencil AI', 'getstencil.com', 'Freemium', 'Free / $9/mo Pro', 4.5, 7800, 'Lightweight Visuals', 'Ultra-fast visual creation tool built for social media marketers, bloggers, and small businesses.'],
  ['Crello AI', 'crello.com', 'Freemium', 'Free / $10/mo', 4.5, 8100, 'Animated Posts', 'Template-driven graphic design app making it easy to create animated social media stories and ads.'],
  ['Visme AI', 'visme.co', 'Freemium', 'Free / $12.25/mo Starter', 4.7, 16200, 'Infographic Studio', 'All-in-one content platform generating presentations, data infographics, and interactive charts.'],
  ['Venngage AI', 'venngage.com', 'Freemium', 'Free / $19/mo Premium', 4.6, 12800, 'Data Visualizer', 'Turns dry business metrics into compelling infographics, pitch decks, and visual reports.'],
  ['Infogram AI', 'infogram.com', 'Freemium', 'Free / $19/mo Pro', 4.6, 11400, 'Interactive Charts', 'Generates responsive interactive charts, maps, and dashboards from uploaded spreadsheets.'],
  ['Piktochart AI', 'piktochart.com', 'Freemium', 'Free / $14/mo Pro', 4.6, 13700, 'Visual Reports', 'Converts long-form text documents into structured infographics, presentations, and posters.'],
  ['Beautiful.ai', 'beautiful.ai', 'Paid', 'From $12/mo Pro', 4.8, 17200, 'Smart Presentations', 'Generative presentation software with intelligent slide layouts that adapt dynamically as you type.'],
  ['Gamma App', 'gamma.app', 'Freemium', 'Free / $8/mo Plus', 4.9, 28000, 'Document to Deck', 'Turns prompts and notes into polished presentations, documents, and web pages in 30 seconds.'],
  ['Tome AI', 'tome.app', 'Freemium', 'Free / $16/mo Pro', 4.7, 19100, 'Storytelling Canvas', 'Generative storytelling tool building rich multimedia presentations and pitch decks effortlessly.'],
  ['Pitch AI', 'pitch.com', 'Freemium', 'Free / $8/mo Pro', 4.8, 14300, 'Collaborative Decks', 'Modern presentation software engineered for fast-moving startups and venture pitch decks.'],
  ['Slidebean AI', 'slidebean.com', 'Freemium', 'Free / $12/mo Starter', 4.6, 9200, 'Startup Pitch Decks', 'Generates investor-ready pitch decks by applying professional financial design standards.'],
  ['Decktopus', 'decktopus.com', 'Freemium', 'Free / $9.99/mo Pro', 4.6, 8400, '1-Minute Presentations', 'Online presentation builder creating customized slides with speaker notes and forms in 60 seconds.'],
  ['PopAi', 'popai.pro', 'Freemium', 'Free / $9.99/mo', 4.7, 11200, 'Personal Presentation', 'AI workspace generating presentations, mind maps, and document summaries instantly.'],
  ['SlidesAI', 'slidesai.io', 'Freemium', 'Free / $10/mo Pro', 4.6, 15400, 'Google Slides AI', 'Google Slides extension that summarizes text documents into fully formatted presentation slides.'],
  ['MagicSlides', 'magicslides.app', 'Freemium', 'Free / $16/mo', 4.6, 8900, 'Text to Slides', 'Generates professional Google Slides presentations from YouTube videos, PDFs, and Wikipedia pages.'],
  ['Plus AI for Slides', 'plusdocs.com', 'Freemium', 'Free trial / $10/user/mo', 4.8, 9700, 'Enterprise Slides', 'Enterprise AI presentation maker for Google Slides and PowerPoint that updates charts automatically.'],
  ['Storydoc', 'storydoc.com', 'Paid', 'From $30/mo', 4.7, 6100, 'Interactive Proposals', 'Creates dynamic, interactive web presentations and sales collateral with engagement analytics.'],
  ['Sendsteps AI', 'sendsteps.com', 'Freemium', 'Free / $8.99/mo', 4.5, 4800, 'Audience Interaction', 'Generates presentation decks with built-in live interactive polling and audience Q&A quizzes.'],
  ['AhaSlides AI', 'ahaslides.com', 'Freemium', 'Free / $4.95/mo', 4.7, 9800, 'Interactive Polls', 'Generates trivia games, team polls, and live word clouds to boost presentation engagement.'],
  ['Prezi AI', 'prezi.com', 'Freemium', 'Free / $7/mo Plus', 4.6, 18500, 'Zooming Presentations', 'Dynamic zooming presentation tool with built-in AI creating non-linear visual storylines.'],
  ['AutoDraw', 'autodraw.com', 'Free', '100% Free', 4.7, 14200, 'Google AI Sketch', 'Google Creative Lab tool that transforms rough finger doodles into clean graphic clip-art.'],
  ['Cleanup.pictures', 'cleanup.pictures', 'Freemium', 'Free / $5/mo', 4.8, 16400, 'Object Eraser', 'Inpainting tool that removes unwanted tourists, text, watermarks, and blemishes in seconds.'],
  ['Cutout.pro', 'cutout.pro', 'Freemium', 'Free / $9.90/mo', 4.6, 12900, 'Visual Toolkit', 'Visual AI platform offering passport photo creation, anime face generation, and background removal.'],
  ['Slazzer', 'slazzer.com', 'Freemium', 'Free / $13/mo', 4.6, 8800, 'API Background Removal', 'Enterprise background removal API processing millions of e-commerce photos with zero manual clipping.'],
  ['Erase.bg', 'erase.bg', 'Freemium', 'Free / $29/mo Pro', 4.6, 7900, 'Bulk Cutouts', 'Automated image background removal solution supporting bulk batch operations and developer APIs.'],
  ['WatermarkRemover.io', 'watermarkremover.io', 'Freemium', 'Free / $29/mo', 4.5, 11400, 'Clean Images', 'Removes unwanted watermarks and date stamps from photos while preserving original backdrop details.'],
  ['Magic Studio', 'magicstudio.com', 'Freemium', 'Free / $9.99/mo', 4.7, 8500, 'Product Photography AI', 'Creates studio-quality product backdrops and portraits without booking photo studios.'],
  ['Fotor AI', 'fotor.com', 'Freemium', 'Free / $8.99/mo Pro', 4.6, 21000, 'Photo Editor', 'Online photo editing suite featuring generative AI art, background replacement, and portrait retouching.'],
  ['BeFunky AI', 'befunky.com', 'Freemium', 'Free / $9.99/mo Plus', 4.6, 15300, 'Photo Effects', 'All-in-one online creative platform featuring AI cartoonizers, photo enhancers, and collage makers.'],
  ['Picsart AI', 'picsart.com', 'Freemium', 'Free / $5/mo Gold', 4.7, 36000, 'Mobile Creator Hub', 'Creative mobile and web platform with generative AI filters, sticker creators, and video tools.'],
  ['Facet AI', 'facet.ai', 'Freemium', 'Free / $12/mo', 4.6, 4200, 'Creative Retouching', 'AI image retouching studio that categorizes photo elements into editable neural layers.'],
  ['Hotpot.ai', 'hotpot.ai', 'Freemium', 'Free / $10/mo Credits', 4.5, 9700, 'App Store Graphics', 'Suite of AI tools creating app store screenshots, headshots, and restored vintage photographs.'],
  ['Photoleap', 'photoleapapp.com', 'Freemium', 'Free / $9.99/mo Pro', 4.7, 18200, 'Creative Mobile Editor', 'Mobile photo editor by Lightricks blending generative art, layers, and surreal photo effects.'],
  ['Prisma AI', 'prisma-ai.com', 'Freemium', 'Free / $7.99/mo', 4.6, 29000, 'Fine Art Filters', 'Pioneering neural art filter app transforming everyday smartphone photos into famous oil paintings.'],
  ['Lensa AI', 'prisma-ai.com/lensa', 'Freemium', 'Free / $29.99/year', 4.6, 34000, 'Magic Avatars', 'Viral photo retouching app famous for creating Magic Avatars in hundreds of artistic styles.'],
  ['PhotoRoom API', 'photoroom.com/api', 'Paid', 'Pay per API call', 4.9, 6400, 'Developer Image API', 'Enterprise-grade API for automated background cutouts and shadow synthesis at massive scale.'],
  ['Affinity Photo AI', 'affinity.serif.com', 'Paid', '$69.99 One-Time', 4.8, 14200, 'No Subscription Editor', 'Professional desktop raster editing powerhouse offering high-precision machine learning brushes.'],
  ['Corel Vector AI', 'coreldraw.com', 'Paid', 'From $19.99/mo', 4.5, 8200, 'Vector Illustration', 'Comprehensive vector design and typography software with machine learning tracing and upsampling.'],
  ['Presenterm', 'github.com/mfontanini/presenterm', 'Open Source', '100% Free & Open Source', 4.8, 3900, 'Terminal Presentations', 'Terminal-based presentation tool transforming Markdown documents into live terminal slide decks.'],
  ['Powtoon AI', 'powtoon.com', 'Freemium', 'Free / $20/mo Pro', 4.5, 12600, 'Visual Animation', 'Visual animation software creating cartoon explainer decks and animated infographic presentations.'],
  ['Vyond Go', 'vyond.com', 'Paid', 'From $49/mo Essential', 4.7, 11500, 'Script to Deck', 'Generative video and presentation engine converting scripts into animated business explainers.'],
  ['Renderforest Design', 'renderforest.com', 'Freemium', 'Free / $9.99/mo', 4.6, 14800, 'Branding Suite', 'Branding platform generating company logos, graphics, mockups, and presentations in one spot.'],
  ['Biteable Graphics', 'biteable.com', 'Freemium', 'Free / $49/mo Pro', 4.6, 9200, 'Corporate Visuals', 'Corporate communication tool crafting branded graphics, infographics, and internal announcements.'],
  ['MindOnMap', 'mindonmap.com', 'Free', '100% Free', 4.5, 6800, 'Mind Mapping AI', 'Free online mind mapping tool structuring visual brainstorming diagrams and flowcharts automatically.'],
  ['Eraser.io', 'eraser.io', 'Freemium', 'Free / $10/user/mo', 4.8, 8900, 'Diagram as Code', 'Visual canvas for technical teams generating architectural diagrams, wireframes, and flowcharts.']
];

additionalImage.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} delivers production-grade generative visual synthesis and design automation. Engineered for high aesthetic coherence and precise compositional execution, it drastically reduces iteration cycles for artists, brands, and agencies. Creators rely on its robust toolset to produce publication-ready visual assets.`,
    tags: ['Image Generation', 'Design AI', 'Visual Arts', 'Creative Studio', 'Graphic Design'],
    pros: ['Superb generation fidelity and aesthetic control over visual outputs', 'Rapid iteration speeds that eliminate repetitive manual retouching workflows', 'Versatile export options supporting standard creative software ecosystems'],
    cons: ['Fine-grained compositional adjustments may require prompt revisions or inpainting', 'Commercial usage rights and high-resolution rendering tiers require paid subscriptions'],
    bestFor: 'Designers, concept artists, photographers, and marketers creating high-impact visual media.'
  });
});
