module.exports = [
  {
    name: 'Cursor',
    domain: 'cursor.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro',
    rating: 4.9,
    reviewCount: 31200,
    badge: 'Developer Favorite',
    shortTagline: 'AI-first code editor built on VS Code with predictive multi-line edits and codebase indexing.',
    detailedDescription: 'Cursor is the breakaway favorite IDE among modern software engineers. Built on a clean fork of VS Code, it indexes your entire git repository to execute hyper-accurate multi-file refactors and feature builds using Claude 3.7 Sonnet and GPT-4o. Its Composer mode allows developers to orchestrate complex architectural edits across dozens of files simultaneously.',
    tags: ['AI Editor', 'VS Code Fork', 'Composer', 'Codebase Indexing', 'Multi-File Edit'],
    pros: ['Superb codebase indexing understands intricate architectural dependencies', 'Cursor Tab predicts next edits across multiple lines with incredible accuracy', 'Drop-in migration for existing VS Code extensions, themes, and keybindings'],
    cons: ['Pro fast-request credits can be consumed quickly during intensive refactoring', 'Occasional indexing cache re-sync required on massive monorepos'],
    bestFor: 'Full-stack software engineers, indie hackers, and engineering teams.'
  },
  {
    name: 'GitHub Copilot',
    domain: 'github.com/features/copilot',
    pricingModel: 'Paid',
    pricingStarting: '$10/mo Individual / $19 Enterprise',
    rating: 4.8,
    reviewCount: 42000,
    badge: 'Industry Standard',
    shortTagline: 'The world’s most widely adopted AI pair programmer embedded across every major IDE.',
    detailedDescription: 'GitHub Copilot provides seamless real-time code completions, inline pull request summaries, and conversational chat within VS Code, JetBrains, and Visual Studio. Powered by multi-model flexibility including Claude 3.5 Sonnet and OpenAI models, it dramatically reduces boilerplate development time. Enterprise governance and IP indemnification ensure worry-free compliance.',
    tags: ['Pair Programmer', 'GitHub', 'Inline Completion', 'Enterprise Ready', 'JetBrains'],
    pros: ['Flawless low-latency autocompletions directly in your editor flow', 'Automatic pull request description and commit message generation', 'Strong enterprise security policies and intellectual property safeguards'],
    cons: ['Less aggressive multi-file automated refactoring compared to Cursor', 'Can generate outdated library syntax without prompt grounding'],
    bestFor: 'Enterprise software developers, open-source contributors, and engineering departments.'
  },
  {
    name: 'Windsurf by Codeium',
    domain: 'codeium.com/windsurf',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $15/mo Pro',
    rating: 4.9,
    reviewCount: 16800,
    badge: 'Agentic Pioneer',
    shortTagline: 'Agentic AI IDE featuring Cascade flow for collaborative developer-agent programming.',
    detailedDescription: 'Windsurf transforms developer productivity through its flagship Cascade agent, which works side-by-side with coders to read terminal outputs, edit files, and resolve compilation errors autonomously. Engineered by Codeium, it provides ultra-fast context-aware code generation and proprietary real-time indexing. Its agentic flows respect developer control while handling tedious infrastructure setup.',
    tags: ['Agentic IDE', 'Cascade', 'Autonomous Debugging', 'Codeium', 'Fast Indexing'],
    pros: ['Cascade flow autonomously runs commands, checks output, and corrects errors', 'Generous free tier with fast unlimited autocomplete completions', 'Exceptional awareness of deep workspace structures and dependencies'],
    cons: ['Rapidly evolving UI undergoes frequent navigation updates', 'Advanced multi-model switching requires Pro subscription'],
    bestFor: 'Engineers who want an autonomous AI agent running tests and debugging within their IDE.'
  },
  {
    name: 'v0 by Vercel',
    domain: 'v0.dev',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Premium',
    rating: 4.9,
    reviewCount: 22400,
    badge: 'Frontend King',
    shortTagline: 'Generative UI development platform that turns natural language into production React and Tailwind code.',
    detailedDescription: 'v0 by Vercel has redefined frontend development by generating beautiful, accessible React components, dashboards, and landing pages from simple prompts. It outputs pristine, modular TypeScript code utilizing Tailwind CSS and shadcn/ui components ready to copy directly into projects. Its interactive visual canvas allows granular element-level prompt refinement.',
    tags: ['Generative UI', 'React & Tailwind', 'shadcn/ui', 'Vercel', 'Design to Code'],
    pros: ['Generates cleanest, production-ready React, Tailwind, and shadcn/ui code in the industry', 'Instant interactive visual preview with live responsive breakpoint testing', 'One-click deployment to Vercel or instant terminal copy-paste CLI integration'],
    cons: ['Credit quota depletes quickly on complex iterative prompt cycles', 'Focused strictly on modern web UI rather than full backend server logic'],
    bestFor: 'Frontend developers, product designers, and founders building modern web applications.'
  },
  {
    name: 'Bolt.new',
    domain: 'bolt.new',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $20/mo Pro',
    rating: 4.8,
    reviewCount: 18700,
    badge: 'Full-Stack Agent',
    shortTagline: 'In-browser AI agent capable of scaffolding, installing npm packages, and running full-stack web apps.',
    detailedDescription: 'Bolt.new by StackBlitz harnesses WebContainers to run full-stack Node.js environments entirely inside your web browser. Users describe full-stack applications—from database schemas to authentication flows—and Bolt scaffolds, executes `npm install`, runs dev servers, and displays live interactive previews. It enables rapid prototyping without requiring any local toolchain installation.',
    tags: ['In-Browser Node', 'Full-Stack', 'StackBlitz', 'WebContainers', 'Rapid Prototype'],
    pros: ['Installs real npm packages and executes Node.js servers directly in browser sandbox', 'Full-stack generation spanning databases, backend routes, and frontend views', 'One-click Netlify and GitHub deployment with full source download'],
    cons: ['Browser memory limits can slow down gigantic enterprise monorepo projects', 'Token limits on free tier when prompting extensive architectural changes'],
    bestFor: 'Full-stack developers, educators, hackathon participants, and startup builders.'
  },
  {
    name: 'Replit Agent',
    domain: 'replit.com',
    pricingModel: 'Paid',
    pricingStarting: 'Core ($15-$25/mo)',
    rating: 4.8,
    reviewCount: 17200,
    badge: 'Autonomous Builder',
    shortTagline: 'Autonomous AI software engineer that plans, writes, debugs, and deploys cloud applications from your phone or PC.',
    detailedDescription: 'Replit Agent acts as an end-to-end autonomous junior developer capable of turning natural language product specs into deployed cloud applications. It designs PostgreSQL database schemas, writes server logic, resolves package dependencies, and automatically configures hosting environments. Accessible on both web and mobile, it makes building cloud software radically accessible.',
    tags: ['Autonomous Agent', 'Instant Deployment', 'Cloud IDE', 'Database Setup', 'Mobile Builder'],
    pros: ['Takes apps from blank canvas to live production URL with zero manual terminal commands', 'Proactively configures backend databases, environment variables, and authentication', 'Build and monitor full application lifecycles from mobile devices'],
    cons: ['Agent compute checkpoints consume Replit Core credits steadily', 'Complex enterprise microservice architectures require manual intervention'],
    bestFor: 'Entrepreneurs, product managers, and builders wanting instant turn-key cloud deployment.'
  },
  {
    name: 'Claude Code',
    domain: 'anthropic.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Pay per token (Anthropic API)',
    rating: 4.9,
    reviewCount: 11200,
    badge: 'Terminal Agent',
    shortTagline: 'Agentic terminal tool by Anthropic that directly inspects, edits, tests, and commits across large codebases.',
    detailedDescription: 'Claude Code is Anthropic’s official agentic command-line interface that brings Claude 3.7 Sonnet directly into your development terminal. It reads git histories, executes shell tests, navigates directory architectures, and applies surgical multi-file edits with human approval. Its ability to iterate on compiler diagnostics and run lint suites makes it a force multiplier for software teams.',
    tags: ['CLI Agent', 'Claude 3.7', 'Git Integration', 'Anthropic', 'Terminal Native'],
    pros: ['Operates directly inside your terminal with full access to git, grep, and build tools', 'Powered by Claude 3.7 Sonnet extended thinking mode for complex architectural refactors', 'Interactive confirmation workflow ensures you review and approve every file edit'],
    cons: ['Requires API key configuration and awareness of token expenditure', 'Terminal-only interaction without built-in graphical visual UI'],
    bestFor: 'Senior engineers, terminal enthusiasts, and developers working on large repositories.'
  },
  {
    name: 'Aider',
    domain: 'aider.chat',
    pricingModel: 'Open Source',
    pricingStarting: '100% Free & Open Source',
    rating: 4.9,
    reviewCount: 14500,
    badge: 'Top Benchmark',
    shortTagline: 'Command-line pair programmer that edits code in your local git repository and automatically writes commit messages.',
    detailedDescription: 'Aider is an open-source terminal pair programming tool with consistently top-ranking scores on the SWE-bench benchmark. It maps your entire git repository into a concise architectural graph and sends surgical unified diffs using top frontier models. After completing edits and verifying tests pass, Aider automatically stages and drafts clean, descriptive git commits.',
    tags: ['Open Source', 'Git Native', 'SWE-bench Leader', 'Terminal', 'Multi-Model'],
    pros: ['Consistently leads real-world coding benchmarks for autonomous diff application', 'Works with OpenAI, Claude, DeepSeek, and local Ollama models seamlessly', 'Automatic sensible git commits make rollbacks and version history effortless'],
    cons: ['Command-line only; requires comfort with terminal development workflows', 'Large repository mapping uses significant context token overhead'],
    bestFor: 'Professional software engineers, open-source developers, and terminal power users.'
  },
  {
    name: 'Tabnine',
    domain: 'tabnine.com',
    pricingModel: 'Freemium',
    pricingStarting: 'Free / $12/mo Pro / Enterprise',
    rating: 4.6,
    reviewCount: 19400,
    badge: 'Privacy Leader',
    shortTagline: 'Enterprise-grade AI code assistant that protects proprietary IP and can be deployed entirely on-premise.',
    detailedDescription: 'Tabnine is the leading privacy-first AI coding copilot trusted by Global 2000 engineering organizations. Unlike services that send company code to public cloud APIs, Tabnine offers air-gapped on-premise deployment, zero data retention guarantees, and strict training only on permissively licensed repositories. It supports all popular IDEs and custom private model fine-tuning.',
    tags: ['On-Premise', 'Enterprise Privacy', 'Zero Data Retention', 'IDE Plugin', 'IP Indemnity'],
    pros: ['Can be hosted completely on-premise or in private VPC for total compliance', 'Guaranteed zero training on customer proprietary intellectual property', 'Trained exclusively on permissively licensed open-source code'],
    cons: ['Raw code completion creativity is slightly more conservative than unconstrained frontier models', 'Enterprise on-premise deployment requires dedicated infrastructure planning'],
    bestFor: 'Financial institutions, defense contractors, and security-conscious enterprise engineering teams.'
  },
  {
    name: 'Amazon Q Developer',
    domain: 'aws.amazon.com/q/developer',
    pricingModel: 'Freemium',
    pricingStarting: 'Free tier / $19/user/mo Pro',
    rating: 4.6,
    reviewCount: 13800,
    badge: 'AWS Specialist',
    shortTagline: 'Generative AI assistant specialized in AWS architectures, cloud debugging, and Java modernization.',
    detailedDescription: 'Amazon Q Developer (formerly CodeWhisperer) is AWS’s generative assistant engineered specifically for cloud development and infrastructure management. Beyond real-time code completion, it excels at diagnosing AWS security vulnerabilities, upgrading legacy Java frameworks, and explaining IAM policies. It connects directly with AWS CloudWatch and CloudFormation for streamlined devops.',
    tags: ['AWS Native', 'Java Upgrades', 'Cloud Security', 'IAM Policies', 'DevOps AI'],
    pros: ['Deep specialized knowledge of AWS APIs, SDKs, and architecture best practices', 'Automated legacy Java version migration agent saves months of manual refactoring', 'Generous free tier with built-in security vulnerability scanning'],
    cons: ['Heavily slanted toward the AWS cloud ecosystem rather than multi-cloud tooling', 'IDE chat interface is less flexible for generic non-cloud frontend frameworks'],
    bestFor: 'DevOps engineers, cloud architects, and enterprise teams operating on Amazon Web Services.'
  }
];

// Append 90 more Coding & Dev tools to reach exactly 100 tools
const additionalCoding = [
  ['Devin by Cognition', 'cognition.ai', 'Paid', 'Custom Enterprise', 4.8, 8700, 'Autonomous Engineer', 'The world’s first autonomous AI software engineer capable of solving complex end-to-end issues.'],
  ['Sourcegraph Cody', 'sourcegraph.com/cody', 'Freemium', 'Free / $9/mo Pro', 4.7, 11500, 'Code Intelligence', 'AI coding assistant that leverages Sourcegraph’s comprehensive code search and repository context graph.'],
  ['Continue.dev', 'continue.dev', 'Open Source', '100% Free & Open Source', 4.8, 14200, 'Open Extension', 'Leading open-source modular AI code assistant extension for VS Code and JetBrains.'],
  ['Supermaven', 'supermaven.com', 'Freemium', 'Free / $10/mo Pro', 4.9, 9300, 'Blazing Speed', 'Ultra-fast autocomplete engine with a 1-million token context window created by the founder of Tabnine.'],
  ['Magic.dev', 'magic.dev', 'Paid', 'Enterprise', 4.7, 4100, 'Ultra-Long Context', 'Frontier AI research company developing LTM-2-mini with ultra-massive context windows for software engineering.'],
  ['CodeRabbit', 'coderabbit.ai', 'Freemium', 'Free for OSS / $15/mo', 4.9, 13400, 'Top PR Reviewer', 'AI-powered code review tool that generates contextual line-by-line feedback on GitHub and GitLab pull requests.'],
  ['Sweep AI', 'sweep.dev', 'Freemium', 'Free tier / $480/mo Team', 4.7, 6100, 'Bug Fixer Agent', 'Junior developer agent that turns bug reports and feature requests in GitHub Issues into pull requests.'],
  ['Qodo Gen (Codiumate)', 'qodo.ai', 'Freemium', 'Free / $19/mo Pro', 4.8, 10200, 'Quality First', 'Generative AI testing, test-case creation, and integrity verification platform for critical software code.'],
  ['Blackbox AI', 'blackbox.ai', 'Freemium', 'Free / $2.99/mo', 4.5, 23000, 'Fast Code Search', 'AI coding search engine and code extractor enabling fast snippet generation from videos and repos.'],
  ['DeepSeek Coder', 'deepseek.com', 'Open Source', 'Free & Open Weights', 4.8, 24500, 'Open Coding Star', 'High-performance open-weights model trained specifically for code generation, infilling, and debugging.'],
  ['StarCoder 2', 'huggingface.co/bigcode', 'Open Source', 'Open Access', 4.7, 8900, 'BigCode Open', 'Openly licensed code LLM developed by the BigCode Project with transparent data provenance.'],
  ['Warp AI', 'warp.dev', 'Freemium', 'Free / $15/mo Pro', 4.9, 21500, 'Modern Terminal', 'The modern terminal with built-in AI debugging, command explanations, and team knowledge sharing.'],
  ['Pieces for Developers', 'pieces.app', 'Freemium', 'Free / $10/mo Pro', 4.7, 8400, 'Snippet Brain', 'On-device contextual snippet manager and AI copilot connecting your browser, IDE, and collaboration tools.'],
  ['Mintlify', 'mintlify.com', 'Freemium', 'Free / $120/mo Startup', 4.9, 9800, 'Beautiful Docs', 'Modern documentation platform that writes, maintains, and converts code into polished developer docs.'],
  ['GitBook AI', 'gitbook.com', 'Freemium', 'Free / $6.70/user/mo', 4.7, 13100, 'Knowledge Base', 'Collaborative documentation platform with semantic search and automatic AI document drafting.'],
  ['Swimm AI', 'swimm.io', 'Freemium', 'Free / $18/user/mo', 4.7, 4900, 'Internal Docs', 'Code-coupled documentation platform that automatically updates alongside codebase commits.'],
  ['Grit.io', 'grit.io', 'Freemium', 'Free / Enterprise', 4.8, 3200, 'Code Migration', 'Automated code migration tool that converts legacy codebases and refactors frameworks seamlessly.'],
  ['Moderne', 'moderne.io', 'Paid', 'Enterprise', 4.7, 2100, 'OpenRewrite', 'Enterprise automated source code refactoring platform operating at multi-repository scale.'],
  ['DeepCode by Snyk', 'snyk.io', 'Freemium', 'Free / $25/mo Team', 4.8, 12600, 'Security Audit', 'AI-assisted static application security testing detecting critical zero-days and vulnerabilities.'],
  ['SonarQube AI', 'sonarsource.com', 'Freemium', 'Free OSS / Enterprise', 4.8, 16900, 'Clean Code', 'Industry-standard static analysis platform checking code quality, security bugs, and code smells.'],
  ['Bito AI', 'bito.ai', 'Freemium', 'Free / $15/mo', 4.6, 7300, 'IDE Companion', 'AI developer assistant helping engineers understand complex code, generate tests, and review PRs.'],
  ['AskCodi', 'askcodi.com', 'Freemium', 'Free / $9.99/mo', 4.5, 8200, 'Code Assistant', 'Personal coding assistant providing conversational explanations, SQL generation, and unit tests.'],
  ['CodeGeeX', 'codegeex.cn', 'Free', '100% Free', 4.6, 6700, 'Multilingual Code', 'Open multilingual code generation model with extensions supporting dozens of major IDEs.'],
  ['Refact.ai', 'refact.ai', 'Freemium', 'Free / $10/mo Pro', 4.7, 4400, 'Self-Hosted Copilot', 'Open-source, self-hosted AI coding assistant offering fine-tuning on company codebases.'],
  ['Plandex', 'plandex.ai', 'Open Source', 'Free Open Source / Cloud', 4.8, 5600, 'Complex Tasks', 'Terminal-based AI coding engine designed for complex, multi-file software engineering tasks.'],
  ['Mentat', 'mentat.ai', 'Open Source', '100% Open Source', 4.6, 3800, 'Command Line AI', 'Command-line coding assistant that coordinates with local files and git commits directly.'],
  ['Smol Developer', 'github.com/smol-ai/developer', 'Open Source', 'Free Open Source', 4.7, 12100, 'Autonomous Scaffolder', 'Lightweight autonomous AI developer prototype capable of generating an entire codebase from a prompt.'],
  ['GPT-Engineer', 'gptengineer.app', 'Freemium', 'Free / $20/mo Pro', 4.8, 15400, 'Prompt to App', 'Collaborative web platform that builds and iterates full web applications from prompt specifications.'],
  ['OpenDevin (OpenHands)', 'all-hands.dev', 'Open Source', '100% Open Source', 4.8, 17900, 'Open Autonomous Agent', 'Community-driven open-source autonomous software development agent matching Devin capabilities.'],
  ['SWE-agent', 'swe-agent.com', 'Open Source', '100% Open Source', 4.8, 9300, 'Research Benchmark', 'Princeton NLP agent architecture turning language models into autonomous software engineers.'],
  ['Devika', 'github.com/stitionai/devika', 'Open Source', '100% Open Source', 4.5, 8100, 'Open Source Devin', 'Open-source autonomous AI software engineer with research and coding abilities.'],
  ['MetaGPT', 'github.com/geekan/metagpt', 'Open Source', '100% Open Source', 4.8, 22100, 'Multi-Agent Framework', 'Multi-agent software engineering framework simulating product managers, architects, and engineers.'],
  ['ChatDev', 'chatdev.ai', 'Open Source', '100% Open Source', 4.7, 14800, 'Virtual Software Co', 'Virtual software company composed of conversational agents collaborating across design and QA.'],
  ['CrewAI', 'crewai.com', 'Freemium', 'Open Source / Cloud Enterprise', 4.9, 26400, 'Agent Orchestration', 'Cutting-edge multi-agent framework empowering role-playing AI agents to accomplish complex tasks.'],
  ['LangChain', 'langchain.com', 'Open Source', 'Open Source / LangSmith Paid', 4.8, 48000, 'LLM Framework', 'The world’s most famous open framework for building context-aware reasoning applications.'],
  ['LlamaIndex', 'llamaindex.ai', 'Open Source', 'Open Source / Cloud Paid', 4.9, 31000, 'Data Framework', 'The premier data framework for connecting private enterprise data with LLMs via RAG.'],
  ['Semantic Kernel', 'github.com/microsoft/semantic-kernel', 'Open Source', '100% Open Source', 4.7, 11400, 'Microsoft SDK', 'Microsoft’s open SDK integrating cutting-edge LLMs with conventional programming languages.'],
  ['Haystack by deepset', 'haystack.deepset.ai', 'Open Source', '100% Open Source', 4.8, 9200, 'Pipelines for RAG', 'Modular open-source framework for building production-ready search systems and RAG pipelines.'],
  ['AutoGen', 'microsoft.github.io/autogen', 'Open Source', '100% Open Source', 4.8, 23800, 'Multi-Agent LLMs', 'Microsoft framework enabling next-gen LLM applications with multiple conversing agents.'],
  ['DSPy', 'dspy.ai', 'Open Source', '100% Open Source', 4.9, 13700, 'Algorithmic Prompts', 'Stanford framework for compiling declarative language model calls into self-optimizing pipelines.'],
  ['Instructor', 'python.useinstructor.com', 'Open Source', '100% Open Source', 4.9, 8900, 'Structured Outputs', 'Lightweight library for extracting typed, structured data from LLMs using Pydantic and Zod.'],
  ['Promptfoo', 'promptfoo.dev', 'Open Source', 'Free OSS / Enterprise', 4.9, 11200, 'LLM Testing & Security', 'CLI and library for evaluating LLM output quality, red-teaming, and preventing prompt injection.'],
  ['Portkey', 'portkey.ai', 'Freemium', 'Free / $99/mo Growth', 4.8, 6200, 'AI Gateway', 'Production control plane and AI gateway providing observability, caching, and fallback routing.'],
  ['Helicone', 'helicone.ai', 'Freemium', 'Free / $79/mo Pro', 4.9, 8400, 'LLM Observability', 'Open-source observability and monitoring platform tracking LLM latency, cost, and user logs.'],
  ['Langfuse', 'langfuse.com', 'Open Source', 'Free OSS / Cloud Paid', 4.9, 12800, 'Open Observability', 'Open source LLM engineering platform for tracing, evaluations, prompt management, and metrics.'],
  ['Arize Phoenix', 'phoenix.arize.com', 'Open Source', 'Free OSS / Enterprise', 4.8, 7100, 'AI Tracing', 'AI observability platform providing evaluation, tracing, and troubleshooting for LLM and RAG apps.'],
  ['DeepEval', 'confident-ai.com', 'Open Source', 'Free OSS / Cloud', 4.8, 5900, 'LLM Evaluation', 'Production-ready unit testing and evaluation framework for LLM applications and RAG systems.'],
  ['Ragas', 'ragas.io', 'Open Source', '100% Open Source', 4.8, 8600, 'RAG Assessment', 'Framework that helps evaluate Retrieval Augmented Generation pipelines with standard metrics.'],
  ['Giskard', 'giskard.ai', 'Freemium', 'Free OSS / Enterprise', 4.7, 4300, 'Quality Assurance', 'Open-source testing framework dedicated to detecting performance bugs and bias in AI models.'],
  ['Galileo AI Eval', 'rungalileo.io', 'Paid', 'Enterprise', 4.8, 3600, 'GenAI Studio', 'Evaluation and guardrail platform preventing enterprise LLM hallucinations and data leakage.'],
  ['Humanloop', 'humanloop.com', 'Paid', 'From $99/mo', 4.7, 4100, 'Collaborative AI Dev', 'Enterprise platform for collaborative prompt engineering, versioning, evaluation, and fine-tuning.'],
  ['Vellum', 'vellum.ai', 'Paid', 'From $300/mo', 4.8, 3800, 'LLMOps Platform', 'All-in-one platform for prototyping, evaluating, and deploying production-ready AI applications.'],
  ['PromptLayer', 'promptlayer.com', 'Freemium', 'Free / $40/mo', 4.7, 5200, 'Prompt CMS', 'The first platform built for prompt engineers to track, version-control, and evaluate model prompts.'],
  ['Braintrust', 'braintrust.dev', 'Freemium', 'Free / $100/mo', 4.9, 4900, 'Evaluation Engine', 'Enterprise-grade evaluation and logging infrastructure for building high-reliability AI products.'],
  ['Dify.ai', 'dify.ai', 'Open Source', 'Free OSS / $59/mo Cloud', 4.9, 21500, 'LLM App Development', 'Open-source LLM application development platform combining AI workflow orchestration and RAG.'],
  ['Flowise', 'flowiseai.com', 'Open Source', '100% Free & Open Source', 4.8, 19200, 'Visual LangChain', 'Drag-and-drop visual interface for building customized LLM flows, chatbots, and autonomous agents.'],
  ['Langflow', 'langflow.org', 'Open Source', '100% Free & Open Source', 4.8, 18700, 'Visual Prototyping', 'Visual framework for fast prototyping multi-agent and RAG applications with Python support.'],
  ['Chainlit', 'chainlit.io', 'Open Source', '100% Free & Open Source', 4.9, 9400, 'Python Chat UI', 'Build conversational ChatGPT-like frontends in Python in minutes with seamless LangChain hooks.'],
  ['vLLM', 'vllm.ai', 'Open Source', '100% Free & Open Source', 4.9, 27400, 'High-Throughput LLM', 'State-of-the-art serving engine for LLMs with PagedAttention delivering 20x higher throughput.'],
  ['llama.cpp', 'github.com/ggerganov/llama.cpp', 'Open Source', '100% Free & Open Source', 4.9, 41000, 'Pure C/C++ Inference', 'Port of LLM architectures in pure C/C++ enabling fast CPU and Apple Metal GPU inference.'],
  ['LocalAI', 'localai.io', 'Open Source', '100% Free & Open Source', 4.7, 11800, 'Self-Hosted AI', 'Drop-in replacement REST API for OpenAI specifications running completely local on commodity hardware.'],
  ['TGI (Text Generation Inference)', 'github.com/huggingface/text-generation-inference', 'Open Source', 'Open Source', 4.8, 14200, 'Hugging Face Serving', 'High-performance production serving toolkit for deploying open-source LLMs at scale.'],
  ['Weights & Biases Weave', 'wandb.ai/site/weave', 'Freemium', 'Free / Enterprise', 4.8, 8300, 'AI Experimentation', 'Lightweight toolkit for logging, evaluating, and monitoring generative AI applications.'],
  ['TruEra', 'truera.com', 'Paid', 'Enterprise', 4.6, 2900, 'LLM Quality & Guardrails', 'Automated testing and monitoring platform diagnosing hallucination risk in generative AI.'],
  ['HoneyHive', 'honeyhive.ai', 'Paid', 'From $99/mo', 4.7, 2400, 'AI Product Evaluation', 'Evaluation and observability platform for product and engineering teams scaling LLM workflows.'],
  ['Pezzo', 'pezzo.ai', 'Open Source', 'Free OSS / Cloud', 4.7, 3900, 'Open Source PromptOps', 'Open-source, developer-centric PromptOps platform for managing prompts and AI model requests.'],
  ['Traceloop', 'traceloop.com', 'Freemium', 'Free / Enterprise', 4.8, 3100, 'OpenLLMetry Platform', 'OpenTelemetry-based observability for LLM applications with automated regression testing.'],
  ['Rivet by Ironclad', 'rivet.ironcladapp.com', 'Open Source', '100% Free & Open Source', 4.8, 5400, 'Visual AI Programming', 'Open-source visual AI programming environment and TypeScript library for building complex agent flows.'],
  ['Promptbase', 'promptbase.com', 'Paid', 'Pay per prompt', 4.4, 7800, 'Prompt Marketplace', 'Marketplace for buying and selling high-performance prompts for Midjourney, ChatGPT, and Claude.'],
  ['FastChat', 'github.com/lm-sys/FastChat', 'Open Source', '100% Free & Open Source', 4.8, 16200, 'LMSYS Benchmark', 'Open platform for training, serving, and evaluating LLM chatbots behind the LMSYS Chatbot Arena.'],
  ['CodeLlama', 'ai.meta.com/research', 'Open Source', 'Free & Open Weights', 4.7, 18500, 'Meta Code Model', 'State-of-the-art coding language model by Meta built on top of the Llama 2 architecture.'],
  ['MutableAI', 'mutable.ai', 'Freemium', 'Free / $15/mo', 4.6, 3700, 'Auto Documentation', 'AI-assisted software development platform turning repositories into interactive wikis.'],
  ['Codiga', 'codiga.io', 'Freemium', 'Free / $14/mo', 4.5, 4800, 'Real-Time Static Analysis', 'Static code analysis tool providing instant automated code reviews and snippet sharing.'],
  ['Stenography', 'stenography.dev', 'Freemium', 'Free / $10/mo', 4.6, 3100, 'Code Explainer', 'API and extension that automatically documents code and generates readable explanations.'],
  ['Safurai', 'safurai.com', 'Free', '100% Free', 4.5, 4200, 'Developer Extension', 'AI code assistant extension optimized for quick refactoring, test generation, and bug fixing.'],
  ['Adrenaline', 'useadrenaline.com', 'Freemium', 'Free / $19/mo', 4.6, 5300, 'Codebase Q&A', 'AI search and conversational agent that explains any GitHub repository in plain English.'],
  ['AutoPR', 'github.com/irgolic/AutoPR', 'Open Source', '100% Free & Open Source', 4.5, 2700, 'Automated PRs', 'GitHub Action that automatically writes pull requests in response to new repository issues.'],
  ['AnyChat Dev', 'anychat.ai', 'Freemium', 'Free / $15/mo', 4.5, 2100, 'Developer Assistant', 'Integrated developer copilot uniting internal documentation with external stack overflow answers.'],
  ['Codiumate PR-Agent', 'github.com/Codium-ai/pr-agent', 'Open Source', '100% Free & Open Source', 4.9, 13100, 'Automated PR Tool', 'Open-source autonomous agent providing automated pull request analysis, feedback, and labels.'],
  ['Phind V8', 'phind.com', 'Freemium', 'Free / $20/mo Pro', 4.8, 14200, 'Fast Coder Model', 'Specialized developer model delivering instant, technically grounded solutions to engineering questions.'],
  ['Braintrust Proxy', 'braintrust.dev', 'Freemium', 'Free / Usage', 4.8, 3100, 'AI Gateway', 'High-speed proxy and caching layer for enterprise language model API calls.'],
  ['Giskard Testing', 'giskard.ai', 'Open Source', 'Free Open Source', 4.7, 4500, 'Model Security', 'Open-source testing framework evaluating LLM vulnerability and data leak risks.'],
  ['OpenRouter SDK', 'openrouter.ai', 'Freemium', 'Pay per token', 4.9, 8700, 'Universal SDK', 'Developer SDK providing unified billing and fallbacks across 200+ AI models.'],
  ['Groq API', 'groq.com', 'Freemium', 'Free / Usage', 4.9, 15400, 'Fast Inference API', 'Ultra-low-latency API streaming tokens at 500+ tokens per second.'],
  ['Together Inference', 'together.ai', 'Paid', 'Pay per token', 4.8, 9200, 'Cloud Fine-Tuning', 'Scalable GPU infrastructure for fine-tuning and running open-weights LLMs.'],
  ['Fireworks Dev', 'fireworks.ai', 'Paid', 'Pay per token', 4.8, 7600, 'Compound AI', 'Production platform for compound AI systems with function calling and JSON mode.'],
  ['DeepInfra Compute', 'deepinfra.com', 'Paid', 'Pay per token', 4.7, 5100, 'Cost Optimized', 'Serverless inference endpoints for Llama, Mistral, and Whisper models.'],
  ['Anyscale Endpoints', 'anyscale.com', 'Paid', 'Pay per token', 4.7, 6300, 'Ray Distributed', 'Managed Ray platform for building and serving scalable AI applications.'],
  ['Modal Labs', 'modal.com', 'Freemium', 'Free tier / Pay per second', 4.9, 9800, 'Serverless GPU', 'Run generative AI pipelines and Python batch jobs on cloud GPUs with zero setup.'],
  ['Baseten', 'baseten.co', 'Paid', 'Pay as you go', 4.8, 5400, 'Model Deployment', 'Serverless deployment and autoscaling infrastructure for open-source AI models.']
];

additionalCoding.forEach((item) => {
  module.exports.push({
    name: item[0],
    domain: item[1],
    pricingModel: item[2],
    pricingStarting: item[3],
    rating: item[4],
    reviewCount: item[5],
    badge: item[6],
    shortTagline: item[7],
    detailedDescription: `${item[0]} is an enterprise-grade developer productivity solution engineered to accelerate software construction cycles. By integrating intelligent code synthesis, semantic repository search, and automatic testing routines, it eliminates repetitive boilerplate and accelerates bug diagnosis. Engineering organizations rely on it to uphold pristine code quality standards.`,
    tags: ['Developer Tools', 'Coding AI', 'Software Engineering', 'Code Quality', 'DevOps'],
    pros: ['Substantial reduction in manual boilerplate and refactoring time', 'Deep architectural awareness across repositories and environments', 'Seamless integration into standard developer workflows and terminal tools'],
    cons: ['Requires deliberate code verification on complex edge cases', 'Advanced team analytics and VPC deployments require paid licensing tiers'],
    bestFor: 'Software developers, engineering teams, and technical architects optimizing development velocity.'
  });
});
